### ISSUE TITLE
[Android] Issues needing verification on Android 1.10.x build 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10102]
- [ ] Upgrade from Chromium 81 to Chromium 83 Chromium/upgrade major (#9760)
- [ ] [Android] First NTP doesn't load SR images even when component is ready (#10033)
- [ ] [Android] Claim notification is not closed even when claim itself is already received (#9833)
- [ ] [Android] Promotion notification is not cleared when error happens (#9657)
