### ISSUE TITLE
[Android] Manual Test run on Android ARM for 1.10.x HF Release

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10393]
## Per release specialty tests

- [x] [Android] App crashes on opening new tab after disabling Custom Homepage theme (#10296)
- [x] [Android] Ads on YT (#10241)
- [x] [Android] Disable twitter support in the panel (#10208)
- [x] [Android] Bottom toolbar setting reverted (possibly on update) (#9843)

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Custom tabs

- [x] Make sure Brave handles links from Gmail, Slack
- [x] Make sure Brave works as custom tabs provide with Chrome browser
- [x] Ensure custom tabs work even with sync enabled/disabled

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [x] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
- [x] Verify that default Bravery settings take effect on pages with no site settings
- [x] Verify that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Visit https://browserleaks.com/webrtc, ensure 2 blocked items are listed in shields
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content Tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Verify that context menus work in the new twitter tab
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password is auto-populated when you visit the site again
- [x] Open a GitHub issue and type some misspellings, make sure they aren't autocorrected
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

## Top sites view

- [x] Long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.
