### ISSUE TITLE
[Android] Manual Test run on Android Tab for 1.10.x HF2 Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10458]
## Per release specialty tests

- [x] [Android] Inject cosmetic filtering scriptlets in all frames #10436
- [x] [Android] Implement internal issue #10452
- [x] [Android] Balances on Android suddenly displaying 0.0 BAT (after May 2020 ad payout) #9992

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## YT Specific

- [x] Ensure that https://github.com/brave/brave-browser/issues/10436 didn't regress ads on YT
  - [x] ensure that ads aren't being displayed on YT (preroll and post video ads)
  - [x] ensure that "Background video playback" works as expected and hasn't regressed

## Custom tabs

- [ ] Make sure Brave handles links from Gmail, Slack
- [ ] Make sure Brave works as custom tabs provide with Chrome browser
- [ ] Ensure custom tabs work even with sync enabled/disabled

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by srirambv** [comment]
Looks good. https://github.com/brave/brave-browser/issues/9992 verified by @samartnik
