### ISSUE TITLE
[Android] Issues to be tested on Android 1.11.x 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#10587]
Following issues have been fixed as part of 1.11.x Beta release. These needs to be checked on for 1.11.x Android Release

- [ ] [Android] Expand estimated pending rewards to three decimal places (#10028)
- [ ] [Android] Remove `Rewards Debug` settings on x86 (#10011)
- [ ] [Android] Fix rewards db import on Android 10 (#9991)
- [ ] [Android] Implement simpler Shield Panel (#9888)
- [ ] [Android] Rewards icon reappears after restarting when SafetyNet fails (#9871)
- [ ] [Android] add a way for QA to import wallets into rewards (#9772)
- [ ] have a way to view server errors in UI (#9533)
- [ ] Remove 'get paid' verbiage on Sponsored Images and make BRE update (#8360)
- [ ] [Android] Rate Brave (#8243)
- [ ]  There was a problem processing your contribution message on BAT logo (#10312
