### ISSUE TITLE
Manual test run on Windows x64 for 1.11.x Hotfix 1 - Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#10881]
## Per release specialty tests

- [ ] Brave freezes or hangs on launch when there are a large number of `Cookies and other site data` #9481
- [x] [Desktop] `Google Safe Browsing` in `brave://settings/privacy` is not translated #10745
- [x] [Desktop] `Reset settings` is not translated #10746
- [x] [Desktop] `Continue running background apps when Brave is closed` is not translated #10755

### Installer

- [x]  Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x]  Make sure that data from the last version appears in the new version OK
- [x]  With data from the last version, verify that
  - [x]  bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x]  cookies are preserved
  - [x]  installed extensions are retained and work correctly
  - [x]  opened tabs can be reloaded
  - [x]  stored passwords are preserved
  - [x]  unpinned tabs can be pinned

### Widevine

- [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Session storage

- [x]  Temporarily move away your browser profile and test that a new profile is created when browser is launched 
  - macOS - `~/Library/Application\ Support/BraveSoftware/`
  - Windows - `%userprofile%\appdata\Local\BraveSoftware\` 
  - Linux(Ubuntu) - `~/.config/BraveSoftware/`
- [x]  Test that windows and tabs restore when closed, including active tab
  - [x] Ensure that the tabs in the above session are being lazy loaded when the session is restored

## Update tests

- [x]  Verify visiting `brave://settings/help` triggers update check
- [x]  Verify once update is downloaded, prompts to `Relaunch` to install update

#### Components

- [ ] Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.
