### ISSUE TITLE
Final step for url handling

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#10987]
@emerick did awesome job extracting all responses in separate folder. So now we need just do final step in this story. We need to merge request and response folder and create class per endpoint. This means every endpoint would have their own class. We should have abstracted class so that all endpoints would have the same structure.

Example class (for file in internals `/endpoint/promotion/get_available/get_available.h`):
```c++
namespace ledger {
namespace endpoint {
namespace promotion {

using GetAvailableCallback = std::function<void(
    const ledger::PromotionList&, 
    const std::vector<std::string>&)>;

class GetAvailable {
 public:
  explicit GetAvailable(bat_ledger::LedgerImpl* ledger);
  ~GetAvailable() override;

  void Request(GetAvailableCallback callback);

 private:
  std::string GetUrl(
    const std::string& payment_id,
    const std::string& platform);

  ledger::Result CheckStatusCode(const int32 status_code);

  ledger::Result ParseResponse(const std::string& body);

  void OnRequest(
    const ledger::UrlResponse& response,
    GetAvailableCallback callback);

  bat_ledger::LedgerImpl* ledger_;  // NOT OWNED
};

}  // namespace promotion
}  // namespace endpoint
}  // namespace ledger
```

Servers:
- [x] api https://github.com/brave/brave-browser/issues/11106
- [x] promotion https://github.com/brave/brave-browser/issues/11203
- [x] rewards https://github.com/brave/brave-browser/issues/11283
- [x] cdn https://github.com/brave/brave-browser/issues/11285
- [x] payment https://github.com/brave/brave-browser/issues/11284
- [x] uphold https://github.com/brave/brave-browser/issues/11286

**Comment by NejcZdovc** [comment]
all subtasks done
