### ISSUE TITLE
Manual test run on Linux for 1.12.x - Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11176]
## Per release specialty tests

 - [x] Search engine updates.([#10890](https://github.com/brave/brave-browser/issues/10890))
 - [x] Upgrade from Chromium 84.0.4147.111 to Chromium 84.0.4147.125 #11153
 - [x] [Desktop] Sync v2 initial bookmarks duplication.([#11116](https://github.com/brave/brave-browser/issues/11116))
 - [x] Reset Rewards crashes the browser in certain cases.([#11125](https://github.com/brave/brave-browser/issues/11125))

### Installer

- [x]  Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x]  Make sure that data from the last version appears in the new version OK
- [x]  With data from the last version, verify that
  - [x]  bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x]  cookies are preserved
  - [x]  installed extensions are retained and work correctly
  - [x]  opened tabs can be reloaded
  - [x]  stored passwords are preserved
  - [x]  unpinned tabs can be pinned

### Widevine

- [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Rewards

- [x]  Verify account balance shows correct BAT and USD value
- [x]  Verify you are able to restore a wallet
- [x]  Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x]  Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [x]  Verify you are able to make one-time tip and they display in tips panel
- [x]  Verify you are able to make recurring tip and they display in tips panel
- [x]  Verify you can tip a verified publisher
- [x]  Verify you can tip a verified YouTube creator
- [x]  Verify you are able to perform a contribution
- [x]  Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators
- [x]  Upgrade from older version
  - [x]  Verify the wallet balance is retained and wallet backup code isn't corrupted
  - [x]  Verify auto-contribute list is not lost after upgrade
  - [x]  Verify tips list is not lost after upgrade
  - [x]  Verify wallet panel transactions list is not lost after upgrade

## Update tests

- [x]  Verify visiting `brave://settings/help` triggers update check
- [ ]  Verify once update is downloaded, prompts to `Relaunch` to install update

#### Components
- [x]   Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

**Comment by kjozwiak** [comment]
Please don't start the above runs till we merge https://github.com/brave/brave-core/pull/6393 & https://github.com/brave/brave-browser/pull/11160 into `1.12.x` and new RC's are created 👍

**Comment by kjozwiak** [comment]
Above can now be checked with https://github.com/brave/brave-browser/releases/tag/v1.12.112.

**Comment by btlechowski** [comment]
LGTM

Verification passed on

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS
