### ISSUE TITLE
Manual test run on Windows x64 for 1.13.x - Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11376]
## Per release specialty tests
 - [x] Out of band user model updates for Brave Ads.([#9147](https://github.com/brave/brave-browser/issues/9147))
 - [x] [Desktop] design updates to customize dialog follow up to #9455.([#10318](https://github.com/brave/brave-browser/issues/10318))
 - [x] [Desktop] Huge ads priority in logs when priority is set to zero.([#10694](https://github.com/brave/brave-browser/issues/10694))
 - [x] [Desktop] onCreateConfirmation and onFetchPaymentToken fail for countries that send ?? for countryCode  - follow up to 9823.([#10710](https://github.com/brave/brave-browser/issues/10710))
 - [x] [Desktop] Show estimated conversion value in confirm trade window.([#10756](https://github.com/brave/brave-browser/issues/10756))
 - [x] [Desktop] Transaction countdown timer speeds up after reconnecting to the network.([#10763](https://github.com/brave/brave-browser/issues/10763))
 - [x] Refresh token should be used in re-authorization flow (Gemini).([#10978](https://github.com/brave/brave-browser/issues/10978))
 - [x] Update Gemini widget Oauth flow to use PKCE.([#11043](https://github.com/brave/brave-browser/issues/11043))
 - [x] Sell panel should include to the total amount to be received in USD (Gemini).([#11046](https://github.com/brave/brave-browser/issues/11046))
 - [x] NTP Settings Design follow up.([#11103](https://github.com/brave/brave-browser/issues/11103))
 - [x] [Desktop] Claim doesn't work for existing wallets .([#11144](https://github.com/brave/brave-browser/issues/11144))
 - [x] [Desktop] Removed anonymous address from Uphold flow.([#11150](https://github.com/brave/brave-browser/issues/11150))
 - [x] [Desktop] user funds do not move to Uphold - follow up to 8428.([#11298](https://github.com/brave/brave-browser/issues/11298))

### Installer

- [x]  Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x]  Make sure that data from the last version appears in the new version OK
- [x]  With data from the last version, verify that
  - [x]  bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x]  cookies are preserved
  - [x]  installed extensions are retained and work correctly
  - [x]  opened tabs can be reloaded
  - [x]  stored passwords are preserved
  - [x]  unpinned tabs can be pinned

### Widevine

- [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Rewards

- [x]  Verify account balance shows correct BAT and USD value
- [x]  Verify you are able to restore a wallet
- [x]  Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x]  Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [x]  Verify you are able to make one-time tip and they display in tips panel
- [x]  Verify you are able to make recurring tip and they display in tips panel
- [x]  Verify you can tip a verified publisher
- [x]  Verify you can tip a verified YouTube creator
- [x]  Verify you are able to perform a contribution
- [x]  Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators
- [x]  Upgrade from older version
  - [x]  Verify the wallet balance is retained and wallet backup code isn't corrupted
  - [x]  Verify auto-contribute list is not lost after upgrade
  - [x]  Verify tips list is not lost after upgrade
  - [x]  Verify wallet panel transactions list is not lost after upgrade

## Update tests

- [x]  Verify visiting `brave://settings/help` triggers update check
- [x]  Verify once update is downloaded, prompts to `Relaunch` to install update

#### Components
- [x]   Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.
