### ISSUE TITLE
Manual test run on Android x86 for Android 1.13.x - Release

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11554]
## Per release specialty tests
 - [ ] [Android] Onboarding Notification. ([#10191](https://github.com/brave/brave-browser/issues/10191))
 - [ ] [Android] Sending link from Android to Desktop doesn't work. ([#11077](https://github.com/brave/brave-browser/issues/11077))
 - [ ] [Android] Update onboardingv2 based on internal feedback. ([#11169](https://github.com/brave/brave-browser/issues/11169))
 - [ ] [Android] "Sync isn't working" modal on new installs. ([#11210](https://github.com/brave/brave-browser/issues/11210))
 - [ ] [Android] Shields onboarding is not dismissed when a new tab is opened. ([#11318](https://github.com/brave/brave-browser/issues/11318))
 - [ ] [Android] Privacy report modal position resizes when switching between Websites and Trackers. ([#11320](https://github.com/brave/brave-browser/issues/11320))
 - [ ] [Android] Text on Brave Desktop info card looks like link . ([#11326](https://github.com/brave/brave-browser/issues/11326))
 - [ ] [Android][Follow up #11210] Sync not working message showing up on private tabs. ([#11363](https://github.com/brave/brave-browser/issues/11363))
 - [ ] [Android] Pdf not opening. ([#11420](https://github.com/brave/brave-browser/issues/11420))
 - [ ] [Android] Missing translation for Turn on privacy stats. ([#11490](https://github.com/brave/brave-browser/issues/11490))
 - [ ] [Android] Remove onboarding for existing user. ([#11539](https://github.com/brave/brave-browser/issues/11539))
 - [ ] Upgrade from Chromium 85.0.4183.78 to Chromium 85.0.4183.83.(https://github.com/brave/brave-browser/issues/11401)
 - [ ] Update l10n for Chromium 85 (https://github.com/brave/brave-browser/issues/11395)
 - [ ] [Android] Fix crash on opening search engine in debug build (https://github.com/brave/brave-browser/issues/11022)
- [ ] [Android] cross promotional Modal for existing user  https://github.com/brave/brave-browser/issues/10924
- [ ] [Android] Bottom bar tab swipe is not working (https://github.com/brave/brave-browser/issues/10668)
- [ ] [Android] Onboarding V2 (https://github.com/brave/brave-browser/issues/9555)

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Visual look

- [x] Make sure thereafter every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [x] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected 

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by LaurenWags** [comment]
above tests verified using 1.13.83 with Asus Zenfone (x86) running BraveModernx86.apk
