### ISSUE TITLE
[Desktop] Manual test run on Windows x64 for 1.13.x - Release #3

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11629]
## Per release specialty tests

- [x] [Desktop][CW] Gemini widget displayed in unsupported region(s) - #11483
- [x] [Desktop] Sign setup.exe - #11378
- [x] Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102 - #11621
- [x] Brave Rewards service is associated to Tor Profiles #11223
- [x] Sometimes clicking ad notifications doesn't do anything (click not being registered) #11042

### Installer

- [x]  Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Widevine

- [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Rewards

- [x]  Verify account balance shows correct BAT and USD value
- [x]  Verify you are able to restore a wallet
- [x]  Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x]  Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [x]  Verify you are able to make one-time tip and they display in tips panel
- [x]  Verify you are able to make recurring tip and they display in tips panel
- [x]  Verify you can tip a verified publisher
- [x]  Verify you can tip a verified YouTube creator
- [x]  Verify you are able to perform a contribution
- [x]  Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators

## Update tests

- [x]  Verify visiting `brave://settings/help` triggers update check
- [x]  Verify once update is downloaded, prompts to `Relaunch` to install update

#### Components
- [x]   Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

### Upgrade

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Installed extensions are retained and work correctly
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained
  - [x] Rewards
    - [x] Wallet balance is retained
    - [x] Auto-contribute list is retained
    - [x] Both Tips and Monthly Contributions are retained
    - [x] Wallet panel transactions list is retained
    - [x] Changes to rewards settings are retained
  - [x] Ads
    - [x] Both `Estimated pending rewards` & `Ad notifications received this month` are retained
    - [x] Changes to ads settings are retained
    - [x] Ensure that ads are not being enabled when upgrading to a new version if they were disabled
    - [x] Ensure that ads are not disabled when upgrading to a new version if they were enabled

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.
