### ISSUE TITLE
[Android] Manual test run on Android x86 for 1.13.x - Release #3

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#11635]
## Per release specialty tests

- [ ] [Android] Settings menu unreachable on Android 7 - #11620
- [x] [Android] Crash from playstore build #11625 - https://github.com/brave/brave-browser/issues/11625
- [x] Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102 - #11621

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Visual look

- [x] Make sure thereafter every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [x] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected 

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by LaurenWags** [comment]
Tests above verified using Asus Zenfone (x86) with Android 6.0 running 1.13.86 BraveModernx86.apk
