### ISSUE TITLE
[Android] Issues to be verified from 1.13.x Release #1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11636]
- [x] [Android] [Security] prune log responses (#11456)
- [x] Upgrade from Chromium 85.0.4183.78 to Chromium 85.0.4183.83. (#11401)
- [x] Update l10n for Chromium 85. (#11395)
- [x] [Android] Sample ad doesn't open landing page when rewards is enabled (#11323)
- [x] Disable rewards logs and remove existing ones (#11260)
- [x] [Android] Add developer option to enable rewards vlog output ARM (#11088)
- [x] [Android] Fix crash on opening search engine in debug build (#11022)
- [x] [Desktop] Ad conversions fail for pages which use pushState (#11012)
- [x] [Android] cross promotional Modal for existing user (#10924)
- [x] [Android] Remove unused code for BottomSheetBehavior (#10865)
- [x] [Android] Bytecode patch is not applied to SearchEngineAdapter in release (#10773)
- [x] [Android] Location service message in Search engines settings (#10713)
- [x] [Android] Bottom bar tab swipe is not working Chromium/waiting upstream (#10668)
- [x] [Android] Implement Desktop -> Android cross promotional Modal (#10571)
- [x] [Android] Add "refresh status" feature in Brave Rewards dropdown tipping panel (#10005)
- [x] Audit server responses (#9666)
- [x] [Android] Onboarding V2 (#9555)
- [x] Fingerprinting 2.0: Plugins (#9435)
- [x] Implement new persona creation (#8428)
