### ISSUE TITLE
[Android] Issues to be verified from 1.14.x Release #1 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11721]
- [ ] Stop modifying WebRTC Web APIs when fingerprinting protection=strict (#11310)
- [ ] [Desktop] Promotion server url handling (#11203)
- [ ] Next payment date is null in Ads panel (#11062)
- [ ] [Desktop] Brave accepts TLS 1.0 and TLS 1.1 without any warning! (#10607)
- [ ] Move confirmations into ads process (#9870)

**Comment by kjozwiak** [comment]
Added the following two issues into the above which will also need to be added into https://github.com/brave/brave-browser/pull/11780.
```
- Fingerprinting 2.0: hardwareConcurrency (#10808)
- Fingerprinting 2.0: enumerateDevices randomization (#11271)
```
