### ISSUE TITLE
Implement Brave VPN on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#12197]
## Description 
Please search for the spec "Brave VPN on Android" for details

## Related issues / sub-issues 
- [x] [Guardian API integration for VPN](https://github.com/brave/brave-browser/issues/14048)
- [x] [VPN install problems UX improvements](https://github.com/brave/brave-browser/issues/13981)
- [x] [Add VPN Enabled Notification](https://github.com/brave/brave-browser/issues/13985)
- [x] [Add support for server/geo selection](https://github.com/brave/brave-browser/issues/13986)

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Wow

**Comment by bsclifton** [comment]
Great progress being made here! Wanted to share a public update 😄 

- We have an implementation (including UI) which works on Android 11 ([see here](https://github.com/brave/brave-core/tree/brave_vpn_ui_android)) which adds VPN an in-app-purchase
- When trying to test this branch out we're running into a weird error. Basically when uploading the arm64 APK to the Google Play Store (for internal testing) a generic "upload failed" error is happening
- We're working on resolving this error now
- Android 10 and earlier implementation is also being worked on; still a work in progress

**Comment by Uni-verse** [comment]
Verified the following issues mentioned in https://github.com/brave/brave-browser/issues/12197#issuecomment-1108883558 for 1.39.x  

- [x] Wireguard implementation for VPN  #22199
- [x] [Android VPN] [Beta User Feedback] Fix VPN Icon (under settings) color #22072
- [x] [Android VPN] [Beta User Feedback] Change VPN Icon #21995

known Issues encountered: 

1. VPN setting icon does not match spec - https://github.com/brave/brave-browser/issues/22848
2. VPN Support page url needs to be updated on Android - https://github.com/brave/brave-browser/issues/22950 
3. Expiry date should specify if its for trial or for subscription - https://github.com/brave/brave-browser/issues/23004
