### ISSUE TITLE
Release Checklist for Ethereum Remote Client 1.0.24 (Release Channel)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#12908]
Feel free to copy this into an issue if you want to keep track of items per-milestone.

### Prerequisites

- [ ] Double-check the release/milestone and ensure everything has been QA'd

### Release Notes to Staging

- [ ] Mark closed issues in github as `release-notes/exclude` or `release-notes/include`
- [ ] Commit release notes to [CHANGELOG.md](https://github.com/brave/ethereum-remote-client/blob/master/CHANGELOG.md) in `brave/ethereum-remote-client` master branch, must be completed before release to production Jenkins build job is run
- [ ] Stage release notes to https://github.com/brave/ethereum-remote-client/releases

### Test Staging for Updates

- [ ] Install a prior version of Ethereum Dev Component and update via command line parameters `--use-dev-goupdater-url`
   - [ ] Verify update works fine and able to login to account
   - [ ] Confirm new version matches in `brave://components`
- [ ] QA summary and sign off report under #release via Slack

### Release to production download locations

- [ ] Publish GitHub release (remove 'pre-release' checkmark)

### Clear Production Fastly cache

- [ ] Clear Fastly cache for production and publish

### Production Tests (Upgrade/Clean Install)

- [ ] Wait for confirmation that component update works on Windows
- [ ] Wait for confirmation that component update works on macOS
- [ ] Wait for confirmation that component update works on Linux
- [ ] Create a new wallet and verify the new component is downloaded

### Announcements

- [ ] Publish the release notes to `GitHub`
- [ ] Notify #announcements, #community of the latest release with a link to the release notes

### Closing milestones

- [ ] Set a release date and close the appropriate milestone under https://github.com/brave/brave-browser/milestones
