### ISSUE TITLE
Pending verifications/Release Notes from 1.17.x Release #3

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#12933]
Current list of issues that have been fixed/resolved in [`1.17.x Release #3`](https://github.com/brave/brave-browser/milestone/158) but haven't been verified by QA as  [`1.17.x Release #3`]https://github.com/brave/brave-browser/milestone/158) was released on `Android` only.

- [ ] Provide a "Don't show again" button on the info bar #12482
- [ ] Need text change for `Ad notifications received this month` #12719
- [ ] Error with the context menu in the bookmarks bar (german language) #12844

Current list of issues that are `release-notes/include` and need to be added into the `1.17.x Release #2` release notes:

- Provide a "Don't show again" button on the info bar #12482
- Need text change for `Ad notifications received this month` #12719
- Error with the context menu in the bookmarks bar (german language) #12844

List of issues that don't need to be QA'd but were also in [`1.17.x Release #3`](https://github.com/brave/brave-browser/milestone/158):

- Rebase Sparkle to 1.24.0 for universal binary support #12879
