### ISSUE TITLE
M1/arm64 macOS issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12953]
The following issues were found which appear to be specific to M1/arm64 macOS builds:
- [x] [Desktop] Widevine does not work on M1/macOS-arm64 #12950
- [ ] [Desktop] No option to enable Flash on M1/arm64 macOS from URL bar #12951
- [x] [Desktop] Brave is listed in System reports as an iOS app for M1/arm64 #12954

Additionally, the below issues were identified during testing which are not specific to M1/arm64 but do reproduce using those builds:
- Geolocation not using correct service #12952
- Ads received this month isn't updating on brave://rewards in Ads panel #12944

**Comment by bsclifton** [comment]
Related [arm64 support for macOS (Apple Silicon, M1 CPU)](https://github.com/brave/brave-browser/issues/12819)

**Comment by dotone-101** [comment]
the browser IDE of aws (aws cloud9) works ok until you try to run a script. Also the terminal doesn't open. The same works well using safari. 
<img width="225" alt="Screenshot 2021-01-18 at 5 09 04 PM" src="https://user-images.githubusercontent.com/77618800/104924174-10c87700-59c3-11eb-800f-9640fde2e728.png">
<img width="662" alt="Screenshot 2021-01-18 at 5 08 01 PM" src="https://user-images.githubusercontent.com/77618800/104924178-12923a80-59c3-11eb-9785-eb6161e1a1c0.png">

**Comment by LaurenWags** [comment]
Testing notes for above issues can be found under:
- [Desktop] Brave is listed in System reports as an iOS app for M1/arm64 - https://github.com/brave/brave-browser/issues/12954#issuecomment-763595329
- [Desktop] Widevine does not work on M1/macOS-arm64 - https://github.com/brave/brave-browser/issues/13074#issuecomment-751938530

The remaining issue, https://github.com/brave/brave-browser/issues/12951, is still open. Since Flash is now deprecated, perhaps that issue should be closed as `wontfix`. wdyt @rebron?

**Comment by rebron** [comment]
I closed out #12951. I think we can close this one out too.

**Comment by dotone-101** [comment]
awesome.. it works now!!
