### ISSUE TITLE
[Android] Pending verifications/Release Notes from 1.18.x Release #1

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#13163]
The below issues need to be checked with 1.18.x Release #2 on Android:
- [x] brave rewards not being removed from URL even though disabled via settings #12533
- [x] Staging grants don't show up instantly when wallet is created #12491
- [x] [Android] Implement earn&give onboarding #12141
- [x] Remove redundant rewards setting to address user confusion #11467

The below issues are marked as `release-notes/include` and need to be included in this release's notes:
- [x] brave rewards not being removed from URL even though disabled via settings #12533
- [x] [Android] Implement earn&give onboarding #12141
- [x] Remove redundant rewards setting to address user confusion #11467

**Comment by LaurenWags** [comment]
Confirmed above issues are included in Release Notes issue: https://github.com/brave/brave-browser/issues/13249

Confirmed above issues have been verified on appropriate platforms
