### ISSUE TITLE
Release Checklist for Ethereum Remote Client 1.0.25 release

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#13436]
Feel free to copy this into an issue if you want to keep track of items per-milestone.

### Prerequisites

- [x] Double-check the release/milestone and ensure everything has been QA'd

### Release Notes to Staging

- [x] Mark closed issues in github as `release-notes/exclude` or `release-notes/include`
- [x] Commit release notes to [CHANGELOG.md](https://github.com/brave/ethereum-remote-client/blob/master/CHANGELOG.md) in `brave/ethereum-remote-client` master branch, must be completed before release to production Jenkins build job is run
- [x] Stage release notes to https://github.com/brave/ethereum-remote-client/releases

### Test Staging for Updates

- [x] Install a prior version of Ethereum Dev Component and update via command line parameters `--use-dev-goupdater-url`
   - [x] Verify update works fine and able to login to account
   - [x] Confirm new version matches in `brave://components`
- [x] QA summary and sign off report under #release via Slack

### Release to production download locations

- [x] Publish GitHub release (remove 'pre-release' checkmark)

### Clear Production Fastly cache

- [x] Clear Fastly cache for production and publish

### Production Tests (Upgrade/Clean Install)

- [x] Wait for confirmation that component update works on Windows
- [x] Wait for confirmation that component update works on macOS
- [x] Wait for confirmation that component update works on Linux
- [x] Create a new wallet and verify the new component is downloaded

### Announcements

- [x] Publish the release notes to `GitHub`
- [ ] Notify #announcements, #community of the latest release with a link to the release notes

### Closing milestones

- [x] Set a release date and close the appropriate milestone under https://github.com/brave/brave-browser/milestones
