### ISSUE TITLE
Properly implement rewards/ads related P3A questions

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#13996]
https://github.com/brave/brave-browser/wiki/P3A

QQs 11-14 and 17 almost never worked properly and were broken during majore refactorings. If they are still needed we need to fix them and add tests as appropriate

**Comment by bsclifton** [comment]
Related tickets:
- [ ] [Implement P3A metric "Q11: What is the state of your Brave Rewards wallet"](https://github.com/brave/brave-browser/issues/7634)
- [ ] [Brave.Rewards.TipsState.2 value 4 isn't captured when a recurring tip is set](https://github.com/brave/brave-browser/issues/8301)
- [ ] [Incorrect response values for Auto-contribute](https://github.com/brave/brave-browser/issues/10088)
- [ ] [Brave.Rewards.AdsState is returning an invalid response value in the initial profile load](https://github.com/brave/brave-browser/issues/13546)
- [ ] [Brave.Rewards.TipsState.2 is returning an invalid value when a one-time tip is sent](https://github.com/brave/brave-browser/issues/13549)

**Comment by bsclifton** [comment]
@emerick I updated https://github.com/brave/brave-browser/wiki/P3A to remove `BROKEN` next to questions 13 and 14 😄

I missed one issue in the checklist above (doh) - question 12 https://github.com/brave/brave-browser/issues/8296
Would you be able to check that one out too?

**Comment by emerick** [comment]
@bsclifton Yup, will do!

**Comment by GeetaSarvadnya** [comment]
@emerick I have verified Q12. https://github.com/brave/brave-browser/issues/8296#issuecomment-850346150. It looks good and working fine. Please go ahead and remove the `BROKEN` text from question 12 from P3A Wiki.

**Comment by emerick** [comment]
@GeetaSarvadnya Thanks Geeta, I updated the wiki.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```


<!--StartFragment-->
Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8641

**Comment by GeetaSarvadnya** [comment]
@emerick:  When the Monthly tip is queued up (still not processed) the response value for `Brave.Rewards.TipsState.2`, is displayed as `2` (`Wallet created, no tips sent`). But the P3A Wiki for Q 14. metrics says `Wallet created, at least one monthly tip queued up or sent` - Is this correct? if so, it's a bug. or do we need to change the wording to `Wallet created, at least one monthly tip  sent`

**Comment by emerick** [comment]
@GeetaSarvadnya That seems like a valid bug, good catch!

**Comment by GeetaSarvadnya** [comment]
Verification is in progress on Samsung Galaxy Tab version Tab running `Bravemonoarm64_1.26.64`

<details>
<summary>Q 11: Brave.Rewards.WalletState</summary>

Covered the testing in https://github.com/brave/brave-browser/issues/7634#issuecomment-850539109
</details>

<details>
<summary>Q 12: Brave.Rewards.WalletBalance.2</summary>

Covered the testing in https://github.com/brave/brave-browser/issues/8296#issuecomment-850346150

</details>

<details>
<summary>Q 13: Brave.Rewards.AutoContributionsState.2</summary>

**_Clean profile:_**
<details>
<summary>Scenario 1: Check the response value when AC switch is enabled and no AC so far </summary>

1. Clean profile 1.26.x
2. Enable rewards

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `3` (`Auto-contribute enabled, no contribution so far`) when AC is enabled and no AC so far
![image](https://user-images.githubusercontent.com/38657976/120314754-32365980-c2f9-11eb-96ee-c5c248eb2392.png)

</details>

<details>
<summary>Scenario 2: Check the response value when Rewrads is enabled and AC switch is OFF </summary>

1. Clean profile 1.26.x
2. Enable rewards
3. Turn off AC switch

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `2` (`Wallet created, Auto-Contribute off`) when AC is enabled and AC switch is OFF
![image](https://user-images.githubusercontent.com/38657976/120316268-db318400-c2fa-11eb-9721-4012e13978bc.png)

</details>

<details>
<summary>Scenario 3: Check the response value when one AC is completed </summary>

1. Clean profile 1.26.x
2. Enable rewards and claim UGP grants
3. Open DDG and add it to the AC table
4. Trigger AC and wait for AC to complete

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `4` (`Auto-contribute enabled, one successful contribution so far`) when one AC is completed
![image](https://user-images.githubusercontent.com/38657976/120318554-9e1ac100-c2fd-11eb-98e6-c7adad47da2e.png)

</details>
<details>
<summary>Scenario 4: Check the response value when more than one successful AC completed</summary>

1. Clean profile 1.26.x
2. Enable rewards and claim UGP grants
3. Open DDG and add it to the AC table
4. Trigger 1st AC and wait for AC to complete
5. Trigger 2nd AC and wait for AC to complete

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `5` (`Auto-contribute enabled, more than one successful contribution so far`) when one AC is completed
![image](https://user-images.githubusercontent.com/38657976/120319744-f8685180-c2fe-11eb-80ad-d09ee46e61e6.png)

</details>

**_Upgrade profile:_**
<details>
<summary>Scenario 5: Install 1.25.x and enable rewards and then Turn OFF AC switch and then upgrade profile to 1.26.x </summary>

1. Clean profile 1.25.x enable rewards
2. Disable AC
3. Upgrade profile to 1.26.x

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `2` (`Wallet created, Auto-Contribute off`) when AC is disabled
![image](https://user-images.githubusercontent.com/38657976/120358219-e3ea8000-c323-11eb-8615-ef8ee14f8093.png)

</details>

<details>
<summary>Scenario 6: Install 1.25.x and enable rewards and then upgrade profile to 1.26.x </summary>

1. Clean profile 1.25.x enable rewards
2. Upgrade profile to 1.26.x

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `3` (`Auto-contribute enabled, no contribution so far`) when AC is enabled
![image](https://user-images.githubusercontent.com/38657976/120443790-9feb8f80-c3a4-11eb-833c-6c4d91672458.png)

</details>

<details>
<summary>Scenario 7: Install 1.25.x and enable rewards trigger one successful AC and then upgrade profile to 1.26.x </summary>

1. Clean profile 1.25.x enable rewards
2. Trigger one successful AC
3. Upgrade profile to 1.26.x

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `4` (`Auto-contribute enabled, one successful contribution so far`) when one successful AC is completed
![image](https://user-images.githubusercontent.com/38657976/120445464-44220600-c3a6-11eb-812d-add839a474dd.png)

</details>

<details>
<summary>Scenario 8: Install 1.25.x and enable rewards trigger more than one successful AC and then upgrade profile to 1.26.x </summary>

1. Clean profile 1.25.x enable rewards
2. Trigger more than one successful AC
3. Upgrade profile to 1.26.x

- Confirmed that the response value for `Brave.Rewards.AutoContributionsState.2` is displayed as `5` (`Auto-contribute enabled, more than one successful contribution so far`) when more than one successful AC is completed
![image](https://user-images.githubusercontent.com/38657976/120448595-581b3700-c3a9-11eb-8358-389eb750c2f1.png)


</details>

</details>

<details>
<summary>Q 14: Brave.Rewards.TipsState.2</summary>

**_Clean profile:_**

<details>
<summary>Scenario 1: Check the response value when wallet created, no tips sent</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `2` (`Wallet created, no tips sent`) when wallet created and no tip sent
![image](https://user-images.githubusercontent.com/38657976/120462553-ac79e300-c3b8-11eb-8042-f5689c70fd15.png)


</details>

<details>
<summary>Scenario 2: Check the response value when wallet created, one-time tip sent</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `3` (`Wallet created, one-time tip sent`) when wallet created and one time tip sent
![image](https://user-images.githubusercontent.com/38657976/120466329-8eae7d00-c3bc-11eb-9975-dd1b3df0361a.png)

</details>

<details>
<summary>Scenario 3: Check the response value when wallet created, at least one monthly tip queued up or sent</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `4` (`Wallet created, at least one monthly tip queued up or sent`) when wallet created and at least one monthly tip sent
![image](https://user-images.githubusercontent.com/38657976/120469676-4c873a80-c3c0-11eb-9966-77b90ac5953b.png)

</details>

<details>
<summary>Scenario 4: Check the response value when wallet created, one-time sent and at least one monthly tip queued up or sent</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `5` (`Wallet created, one-time sent and at least one monthly tip queued up or sent`) when wallet created one-time tip sent and at least one monthly tip sent
![image](https://user-images.githubusercontent.com/38657976/120469883-8ce6b880-c3c0-11eb-9d25-b1116385e4bb.png)

</details>

**_Upgrade profile:_**

<details>
<summary>Scenario 1: Install 1.25.x and enable rewards and send a one-time tip and upgrade profile to 1.26.x</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `3` (`Wallet created, one-time tip sent`) when wallet created and one-time tip sent

</details>

<details>
<summary>Scenario 2: Install 1.25.x and enable rewards and send a one-time tip and a monthly tip and upgrade profile to 1.26.x</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `5` (`Wallet created, one-time sent and at least one monthly tip queued up or sent`) when wallet created one-time tip sent and at least one monthly tip sent
</details>

<details>
<summary>Scenario 3: Install 1.25.x and enable rewards and send a one-time tip and a monthly tip (still not processed) and upgrade profile to 1.26.x</summary>

- Logged https://github.com/brave/brave-browser/issues/16193 - The response value isn't correct for monthly tip queued up scenarios

</details>

<details>
<summary>Scenario 4: Install 1.25.x and enable rewards and send multiple one-time tips and monthly tips and upgrade profile to 1.26.x</summary>

- Confirmed that the response value for `Brave.Rewards.TipsState.2` is displayed as `5` (`Wallet created, one-time sent and at least one monthly tip queued up or sent`) when wallet created one-time tip sent and at least one monthly tip sent

</details>

</details>

<details>
<summary>Q 17: Brave.Rewards.AdsState.2 </summary>

**_Clean profile:_**

<details>
<summary>Scenario 1: Check the response value when wallet created, ads not enabled</summary>

- Confirmed that the response value for `Brave.Rewards.AdsState.2`  is displayed as `4` (`Wallet created, ads enabled, then disabled, while Brave Rewards remains on`)  
![image](https://user-images.githubusercontent.com/38657976/120482815-1f8e5400-c3cf-11eb-8301-73f65f8dce96.png)

</details>

<details>
<summary>Scenario 2: Check the response value when wallet created, ads enabled</summary>

- Confirmed that the response value for `Brave.Rewards.AdsState.2`  is displayed as `3` (`Wallet created and ads enabled`) when wallet created and ads enabled
![image](https://user-images.githubusercontent.com/38657976/120482535-da6a2200-c3ce-11eb-9c88-6b4807d9e7cd.png)

</details>

- Logged a follow-up issue https://github.com/brave/brave-browser/issues/16194 for Ads related metrics

</details>
