### ISSUE TITLE
Only make requests to *.rewards.brave.com endpoints after Rewards opt-in

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#14277]
## Description 

Browser sometimes makes calls out to `*.rewards.brave.com` endpoints before user fully opts into Brave Rewards. For example, see https://github.com/brave/brave-site-specific-scripts/issues/41. Any `*.rewards.brave.com` requests should only occur if the user has pressed "Start using Brave Rewards" and generated a wallet. These calls can happen as a result of Greaselion or by clicking the BAT icon. 

Requests are made to the following domains, for example:

* `api.rewards.brave.com`
* `rewards.brave.com`
* `grant.rewards.brave.com`

## Steps to Reproduce

**Greaselion**

   1. Fresh profile
   2. Go to reddit.com or another site with site-specific Greaselion scripts
   3. Check for calls to `*.rewards.brave.com`

Another way:

**BAT icon**

   1. Fresh profile
   2. Click on BAT icon
   3. Although Brave Rewards is still disabled (i.e., "Start using Brave Rewards" has not yet been pressed), check for calls to `*.rewards.brave.com` 

Calls should be deferred until after the user has pressed "Start using Brave Rewards". 

## Expected result:

No requests needed until after opt-in.

## Task list

- [x] Content scripts/Greaselion case
- [ ] Clicking on Brave Rewards panel/BAT icon in the URL bar
- [ ] Clicking on in-line tipping button
- [ ] Navigating to brave://rewards settings page

**Comment by bsclifton** [comment]
There should only be a few more remaining cases (that we know of) for this:
1. Clicking tip icon (on GitHub/Reddit/Twitter). Used to get the verification status for entity being tipped
2. Clicking rewards icon in omnibox (on GitHub/Reddit/Twitter/Twitch/Vimeo/YouTube). Used to get the verification status for entity visited

Status TBD on Android (@deeppandya can you help verify?). All other cases have been closed (ex: with https://github.com/brave/brave-core/pull/8036). Nice work @zenparsing @emerick 😄

**Comment by bsclifton** [comment]
Given above - going to reprioritize this issue based on the remaining two cases

**Comment by holow29** [comment]
Is there a way to reset Brave Rewards status? I enabled it once but have since tried to disable it as much as possible - including turning off ads, hiding the rewards button, and resetting the wallet. However, I can't get back to the state where it says, "Start using Brave Rewards" without creating a new profile. Using my old profile, I still get calls to *.rewards.brave.com endpoints.

**Comment by bsclifton** [comment]
@holow29 I gave this a shot and here's what I found:
1. Clicked the gear on the top right of brave://rewards/
  ![image](https://user-images.githubusercontent.com/4733304/129670612-50193bd2-658a-484a-92cc-ac39c1d6ff47.png)
2. Picked `Reset` and clicked the orange button
  ![image](https://user-images.githubusercontent.com/4733304/129670664-9cf031a2-7b42-4c2e-a38e-e79c93c6255b.png)
3. Closed browser, re-opened
4. Visit brave://rewards/
5. The opt-in isn't showing again ☹️ Should this be showing again @Miyayes?
6. As long as Ads and Auto-contribute are off, the service should be OFF. You can verify under hamburger menu => More tools => Task Manager
7. Looks like Ledger service is still running (it shouldn't be)
  ![image](https://user-images.githubusercontent.com/4733304/129671086-3304a994-6eb5-4fc8-877a-564fde3ce14a.png)

cc: @brave/rewards-client

**Comment by holow29** [comment]
Potentially some more info: I restarted the browser and Utility: Bat Ledger Service was not running, and I didn't see any calls to *.rewards.brave.com endpoints. However, when I went to brave://rewards to ensure everything was off, the ledger service started again and remained running.
It seems like the ledger service should not start when simply visiting brave://rewards if ads/ac are off. Perhaps there needs to be a way to reset to the pre-opt-in state and maybe that will prevent the ledger service from starting automatically.

**Comment by bsclifton** [comment]
Thanks for testing! I raised issue today to @Miyayes - we can figure out next steps 😄 But as long as you quit the browser and re-open (as long as no brave://rewards windows are open), it won't be running Ledger

There is a possibility Ads service might run, if you enable Brave News. That's something to keep in mind. Even if you turn off Brave news, it'll still be running (that bug is captured by https://github.com/brave/brave-browser/issues/17491)

**Comment by Miyayes** [comment]
From latest look into this, it looks like Rewards endpoints and URLs are hit when user:

1. Clicks the BAT icon in the URL bar
2. Clicks on an in-line tipping button on a website like Twitter or Reddit

**Comment by diracdeltas** [comment]
@Miyayes thanks for the info! i will mostly defer this to @PrivacyMatters but i think we shouldn't be adding more of these. for instance it seems this has slightly regressed since https://github.com/brave/brave-browser/issues/14277#issuecomment-788143258 (now navigating to brave://rewards triggers a request)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.66 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 12.6 (Build 21G115)
```

**Comment by Uni-verse** [comment]
In Progress on Android ARM

Test Plan https://github.com/brave/brave-browser/issues/14277#issue-812772717.

<details>
<summary>Case: BAT icon - PASSED</summary>

1. Fresh profile, relaunch to pull griffin seed
2. Click on BAT icon
3. Although Brave Rewards is still disabled (i.e., "Start using Brave Rewards" has not yet been pressed), check for calls to `*.rewards.brave.com` 
4. Confirm no calls to `*.rewards.brave.com`
5. Go to twitter.com/emerick
6. Check for calls to `*.rewards.brave.com`
7. Confirm no calls to `*.rewards.brave.com`
8. Go to github.com/miyayes
9. Check for calls to `*.rewards.brave.com`
10. Confirm no calls to `*.rewards.brave.com`
12. Go to reddit.com/u/cryptojennie
13. Check for calls to `*.rewards.brave.com`
14. Confirm no calls to `*.rewards.brave.com`
15. Open NTP
16. Check for calls to `*.rewards.brave.com`
17. Confirm no calls to `*.rewards.brave.com`
18. Open browser Task Manager and confirm Ledger service is not running

* Confirmed no calls to `*.rewards.brave.com` after clicking the BAT icon, but not opting into Rewards

</details>

<details>
<summary>Case: brave://rewards page - PASSED</summary>

1. Fresh profile, relaunch to pull griffin seed
2. Visit brave://rewards
3. Although Brave Rewards is still disabled (i.e., "Start using Brave Rewards" has not yet been pressed), check for calls to `*.rewards.brave.com` 
4. Confirm no calls to `*.rewards.brave.com`
5. Go to twitter.com/emerick
6. Check for calls to `*.rewards.brave.com`
7. Confirm no calls to `*.rewards.brave.com`
8. Go to github.com/miyayes
9. Check for calls to `*.rewards.brave.com`
10. Confirm no calls to `*.rewards.brave.com`
12. Go to reddit.com/u/cryptojennie
13. Check for calls to `*.rewards.brave.com`
14. Confirm no calls to `*.rewards.brave.com`
15. Open NTP
16. Check for calls to `*.rewards.brave.com`
17. Confirm no calls to `*.rewards.brave.com`
18. Open browser Task Manager and confirm Ledger service is not running

* Confirmed no calls to `*.rewards.brave.com` after visiting brave://rewards, but not opting into Rewards

</details>

<details>
<summary>Case: In-line tip button - PASSED</summary>

1. Fresh profile, relaunch to pull griffin seed
2. Go to twitter.com/emerick
3. Click on an in-line tip button
---> nothing happens, panel does not open but it should. Remainder of test case cannot be executed until follow up issue is resolved.
5. Panel is displayed, but do not opt in to rewards. Close panel.
6. Check for calls to `*.rewards.brave.com`
7. Confirm no calls to `*.rewards.brave.com`
8.  Go to github.com/miyayes
9. Click on an in-line tip button 
---> nothing happens, panel does not open but it should. Remainder of test case cannot be executed until follow up issue is resolved.
10. Panel is displayed, but do not opt in to rewards. Close panel.
11. Check for calls to `*.rewards.brave.com`
12. Confirm no calls to `*.rewards.brave.com`
13. Go to reddit.com/u/cryptojennie
14. Click on an in-line tip button 
---> nothing happens, panel does not open but it should. Remainder of test case cannot be executed until follow up issue is resolved.
15. Panel is displayed, but do not opt in to rewards. Close panel.
16. Check for calls to `*.rewards.brave.com`
17. Confirm no calls to `*.rewards.brave.com`
18. Open NTP
19. Check for calls to `*.rewards.brave.com`
20. Confirm no calls to `*.rewards.brave.com`
21. Open browser Task Manager and confirm Ledger service is not running

</details>

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/202817008-f834082f-6dc4-4d4b-9b15-2cc643c5f66d.png">

**Comment by PrivacyMatters** [comment]
@Miyayes apologies for the delay.  re https://github.com/brave/brave-browser/issues/14277#issuecomment-1243057480 yes, it is acceptable

**Comment by Miyayes** [comment]
Thanks. @PrivacyMatters In any case, we actually went for the stronger route, and we make no calls to rewards-related endpoints until the user explicitly opts in/enables Brave Rewards :).
