### ISSUE TITLE
Work required before we can release Sidebar

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#14980]
## Description 
We have a Sidebar that is available in Nightly which can be enabled via brave://flags/#sidebar

Some specific issues have been captured and labeled with [feature/sidebar](https://github.com/brave/brave-browser/labels/feature%2Fsidebar)

This issue is intended to track work required before we can release an MVP (minimal viable product) of sidebar

## P1
- [x] Clicking a sidebar item should open in the current tab, not new tab (https://github.com/brave/brave-browser/issues/15084)
- [x] Show “Add to sidebar” menu on hover (https://github.com/brave/brave-browser/issues/15713)
- [x] Clicking a sidebar item that is already open in any tab/window should bring that into focus instead of opening another tab (https://github.com/brave/brave-browser/issues/15084)
- [x] Settings button in sidebar does not work (https://github.com/brave/brave-browser/issues/15084)
- [x] Show sidebar options don’t work (https://github.com/brave/brave-browser/issues/15592)
- [x] Drag to reorder sidebar items (https://github.com/brave/brave-browser/issues/15135)
- [x] Bookmarks in sidebar is empty (https://github.com/brave/brave-browser/issues/14950)
- [x] Responsive History - Settings ribbon needs to be hidden - (Not valid anymore as we don't include history item)
- [x] Responsive Bookmarks - Settings ribbon needs to be hidden - (Fixed by using sidepanel's one)
- [x] Clicking a Sidebar item should bring focus to the existing tab if the sidebar item is already open.

## P2
- [x] “Added to sidebar” tooltip should be limited to 3 times; not forever. (https://github.com/brave/brave-browser/issues/16018)
- [x]  https://github.com/brave/brave-browser/issues/21655
- [x] https://github.com/brave/brave-browser/issues/21597
- [x] https://github.com/brave/brave-browser/issues/21060
- [x] https://github.com/brave/brave-browser/issues/21590

## P3
- [ ] Resizable sidebar panel
- [ ] Sidebar item missing selected state when open in the current tab (Need more discussion for this item)
- [ ] Clicks and hold on the sidebar item should show options (https://github.com/brave/brave-browser/issues/16017)
- [ ] Sidebar options menu should use Brave menu component (applies to all sidebar icon menus and show sidebar menu)
- [ ] Show sidebar on top of webview rather than resizing the webview (#16059)
- [ ] Add to sidebar by dragging the site information (lock) icon in the URL bar into the sidebar
- [ ] Add to sidebar by dragging the tab into the sidebar
- [ ] Drag a sidebar icon off to remove it
- [ ] Need focus states
- [ ] Incorrect typography treatments on “Add to Sidebar” menu

## BUG
- [x] Incorrect sidebar mouse event detect area with On click option (https://github.com/brave/brave-browser/issues/15745)
- [x] Sidebar event dectect area is visible in full screen (https://github.com/brave/brave-browser/issues/16157)
- [x] Sidebar UI should be hidden only when tab-initiated full screen (https://github.com/brave/brave-browser/issues/16160)

**Comment by bsclifton** [comment]
Some other concerns which came up:
- No URL is shown for content loaded in sidebar. This could be a problem as there's no way to ensure which site you're on
- Trying to use functionality which requires microphone/camera (ex: Brave Together) will ask for permission... but this ends up being hidden because there is no visible omnibox for the sidebar (where you'd typically see the permission requests show up)

**Comment by srirambv** [comment]
#14402 should be part of MVP as well (just a suggestion)

**Comment by NumDeP** [comment]
I hope you don't mind me adding just a few more additional features/issues/tests

- Purposely cause a crash and see if it asks to restore and does it actually restore.

- Does it allow to reopen closed tabs, including in private tabs as well (it's going on 2 years soon or is over 2 years since a fix for this has come to horizontal tabs, still waiting for upstream fix)

- Indicate the number of tabs open near "OPEN TABS". Perhaps you could indicate it like "67 OPEN TABS" (This would come in handy if it was implemented before crash test; I've occasionally had restore not work effectively for me)

- Right-click - Bookmark tab to... / Bookmark all tabs to...

- If horizontal tabs is going to be redundant by the use of the sidebar tabs, is there any point to have the empty bar left over from the horizontal tabs. I mean, with the exception of the minimize, maximize and close button which you can push down, is there any point of an empty bar, it's a waste of space right?

**Comment by AshrayaCoder** [comment]
When Might This Drop?
Any Estimations?

**Comment by JeswinSunsi** [comment]
Any updates on this? 👀

**Comment by plandem** [comment]
is it possible to prevent reloading when I switch `apps` on siderbar? right now it fresh reload everytime I switch `app`

**Comment by JeswinSunsi** [comment]
Hey is the sidebar still limited to those 4 tabs?

**Comment by niutech** [comment]
Could you please open the web type items (websites added to the sidebar) in an overlay instead of the current tab, like it is in Opera?

![Opera sidebar](https://user-images.githubusercontent.com/384997/176428362-517639bb-723e-46bf-8083-081e30d21d84.png)

We already have a bookmarks bar for opening websites in the current tab.

**Comment by IMrCreepyI** [comment]
just wondering how far the progress is cause im really looking forward to this

**Comment by JeswinSunsi** [comment]
This isn't a sidebar though. These are bookmark icons on the side. Something like the one in Opera would be very useful to many users. Only reason I haven't switched to OperaGX yet is privacy.

**Comment by simonhong** [comment]
> just wondering how far the progress is cause im really looking forward to this. if its still being worked on

@IMrCreepyI Sidebar feature is already available. It's not shown by default on Stable release.
You can enable it via app menu.
<img width="735" alt="image" src="https://user-images.githubusercontent.com/6786187/177020201-acd49a5e-5276-4ffb-bd25-b3cb1901f2cd.png">

**Comment by IMrCreepyI** [comment]
> > just wondering how far the progress is cause im really looking forward to this. if its still being worked on
> 
> @IMrCreepyI Sidebar feature is already available. It's not shown by default on Stable release. You can enable it via app menu. <img alt="image" width="735" src="https://user-images.githubusercontent.com/6786187/177020201-acd49a5e-5276-4ffb-bd25-b3cb1901f2cd.png">

i have that enabled but i mean like what they have in operaGX and in a message above they show a picture of it

**Comment by bsclifton** [comment]
Closing issue as this is now live 🎉 We can open individual issues for specific items we'd like (that aren't already implemented)
cc: @rebron in case we needed to file items
