### ISSUE TITLE
Test upgrade on the Beta channel

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1536]
When development is complete, we should test the Muon to Brave Core upgrade path officially on the `Beta` channel of `browser-laptop`. This issue is basically the test plan for https://github.com/brave/browser-laptop/pull/15309

An in-depth explanation of how the upgrade happens can be found here:
https://github.com/brave/brave-browser/issues/1863#issuecomment-433555799

There is also a support article (which we link to). Details about that can be found here:
https://github.com/brave/brave-browser/issues/1918

## Pre-testing steps
- [x] Release brave-core with `--upgrade-from-muon` that imports all expected data
- [x] Package final brave-core release channel binaries in browser-laptop
- [x] Build new version of browser-laptop and push to `beta` channel

## Test plan
- [ ] Does upgrading to this new version of Muon install Brave Core? (Windows https://github.com/brave/brave-browser/issues/1540, macOS https://github.com/brave/brave-browser/issues/1541)
- [ ] Does the install of Brave Core happen silently? (Windows https://github.com/brave/brave-browser/issues/1538, macOS https://github.com/brave/brave-browser/issues/1539)
- [ ] Does Muon pass the `--upgrade-from-muon` flag to Brave Core when it launches (verifiable via `brave://version`, under `Command Line:` - https://github.com/brave/brave-browser/issues/1543)
- [ ] Does Muon have a new icon? (https://github.com/brave/brave-browser/issues/1915)
- [ ] If you uninstall Brave Core and relaunch Muon, it should NOT re-install Brave Core (https://github.com/brave/brave-browser/issues/1911)
- [ ] After the upgrade, if user launches Muon, there should be an ugly warning on new tab page and a link to a support article. New tabs will ALWAYS show this (https://github.com/brave/brave-browser/issues/1544)
- [ ] Is sync disabled? You should be able to restore existing groups and (if you have a group) clear the associated data. But you can't create groups. (https://github.com/brave/brave-browser/issues/2303)
### Windows specific
   - [ ] Does stub executable on Windows open Brave Core? ex: if set as default browser, double clicking an HTML file should open Brave Core (https://github.com/brave/brave-browser/issues/1782)
   - [ ] Is there an “old” shortcut which does launch Muon? (in case someone wanted to see their reports, etc - https://github.com/brave/brave-browser/issues/1867)
   - [ ] Do `Add / Remove Programs` and `Default programs` (Windows 10, where you set default handlers) show `Brave (old)` for Muon? (https://github.com/brave/brave-browser/issues/1916)
   - [ ] Uninstalling Muon Brave on Windows should keep the stub executable in place (meaning user doesn’t have to change default browser, if it was Muon - https://github.com/brave/brave-browser/issues/1912)
### Linux specific
- [ ] When user upgrades (via apt, yum/dnf, etc), Brave Core will not install
- [ ] When user upgrades to latest Muon, there are warnings shown in notification bar and on new tab page (https://github.com/brave/brave-browser/issues/1917)

## Import test plan
These can't be tested yet, because the Brave Core components aren't finished (yet)
- [ ] When Muon installs Brave Core and launches, does it import all important data (stats / bookmarks / cookies / passwords / brave payments / etc - https://github.com/brave/brave-browser/issues/872)

## Known use-cases
Here are the known use-cases and how they work:
- User is prompted for update on Muon. They hit “Update” to relaunch Brave OR they close it (Either way, we force-relaunch Muon)
- ***HAPPY PATH***
   - user is on macOS or Windows
   - Brave Core is not installed yet (no profile directory)
   - Brave Core will be installed and executed with `--upgrade-from-muon`
   - Immediately after launching Brave Core, Muon quits (no UI is ever shown to user)
   - `--upgrade-from-muon` flag is detected by brave-core; import takes place
- ***NOT HAPPY PATH***
   - If user is on Linux, nothing happens
   - If installing Brave Core fails, nothing happens
   - If user already has Brave Core installed, nothing happens (no import)
- ***DIFFERENT BUT POSSIBLY HAPPY PATH (NEEDS CONFIRMATION)***
   - If the user uninstalled Brave Core at some point (ex: they have a profile directory) and then upgrades Muon
- ***EDGE CASE***
   - If user goes through the upgrade process and then decides to delete Brave Core, Muon will not attempt to re-install it

**Comment by bsclifton** [comment]
Should we update the users to RELEASE channel (on `brave-core`)? or BETA? Would be good to respect their channel preference and keep them on BETA if possible

**Comment by bsclifton** [comment]
Just finished testing this with the current code for Windows on `NIGHTLY` channel
- Update found - it was downloaded 😄👍 
- Update finished downloading... and then it did the silent install for Brave Core and launched into it? 🙀 (so now, Muon is open saying "Do you want to restart?" and there is a Brave Core window which is now on top of the Muon window)
- Clicking "Restart" on the notification bar in Muon quits and relaunches Muon? 🙀 
- Squirrel executable works as expected: 😄👍
   - default browser being Muon launches Brave Core
   - shortcuts to Muon launch Brave Core

**Comment by petemill** [comment]
Tested:
- Installed 0.25.201
- Ran 0.25.201
	- Prompted for update
    - Prompted for app restart (still only muon showing)
    - Click Restart
       - Muon launches
       - Brave Core launches
          - Quit both
          - Open "Brave Nightly"
              - Brave Core launches

**Comment by bsclifton** [comment]
Tested on macOS last nite:
- update found; it gets downloaded 👍
- I clicked the `Do you want to restart?` and it quit as expected 👍  
- relaunch happened, no UI is shown. It installs brave-core fairly quickly (since it has the entire installer, not just the stub installer) 👍 
- after it does the silent install of brave-core, it launches directly into brave-core 👍

**Comment by bsclifton** [comment]
OK here we go - update pushed to BETA channel
1. Dowload latest Muon BETA if you haven’t already https://github.com/brave/browser-laptop/releases/tag/v0.23.204beta
2. You should be prompted for upgrade (which will be version 0.25.217)

**Comment by bsclifton** [comment]
Looks good! Merged https://github.com/brave/browser-laptop/pull/15309 and we'll be going live here soon
