### ISSUE TITLE
Implement Brave VPN on Desktop

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#15804]
# Test plan (and issues)
Test cases capture the issues that they fix in each section

## Related resources
- **Figma** https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN
- **Security review** https://github.com/brave/security/issues/772 (has link to spec)

## Steps to enable the VPN functionality (do on fresh profile before testing)
- [x] [Allow for VPN on Beta](https://github.com/brave/brave-browser/issues/21598)

**This is a pre-requisite step; this has to be done before any tests are attempted**. 
- VPN is only implemented for Windows and macOS ([Linux captured in a VPN part 2 issue here](https://github.com/brave/brave-browser/issues/21123)).
- As of this writing, VPN is still **behind a feature flag** and is only enabled on **BETA** and **NIGHTLY**.

1. Fresh profile (or not; depending on the test case)
2. Set `brave://flags/#skus-sdk` to ENABLED
3. Set `brave://flags/#brave-vpn` to ENABLED
4. Set `brave://flags/#skus-environment` to DEVELOPMENT
5. Close the browser and re-open it
6. Verify VPN is enabled (look for VPN button next to hamburger menu)

## VPN button and entry in hamburger menu
- [x] [Add stub brave vpn button to toolbar](https://github.com/brave/brave-browser/issues/17235)
- [x] [Add Brave VPN to hamburger menu](https://github.com/brave/brave-browser/issues/17244)
- [x] [Add vpn button toggle option in settings](https://github.com/brave/brave-browser/issues/17802)
- [x] [VPN should have a right click to hide](https://github.com/brave/brave-browser/issues/21163)
- [x] [Debug crash when changing theme color (due to VPN button)](https://github.com/brave/brave-browser/issues/21190)
- [x] [VPN button text should be theme/contrast-aware](https://github.com/brave/brave-browser/issues/21242)

### Verify the button is visible
1. You should see a `VPN` button (next to hamburger button)
2. You should also [see a `Brave VPN` entry in hamburger menu](https://github.com/brave/brave-browser/issues/17244)

### Context menu behavior
1. If you right click VPN button you should get a context menu
2. Choose `Hide VPN button from toolbar` from the context menu and verify the button is hidden
3. Go into hamburger menu, pick `Brave VPN`, and choose `Show VPN button in toolbar`. Verify button shows again
7. Go into hamburger menu, pick `Brave VPN`, and choose `Hide VPN button in toolbar`. Verify button is hidden
8. Go into hamburger menu, pick `Brave VPN`, and choose `Show VPN button in toolbar`

### Theming behavior
1. Visit brave://settings/manageProfile
2. Change your theme color to orange colors (like the Brave lion!)
3. Verify Brave doesn't crash 😄 
4. Verify that the VPN button adjusts its colors accordingly
5. Change your theme back to the default

## Brave Premium login
- [x] [Stripe session/checkout error trying to purchase VPN with experimental SKU SDK](https://github.com/brave/brave-browser/issues/21314)
- [x] [Detect and store VPN state after sign-in](https://github.com/brave/brave-browser/issues/17254)

### Purchasing VPN with a new account
1. Visit https://account.brave.software (Development) and sign into a new account
2. Purchase VPN (browse plans, do checkout process; use a test credit card `4111 1111 1111 1111` / `12/24` for example)
3. Verify purchase works; you should be returned to account.brave.software
4. VPN should show as purchased (you should NOT see `Complete your purchase to begin using Brave VPN`)
6. Click the `Refresh Brave VPN` button and you should see green text saying `YOU HAVE ACTIVE CREDENTIALS LOADED!`
7. Click `VPN` button (top right by hamburger) and you should see the on/off toggle and your default region

### Login to an existing account which has VPN
1. On a different profile than above (see `Purchasing VPN with a new account`), visit https://account.brave.software (Development) and sign into the same account
2. VPN should show as purchased (you should NOT see `Complete your purchase to begin using Brave VPN`)
3. Click the `Refresh Brave VPN` button and you should see green text saying `YOU HAVE ACTIVE CREDENTIALS LOADED!`
4. Click `VPN` button (top right by hamburger) and you should see the on/off toggle and your default region
5. It could be handy to copy this folder and keep it handy as a "fresh logged in profile" (in tests below)

## OS integration
- [x]  [Notify more detailed VPN connecting status change on Windows](https://github.com/brave/brave-browser/issues/17883)
- [x] [BraveVPNOSConnectionAPI should detect OS's vpn status](https://github.com/brave/brave-browser/issues/17679)

### Toggle VPN in operating system (with Brave open)
1. Have Brave open with VPN button visible
6. Have a working connection (region doesn't matter). Verify you can connect/disconnect in Brave.
9. Keep Brave open and go to your OS's VPN section.
    - On Windows, you can push Windows key and type `VPN settings` to get there
    - macOS shows under `Settings` > `Networking`
10. Find the `BraveVPN` connection
11. Manually connect to the VPN using the OS interface
12. Verify that Brave's VPN button lights up Green when connected
13. Verify that Brave's VPN button shows as gray when not connected

### Toggle VPN in operating system (with Brave closed)
1. Have Brave open with VPN button visible
2. Have a working connection (region doesn't matter). Verify you can connect/disconnect in Brave.
3. Close Brave
4. Go to your OS's VPN section.
    - On Windows, you can push Windows key and type `VPN settings` to get there
    - macOS shows under `Settings` > `Networking`
5. Find the `BraveVPN` connection
7. Manually connect to the VPN using the OS interface
8. In a different browser (Edge, Safari, Chrome) visit https://whatismyipaddress.com/
14. Verify that you're in the appropriate region (where you connected manually in step 2)

## Visible user interface
- [x] [VPN panel (logged into Brave Premium)](https://github.com/brave/brave-browser/issues/17246)
- [x] [VPN panel (not logged into Brave Premium)](https://github.com/brave/brave-browser/issues/17249)
- [x] [VPN panel (login expires)](https://github.com/brave/brave-browser/issues/17253)
- [x] [VPN Panel - create a basic server selection UI w/o service logic](https://github.com/brave/brave-browser/issues/17770)
- [x] [Handle not having permission to write config (macOS)](https://github.com/brave/brave-browser/issues/22109)
- [x] [Determine default vpn region based on user's timezone or country code](https://github.com/brave/brave-browser/issues/18078)
- [ ] [[Desktop VPN] Add region flag icons to vpn region list](https://github.com/brave/brave-browser/issues/18623)
- [x] [Add sending email form for VPN Support](https://github.com/brave/brave-browser/issues/18469)

### Notes before testing
Please refer to the Figma as you test:
https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN

This should be accurate and captures expected look and feel for both light and dark mode (we'll want to test both).

### Purchase entry points
This would be on a fresh profile after enabling the VPN feature
1. Click the VPN button (top right, next to hamburger button)
2. Panel will show up and have the sales information (Buy / Already purchased?).
3. Interact (verify links go to the right place, etc)
4. Click the VPN button again to hide the panel
5. Click `Brave VPN` in the hamburger menu
6. Verify the sale panel shows up

#### Default region selection
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Click the VPN button (top right, next to hamburger button)
3. You should see a default region picked which is nearest to your location (based on time zone)
4. Set your OS time to be in another region (like Japan)
5. Create another fresh profile and get setup with VPN
6. Click VPN button
7. Verify it shows region close to where you picked (ex: Japan)

#### Verify connecting works and connected/unconnected state shows properly
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Click the VPN button (top right, next to hamburger button)
3. Enable VPN
4. Verify that Brave's VPN button lights up Green when connected
5. Visit https://whatismyipaddress.com/
6. The website should show you as being in the VPN region now 🎉 
8. Check hamburger menu > `Brave VPN` and ensure toggle there shows as connected
9. Click the toggle (disconnect) in hamburger menu > `Brave VPN`
10. Verify that Brave's VPN button shows as gray when not connected
11. Visit https://whatismyipaddress.com/
12. You should be back in your regular region now

#### Verify you can change regions
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Click the VPN button (top right, next to hamburger button)
3. You should see the default region with a `>` arrow. Click that to show regions
4. Region list should show. The choices listed are coming from Guardian VPN.
5. Choose a different region and connect
6. Verify you can connect; confirm you're in that region using https://whatismyipaddress.com/
7. Disconnect from VPN
8. Choose a different region and connect
9. Verify connect works; confirm you're in that region using https://whatismyipaddress.com/
10. Without disconnecting, choose a different region and connect
11. Verify that VPN disconnects and reconnects; confirm you're in that region using https://whatismyipaddress.com/

#### Setttings
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Click the VPN button (top right, next to hamburger button)
3. Click the gear button to go into Settings
4. Verify navigation works (ex: you can go back; clicking `Contact technical support` opens a new screen; you can go back from that)

#### Creating a support ticket
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Click the VPN button (top right, next to hamburger button)
3. Click the gear button to go into Settings
4. Click `Contact technical support`
5. Fill out the support form. Feel free to try to break it 😄 Provide an email you have access to read
6. Submit form when ready
7. Check with a Guardian team member to confirm if ticket was received

#### Can't connect to server UI
1. Complete the steps under `Brave Premium login` > `Login to an existing account which has VPN`
2. Unplug your network cable (or disable WiFi)
3. Click the VPN button (top right, next to hamburger button)
4. Click the toggle to enable
5. You should see the error about not being able to connect
6. Plug network cable back in OR enable WiFi (disabled in step 2)
7. Click the `Try again` button
8. It should work now

### Preferences
1. Visit brave://settings/appearance
2. Verify there is a setting `Show VPN button`
3. Test it out; toggling should show and hide the button next to hamburger menu

# Original issue description 
Overall goal is to implement a VPN manager within Brave that can create connection, connect, disconnect, and remove a connection. The connection will show in the OS's VPN area for OSes that support that

- [x] Backend integration (TBD - authenticating purchase, etc)
- [x] Windows https://github.com/brave/brave-browser/issues/15805
- [x] macOS https://github.com/brave/brave-browser/issues/15810

History (pathfinding, proof of concept info, etc) available in the employee only issue:
https://github.com/brave/internal/issues/729

Android is currently a WIP which is tracked with https://github.com/brave/brave-browser/issues/12197 and https://github.com/brave/brave-browser/issues/14048 - development done by @deeppandya 

iOS is already live; please see https://github.com/brave/brave-ios/issues/2739 along with https://github.com/brave/brave-ios/pulls?q=is%3Apr+VPN+is%3Aclosed+sort%3Aupdated-desc

## Subtasks not covered in test plan
- [x] [Makes VPN Service fetch/cache region list](https://github.com/brave/brave-browser/issues/17985)
- [x] [Add state machine to vpn service](https://github.com/brave/brave-browser/issues/18422)
- [x] [Load VPN urls from app menu](https://github.com/brave/brave-browser/issues/18573)
- [x] [Pass vpn urls to webui via mojo](https://github.com/brave/brave-browser/issues/18548)
- [x] [Add purchased state in brave_vpn.mojom and manage it in service](https://github.com/brave/brave-browser/issues/18329)
- [x] [Fetch hostnames for selected vpn region and cache it in service](https://github.com/brave/brave-browser/issues/18330)
- [x] [Store fetched region list/device region in prefs and update it periodically in background](https://github.com/brave/brave-browser/issues/18397)
- [x] [Wiring up BraveVPNService with BraveVPNOSConnectionAPI](https://github.com/brave/brave-browser/issues/17658)
- [x] [Create vpn panel handler for webui to call and interface it with mojom](https://github.com/brave/brave-browser/issues/17677)
- [x] [Add mojo observer to vpn desktop service](https://github.com/brave/brave-browser/issues/17810)
- [x] [Get all regions in desktop vpn service and expose to mojom](https://github.com/brave/brave-browser/issues/17899)
- [x] [Get region list from the desktop service to webui ](https://github.com/brave/brave-browser/issues/18055)
- [x] [Add vpn lifecycle events to webui](https://github.com/brave/brave-browser/issues/17885)
- [x] [Add gradient animation](https://github.com/brave/brave-browser/issues/18263)
- [x] [Add "not allowed state" to connection state](https://github.com/brave/brave-browser/issues/22061)
- [ ] [VPN Panel WebUI should be chrome-untrusted](https://github.com/brave/brave-browser/issues/22111)

**Comment by simonhong** [comment]
@rebron Question about VPN state in multi profile situation.
Should browser's vpn status(ex, vpn button state) should be per-profile or should be local state?

If user buy VPN with default profile, browser can get credentials within this profile.
However, user can't get credentials from another new profile before user login to our premium page again.

If we want to make VPN state globally, credentials should be shared across the profiles
Or should we make user login again in new profiles?

**Comment by rebron** [comment]
Should be per profile and not global.

**Comment by starboyvarun** [comment]
@bsclifton It would look more attractive if we add a VPN button beside the extension button. It will be easy to access plus more people can use it easily.i.e noncoders. etc
And we can also give premium Vpn to Users with rewards. This way users can view more ads and can create revenue indirectly.
Thanks!

**Comment by bsclifton** [comment]
@starboyvarun here's where it shows now:
![image](https://user-images.githubusercontent.com/4733304/132547835-5141552c-9905-443b-bf8e-f9d46d14730a.png)

When clicked, a UI will popup where you can interact with:
![image](https://user-images.githubusercontent.com/4733304/132547950-0afc6f48-4853-48e7-b049-93efc94e5166.png)

Good call on the VPN w/ Rewards. We're exploring that for sure - after we get this main use-case working, we intend to look at this 😄

**Comment by starboyvarun** [comment]
@bsclifton  yea, it's in a perfect position.
Thanks for taking the suggestions.

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

<summary>Shared Setup Steps</summary>
<details>

Follow steps from `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`

</details>

<summary>UI</summary>
<details>

* theme awareness
* dark/light support

</details>

<summary>Brave Premium login</summary>
<details>

* Purchasing VPN with a new account
* Log in to an existing account which has VPN

</details>

<summary>VPN button and entry in hamburger menu</summary>
<details>
* context-menu items

</details>

<summary>Post-purchase UX</summary>
<details>
* default region selection
* connecting/disconnecting
* changing regions

</details>

<summary>OS integration/connectivity</summary>
<details>

* Toggle VPN in operating system (Brave open)
* Toggle VPN in operating system (Brave closed)

</details>

<summary>Settings</summary>
<details>

* visit `brave://settings/appearance`
* toggle `Show VPN button`

</details>

<summary>Creating a support ticket</summary>
<details>

TBD

</details>


<summary>Edge cases and error states</summary>
<details>

* can't connect to server UI

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (arm64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by MadhaviSeelam** [comment]
Verification `In-Progess` using
