### ISSUE TITLE
Implement Rewards UI 2.0 for Rewards

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15969]
Android version of: https://github.com/brave/brave-browser/issues/14602

**Comment by Miyayes** [comment]
@deeppandya Broke it into subtasks: 

## Subtasks

- [ ] Rewards settings page, make native
- [ ] Rewards dropdown panel UI/UX refresh
- [ ] Tipping panel refresh

**Comment by Miyayes** [comment]
This is the super-issue that will be closed/resolved when 3/3 subtasks are complete. Just for organizational purposes. If not necessary, please close and use individual subtask issues.
