### ISSUE TITLE
[Meta] certain cookie settings maybe disabled or conflict in the UX when shield settings are set 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#16127]
## Description 
Meta issue for several UX issues with cookie settings as it relates to Shield settings and other exceptions from social media blocking. Root cause may be how we add cookie exceptions from shields.

brave://settings/cookies

- [ ] Unexpected cookie exceptions #11772 
- [ ] Cannot delete sites from "Sites that can always use cookies" #12375 
- [ ] Allowed cookies cannot be deleted #11259
- [ ] Delete icon in cookie settings does nothing #8604
- [ ] Unable to delete cookie for gmail via Clear On Exit #9085
- [ ] Can't remove the url 'https://accounts.google.com' from brave://settings/content/cookies page #8842

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by Michael82548** [comment]
I can't remove these either. The BG is white because the current BETA version of Brave (1.27.69) (1.27.75) does not render the dark theme in any brave:// pages properly when the dark theme in "Brave colors" is selected.

I can temporarily set it to dark by switching to light and then dark again but the page goes back to light after a refresh. The tabs and UI stay dark though...
![image](https://user-images.githubusercontent.com/53535277/123011864-37824380-d38f-11eb-8b4d-5e79208ebfd2.png)

**Comment by bridiver** [comment]
https://github.com/brave/brave-browser/issues/20858

**Comment by 78Star** [comment]
A temporary solution is to reinstall Brave completely. Extreme but I just verified it works.

**Comment by Gianluca-Schileo** [comment]
I think you can remove them by going to the site and re-enabling shields, it worked for me. Hopefully this can prevent you needing to reinstall brave.

**Comment by RazgrizSurget** [comment]
Having this issue. Fresh install on latest version.

**Comment by RazgrizSurget** [comment]
> A temporary solution is to reinstall Brave completely. Extreme but I just verified it works.

Didn't work for me
