### ISSUE TITLE
Add deep links for Rewards settings page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#16628]
## Description

Currently, we can only link to the Rewards settings page at the top level (brave://rewards). Specific areas or panels, such as the settings section of the Ads component, cannot be directly linked to with a link such as `brave://rewards/ads-settings`. 

![image](https://user-images.githubusercontent.com/11497541/123500858-f1d3ae00-d60e-11eb-9ca7-91adf29656a6.png)

## Solution

Add deep links for the following areas (can narrow scope for faster iterations if needed):

```[tasklist]
### Tasks

- [ ] Brave Private Ads settings
- [ ] Auto-contribute settings
- [ ] Contributions settings
- [ ] Monthly statements / Brave Rewards wallet activity top-level modal
- [ ] Reset modal (gear button)
- [ ] 30-day ads history modal
- [ ] Brave Private Ads section
- [ ] Auto-Contribute section
- [ ] Contributions section
- [ ] Monthly contributions section

``

cc: @BrendanEich

**Comment by mkarolin** [comment]
**QA**
Links to test:

<table>
<tr><th>Section</th><th>Link</th></tr>
<tr><td>Brave Private Ads settings</td><td>brave://rewards?settings#ads</td></tr>
<tr><td>Auto-contribute settings</td><td>brave://rewards?settings#auto-contribute</td></tr>
<tr><td>Contributions settings</td><td>brave://rewards?settings#contributions</td></tr>
<tr><td>Monthly statements / Brave Rewards wallet activity top-level modal</td><td>brave://rewards#monthly-statements</td></tr>
<tr><td>Reset modal (gear button)</td><td>brave://rewards#reset</td></tr>
<tr><td>30-day ads history modal</td><td>brave://rewards#ads-history</td></tr>
<tr><td>Brave Private Ads section</td><td>brave://rewards#ads</td></tr>
<tr><td>Auto-Contribute section</td><td>brave://rewards#auto-contribute</td></tr>
<tr><td>Contributions section</td><td>brave://rewards#contributions</td></tr>
<tr><td>Monthly contributions section</td><td>brave://rewards#monthly-contributions</td></tr>
</table>

**Comment by GeetaSarvadnya** [comment]
@mkarolin I don't see the changes https://github.com/brave/brave-browser/issues/16628#issuecomment-1555310199 in Beta `1.53.74` or Nightly build `1.54.16`

**Comment by mkarolin** [comment]
It's working for me with `1.53.71`, which claims to be the latest version available.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (x86_64)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision	1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS	Linux
```

<details>
<summary>Rewards not enabled - 10 InProgress</summary>

<details>
<summary>Case 1: brave://rewards?settings#ads - InProgress</summary>

1. Clena profile 1.53.x
2. Don't enable Rewards
3. Open a new tab and paste the URL `brave://rewards?settings#ads` and hit enter
4. Confirmed that brave://rewards is opened in a new tab displaying pre-enrollment state


</details>

<details>
<summary>Case 2: brave://rewards?settings#auto-contribute - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards?settings#auto-contribute` and hit enter
3. Confirmed that the `Auto-contribute` settings section NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards?settings#auto-contribute` is still shown in the URL bar


</details>

<details>
<summary>Case 3: brave://rewards?settings#contributions - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards?settings#contributions` and hit enter
3. Confirmed that the `Contribution` settings section NOT opened as it doesn't exist in a pre-enrollment state
4. Confirmed that `brave://rewards?settings#contributions` is still shown in the URL bar


</details>

<details>
<summary>Case 4: brave://rewards#monthly-statements - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#monthly-statements` and hit enter
3. Confirmed that the `Monthly Statement` modal popup is NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#monthly-statements` is still shown in the URL bar


</details>

<details>
<summary>Case 5: brave://rewards#reset - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#reset` and hit enter
3. Confirmed that brave://rewards is opened in a new tab displaying pre-enrollment state


</details>

<details>
<summary>Case 6: brave://rewards#ads-history - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#ads-history` and hit enter
3. Confirmed that the `Monthly Statement` modal popup is NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#ads-history` is still shown in the URL bar


</details>

<details>
<summary>Case 7: brave://rewards#ads - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#ads` and hit enter
3. Confirmed that the `Monthly Statement` modal popup is NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#ads` is still shown in the URL bar


</details>

<details>
<summary>Case 8: brave://rewards#auto-contribute - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#auto-contribute` and hit enter
3. Confirmed that the `Auto-contribute` section NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#auto-contribute` is still shown in the URL bar


</details>

<details>
<summary>Case 9: brave://rewards#contributions - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#contributions` and hit enter
3. Confirmed that the `Contributions` section NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#contributions` is still shown in the URL bar


</details>

<details>
<summary>Case 10: brave://rewards#monthly-contributions - TBD</summary>

1. Continuation of case 1
2. Open a new tab and paste the URL `brave://rewards#monthly-contributions` and hit enter
3. Confirmed that the `Monthly Contributions` section NOT opened as it doesn't exist in pre-enrollment state
4. Confirmed that `brave://rewards#monthly-contributions` is still shown in the URL bar


</details>

</details>
