### ISSUE TITLE
Tracking: Private windows & Tor windows - text, menu, and keyboard shortcut issues

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#1671]
- [x] https://github.com/brave/brave-browser/issues/1627 macOS Menu Bar: Tor items missing, 'New Window' has inconsistent behavior when Tor window is active.

- [x] macOS "New private window with Tor" and similar Tor messages should be appropriately title-cased. Fixed with https://github.com/brave/brave-core/pull/683

- [x] https://github.com/brave/brave-browser/issues/1688 New Tab Page: Explanatory text in Private Window does not show the correct Mac keyboard shortcuts. 
  - Incorrect: "Open a Private Window with Tor from the menu, or with Alt+Shift+N or Option+Shift+N."
  - Correct: "Open a Private Window with Tor from the menu, or with Alt+Shift+N (Windows) or ⌥⌘N (Mac)" (That is standard notation for option-command-N)

- [x] https://github.com/brave/brave-browser/issues/738 "incognito" references should be renamed to "private"

**Comment by petemill** [comment]
I'll take some of these items as doesn't look like there's an open PR for any

**Comment by bbondy** [comment]
I think this partially overlaps with https://github.com/brave/brave-browser/issues/738

**Comment by petemill** [comment]
https://github.com/brave/brave-core/pull/683 fixes the strings from #738 and corrects the title-casing.

https://github.com/brave/brave-core/pull/684 fixes the keys displayed on the Private NTP, and also only shows macOS keys on macOS and non-macOS keys on Win / Linux:
![image](https://user-images.githubusercontent.com/741836/47133482-c7c26f00-d25d-11e8-93f1-012928fac44b.png)

Still forthcoming is macOS menu bar item.

**Comment by tomlowenthal** [comment]
Ooh, looks like we have a "Private Tabs" string in here rather than "Private Windows". :/

**Comment by petemill** [comment]
Updated the description on this issue to show status and sub-issues @tomlowenthal @rebron

**Comment by rebron** [comment]
Closing this meta issue. Individual issues resolved for 1.0.x or earlier.
