### ISSUE TITLE
IPFS improvements and fixes for 1.27.x

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#17112]
## Description 

List of IPFS improvements and fixes for 1.27.x

- [x] Allow users to add IPFS peer servers #15567 
- [x] Added option to resolve ENS via Ethereum #15751
- [x] Fix to show ipfs:// when Unstoppable Domains is set to resolve via Ethereum #15750
- [x] Fix to not show `Open using IPFS` button for built-in ipfs-webui #15718

## Brave version (brave://version info)

1.27.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a
