### ISSUE TITLE
[ads] Add additional content to brave://ads-internals

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17393]
- [ ] Condition matchers tab
- [ ] Rewards tab
- [ ] Ad formats tab
- [ ] Permission Rules tab
- [ ] Storage tab
- [ ] User attention tab
- [ ] Resources tab
- [ ] Campaigns tab
- [ ] Dayparts tab
- [ ] Segments tab
- [ ] Confirmation queue tab
- [ ] Transactions tab
- [ ] Payment tokens tab
- [ ] Reactions tab
- [ ] Conversions tab
- [ ] Events tab
- [ ] Logs tab
- [ ] Diagnostics tab

**Comment by ShivanKaul** [comment]
@tmancey we discussed this in the privacy confab and it sounds fine, but just a reminder that for new features/things that expose user info it's best to go through a security/privacy review.

**Comment by tmancey** [comment]
Assess which of the above are still relevant, and would be useful, before implementation.

**Comment by tmancey** [comment]
Closing issue as will be handled by https://github.com/brave/brave-browser/issues/58803 where a privacy review will be opened.
