### ISSUE TITLE
Shields v2 UI Refresh 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18630]
## Description 

Update to new designs and refactor Shields to use mojom api

## Subtasks

- [x] https://github.com/brave/brave-browser/issues/18626
- [x] https://github.com/brave/brave-browser/issues/18627
- [x] https://github.com/brave/brave-browser/issues/16654

## Miscellaneous Information:

Figma link: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=689%3A24419

## Launch Plan
- Keep v2 flag (which shows the shields UI refresh button and panel), and default it to ENABLED
- Introduce v1 flag (which shows the current shields UI button and panel), and default it to DISABLED

This allows:
- Shields UI refresh to ride the trains
- QA to enable v1 to compare counts are identical
- Revert the feature for release via griffin

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.38.75 Chromium: 100.0.4896.60 (Official Build) beta (64-bit)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)

Prerequisites:
- Enable Brave Shields v2
    - Select Enabled option in brave://flags/#brave-shields-v2 
- Disable Brave Shields v1
    - Select Disabled option in brave://flags/#brave-shieds-v1

- Install 1.38.83
- Launch Brave

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using

Brave | 1.38.93 Chromium: 100.0.4896.88 (Official Build) beta (x86_64)
--|--
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 12.4 (Build 21F5048e)

**Comment by s-palianskas** [comment]
After this update the ability to allow individual scripts via Shield is gone. Is this supposed to happen?

**Comment by stephendonner** [comment]
> After this update the ability to allow individual scripts via Shield is gone. Is this supposed to happen?

Yes, the ability to `Run scripts once` was intentionally removed.  cc @rebron for more context

**Comment by anoraknophobia** [comment]
> 

Worst decision ever made on Brave so far in my eyes. 
V2 UI is 2 steps in the wrong direction. 
Allow once option is an essential part for me.

**Comment by palianskas** [comment]
Good thing, that it is possible to revert back to v1 without version rollback - disable `brave://flags/` has options for disabling v2 and enabling v1 if you search for _shields_

**Comment by BobT36** [comment]
@palianskas  thanks for this. This change is indeed retrograde in my eyes. 
Can't see why Run Once would be removed, why remove an OPTIONAL function? 
Also can't see why there's no ability to force the "Advanced Controls" section open by default. This just leads to people naturally Downing ALL shields, rather than JUST scripts, but still keeping the other elements on, etc. 

Why would you want that?

**Comment by BobT36** [comment]
Why doesn't the new panel remember the advanced open / closed setting? 
This is STUPID by defaulting it to basic all the time, this is not only an extra click EVERY TIME, but also encourages people to drop ALL shields rather than just specific ones due to not knowing about the specific options, or simple inconvenience. What's the point? 
Shields were a major selling point of this browser.

**Comment by stephendonner** [comment]
> Why doesn't the new panel remember the advanced open / closed setting? This is STUPID by defaulting it to basic all the time, this is not only an extra click EVERY TIME, but also encourages people to drop ALL shields rather than just specific ones due to not knowing about the specific options, or simple inconvenience. What's the point? Shields were a major selling point of this browser.

@BobT36 Hi; it will remember its previous state starting with the `1.43.x` Brave release, which should ship on or ~ August 30th.

**Comment by BobT36** [comment]
Great, at least that makes it slightly less cumbersome then. Cheers. 

Hopefully the Shields panel can get the same amount of dev effort put in as previously, considering it's one of the major selling points of the brave browser.
