### ISSUE TITLE
Pending verification's from 1.31.x Release #1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#18925]
Following issues from <code>[1.31.x Release](https://github.com/brave/brave-browser/milestone/229)</code> needs to be verified on Android as part of [`1.31.x Release #2`](https://github.com/brave/brave-browser/milestone/244)

- [ ] Remove change location and just keep Location to switch regions (#18424)
- [ ] Add support for server/geo selection (#13986)
- [ ] Add VPN Enabled Notification (#13985)
- [ ] VPN install problems UX improvements (#13981)
