### ISSUE TITLE
Pending wallet verification's/Release Notes from 1.32.x - Release #2

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#19722]
Current list of issues that have been `fixed/resolved` in `1.32.x Release #2` but haven't been verified by QA and should be completed for `1.33.x Release #3`

- [ ] Should ignore casing when compare account address in ShouldCreate1559Tx (#19673)
- [ ] zapper.fi switch network is not working (#19656)
- [ ] Add a menu item on the panel for viewing account on Etherscan (#19655)
- [ ] Unable to approve cancel transactions (#19642)
- [ ] revvracing.com (dapp on Polygon) shows a blank black screen when using Brave native Wallet (#19624)
- [ ] eth_sendTransaction should check keyring support when deciding to create EIP1559 or legacy tx (#19617)
- [ ] Fix patches changes for Chromium 96.0.4664.45 (#19611)
- [ ] Brave Wallet Cannot Connect to Hex (#19551)
- [ ] Swapping via Quickswap (Polygon/MATIC) chain shows insufficient funds (#19536)
- [ ] wallet_addEthereumChain should ask users to switch chain after the network is successfully added  (#19291)
- [ ] Implement eth_signTypedData and in particular eth_signTypedData_v4 version of EIP-712 (#18659)

Current list of issues that were `release-notes/include` via `1.32.x Release #2` and should be added into the release notes for `1.33.x Release #3`

- zapper.fi switch network is not working (#19656)
- Add a menu item on the panel for viewing account on Etherscan (#19655)
- Unable to approve cancel transactions (#19642)
- revvracing.com (dapp on Polygon) shows a blank black screen when using Brave native Wallet (#19624)
- Fix crash when permission requests for Ethereum are from a popup window (#19566)
- Brave Wallet Cannot Connect to Hex (#19551)
- Swapping via Quickswap (Polygon/MATIC) chain shows insufficient funds (#19536)

**Comment by srirambv** [comment]
Issues listed are all verified. 
* [#19611](#19611) - Will be checked as part of Android wallet verification
* [#18659](#18659) - will be tested as part of 1.33.x as the fix was reverted and is now assigned to 1.33.x milestone
