### ISSUE TITLE
Implement Sync v2

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2123]
original comment from @bsclifton: https://github.com/brave/brave-browser/issues/356#issuecomment-397959670

`browser-laptop` implementation of the Sync v2 UI available here:
https://github.com/brave/browser-laptop/pull/13197

Important issues to consider when implementing (we can create separate issues for these):
- [ ] sync v2: Add first-use wizard dialogs https://github.com/brave/browser-laptop/issues/12269
- [ ] after sync reset, devices are not visible anymore if you try to re-sync https://github.com/brave/browser-laptop/issues/13258
- [ ] sync v2: finish total sync-chain removal feature https://github.com/brave/browser-laptop/issues/12364
- [ ] sync should clear clipboard data after 30s https://github.com/brave/browser-laptop/issues/13359
- [ ] Remove sync devices feature - Sync'd device manager https://github.com/brave/browser-laptop/issues/9254

**Comment by bsclifton** [comment]
Adding `P1` label as iOS and Android already use the v2 UI spec

**Comment by kjozwiak** [comment]
@cezaraugusto @bsclifton marked this as `QA/No` as there's nothing specific here other than making sure syncing works. Please let me know if you feel differently!
