### ISSUE TITLE
Comprehsive list of sites where ads bypass Shields

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2124]
## Description 

I was tired of digging around for individual adblock issues that only relate to one specific website/domain. So I decided to open this to track all current (open) and future adblock issues on a per-site basis. Helps keep repos tidy and serves as an easy reference. 

Note: I think its worth reiterating that these are **only issues (logged or not) that pertain to ads bypassing shields - that is, displaying ads that should be blocked**. This does not include any webcompat issues or issues where Shields interfere with site functionality. 

<details>
<summary>
Recorded Issues
</summary>

Site/Domain: Twitch
Issue: [Pre-roll ads on twitch not always blocked](https://github.com/brave/brave-browser/issues/1489)
Screenshot (if available): N/A

**Site/Domain**: Breitbart.com
**Issue**: [Pre-roll ads not blocked on breitbart videos](https://github.com/brave/brave-browser/issues/1318)
**Screenshot (if available)**:
![image](https://user-images.githubusercontent.com/3299098/48442827-2509ed00-e744-11e8-813e-183cd18c7c3a.png)

**Site/Domain**: https://youtube.com
**Issue**: [Ads on YouTube (pre-roll and banner overlays) not blocked when video is embedded](https://github.com/brave/brave-browser/issues/1145)
**Screenshot (if available)**:
![image](https://user-images.githubusercontent.com/3299098/48443005-ac576080-e744-11e8-8a96-fefa290b9f56.png)

**Site/Domain:** Freethoughtproject.com
**Issue**: [Freethoughtproject.com - ads getting beyond shields](https://github.com/brave/brave-browser/issues/1049)
**Screenshot (if available)**:

**Site/Domain**: https://movpod.in/ (likely multiple sites)
**Issue**:  [Adblock doesn't block ads on streaming sites](https://github.com/brave/brave-browser/issues/1043)
**Screenshot (if available)**:
![image](https://user-images.githubusercontent.com/3299098/48448252-41615600-e753-11e8-82b7-b71d90ab8000.png)

</details>

<details>
<summary>
Write-in Issues
</summary>

**Site/Domain:**
https://kissanime.ac (also a webcompat issue - must allow ads to stream but either way, site will show pop-up ads with ads/trackers blocked in Shields)

**Screenshot (if available):**
I was going to include a screenshot but 99% of the pop-ups are "lewd" or otherwise inappropriate for GH.

**Site/Domain:**
https://www.msn.com/en-xl/asia/asia-tech-science/alibaba%E2%80%99s-singles%E2%80%99-day-sets-online-shopping-record-with-dollar31b-in-sales/ar-BBPBJLO?li=BBJE6P9&ocid=mailsignout
**Screenshot (if available):**
![image](https://user-images.githubusercontent.com/3299098/48448684-ab2e2f80-e754-11e8-96d9-b3e621f95496.png)

**Site/Domain:**
https://community.brave.com/c/support-and-troubleshooting/mobile-support

**Screenshot (if available):**
![image](https://user-images.githubusercontent.com/3299098/49037137-5506b680-f16e-11e8-8b6f-15e8879403ea.png)
</details>

<details>
<summary>
Issues/Sites in list form
</summary>

- [ ] https://github.com/brave/brave-browser/issues/1489 - pre-roll ads on twitch not always blocked #1489
- [ ] https://github.com/brave/brave-browser/issues/1318 - pre-roll ads not blocked on breitbart videos #1318
- [ ] https://github.com/brave/brave-browser/issues/1145 - Ads on YouTube (pre-roll and banner overlays) not blocked when video is embedded #1145
- [ ] https://github.com/brave/brave-browser/issues/1049 - Freethoughtproject.com - ads getting beyond shields #1049
- [ ] https://github.com/brave/brave-browser/issues/1043 - Adblock doesn't block ads on streaming sites #1043
- [ ] https://www.msn.com/en-xl/asia/asia-tech-science/alibaba%E2%80%99s-singles%E2%80%99-day-sets-online-shopping-record-with-dollar31b-in-sales/ar-BBPBJLO?li=BBJE6P9&ocid=mailsignout
- [ ] https://kissanime.ac
- [ ] https://www.cartooncrazy.tv/watch/family-guy-season-17-episode-7-the-griffin-winter-games/
</details>

**Comment by bbondy** [comment]
mega issues like this won't work @Brave-Matt because when a fix is submitted, the issue is closed in the milestone and QA tests the closed issues.   I don't think each of the issues listed would be from the same single fix that would be submitted.    So please post separate issues, thanks!
