### ISSUE TITLE
Release checklist for `1.35.x - Release #4`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#21250]
Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### Prerequisites

- [ ] Consult with the security team to ensure that all security issues have been included.
   - [ ] Release using the `critical` feature (forces users to update/restart) if there's a zero day vulnerability being exploited
- [ ] Consult with PR team (@catherinecorre) and provide heads up on release timing, screenshots, other deliverable's.

### Release Notes to Staging

- [ ] Mark closed issues in github as `release-notes/exclude` or `release-notes/include`.
- [ ] Commit release notes to [CHANGELOG_DESKTOP.md](https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md) in brave-browser master branch, must be completed before release to production Jenkins build job is run.
- [ ] Stage release notes to https://github.com/brave/brave-browser/releases/

### Certification and Builds

- [ ] Upload builds to Omaha test channels (`86-r-test`, `64-r-test`, `test`(mac))
- [ ] Log into Fastly, clear CDN cache for: `updates-cdn.bravesoftware.com`, `updates.bravesoftware.com`

### Test Staging for Updates

- [ ] Install a prior version of Brave and update via `test` channels (`86-r-test`, `64-r-test`, `test`(macOS))
   - [ ] Confirm version matches expectations
- [ ] QA summary and sign off report under #release via Slack.

### Release to production download locations

- [ ] Publish github release (remove 'pre-release' checkmark)
- [ ] Upload Mac/Win build to Omaha production channels (`x86-rel`, `x64-rel`, `stable`(mac))
- [ ] Upload Mac `.dmg` and `.pkg` to S3 bucket (i.e. `aws s3 cp ./Brave-Browser-Dev.dmg s3://brave-browser-downloads/latest/Brave-Browser-Dev.dmg --acl public-read`)

### Clear Production Fastly cache

- [ ] Clear Fastly cache for: `brave-browser-downloads.s3.brave.com`, `brave-browser-apt-release.s3.brave.com`, `brave-browser-rpm-release.s3.brave.com`

### Updates Testing on Production

- [ ] Wait for confirmation that macOS live update works

### Download & Install stub binaries from https://brave.com

- [ ] download the `.dmg` binary from https://brave.com on `macOS` - `https://laptop-updates.brave.com/latest/osx`

### Announcements

- [ ] Publish the release notes to `GitHub`
- [ ] Publish the release notes to `https://www.brave.com/latest`
- [ ] Announce release on https://community.brave.com/ (@Hollons)
- [ ] Announce release on https://www.reddit.com/r/brave_browser/ (@Hollons)
- [ ] Notify #announcements of the latest release with a link to the release notes

### Closing milestones

- [ ] Set a release date (if missing) and close the appropriate milestone under https://github.com/brave/brave-browser/milestones
- [ ] Set a release date (if missing) and close the appropriate milestone under https://github.com/brave/brave-core/milestones

### Creating milestones

- [ ] Create milestones under [`b-b`](https://github.com/brave/brave-browser/milestones) & [`b-c`](https://github.com/brave/brave-core/milestones) if needed

**Comment by rebron** [comment]
Closing. Brave Browser Desktop 1.35.104 for macOS released at 2022-02-23 at 8:00am PST.
