### ISSUE TITLE
Upgrade from Chromium 99 to Chromium 100

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#21470]
# Upgrade from Chromium 99 to Chromium 100

https://chromium.googlesource.com/chromium/src/+log/99.0.4844.51..100.0.4896.20/?pretty=fuller&n=10000

## QA Tests

This is a major Chromium version bump, please do full passes.

## Desktop Affected areas

- Tab muting
- Cross-site cookies
- Greaselion service, particularly during shutdown
- Clear data on exit (UI and functionality)
- Popup windows, e.g., Rewards panel, Shields
- Sync
- Component updater
- Private/Tor profiles
- Focus colors, theming, system colors, etc.
- Wallet (correctly showing data, importing external wallet)
- Linux app icons

## Android Affected areas

* Sync (double check that it generally works)
* Top toolbar UI
* Bottom toolbar UI
* Home button behavior

**Comment by Uni-verse** [comment]
QA performed manual test passes which covered the affected areas on Android ARM. 

Test Devices:
`Samsung GS 21 | Android 12`
`Samsung G Tab S7 | Android 11`

C100 Upgrade Test Runs for Android ARM:

https://github.com/brave/brave-browser/issues/21741
https://github.com/brave/brave-browser/issues/21786
https://github.com/brave/brave-browser/issues/21793

**Comment by kjozwiak** [comment]
Above will require `1.37.103` or newer for `1.37.x` verification.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.105 Chromium: 100.0.4896.46 (Official Build) (64-bit)
-- | --
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | Ubuntu 18.04 LTS


* [x] Tab muting - requires `brave://flags#enable-tab-audio-muting` to be enabled
* [x] Cross-site cookies
* [x] Greaselion service, particularly during shutdown
* [x] Clear data on exit (UI and functionality)
* [x] Popup windows, e.g., Rewards panel, Shields
* [x] Sync - was checked under `Sync` via https://github.com/brave/brave-browser/issues/21853
* [x] Component updater - was under `Startup & Components` checked via https://github.com/brave/brave-browser/issues/21853
* [x] Private/Tor profiles - was checked under `under `Tor Tabs` via https://github.com/brave/brave-browser/issues/21853
* [x] Focus colors, theming, system colors, etc.
* [x] Wallet (correctly showing data, importing external wallet)
* [x] Linux app icons

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.37.107`


* Sync (double check that it generally works)
* Top toolbar UI
* Bottom toolbar UI
* Home button behavior

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 12.3 Monterey x64` using the following build(s):

```
Brave | 1.37.107 Chromium: 100.0.4896.46 (Official Build) (x86_64)
--- | ---
Revision | 5ca33821b2211805855c77d334353d27c616a7ca-refs/branch-heads/4896@{#584}
OS | macOS Version 12.3 (Build 21E230)
```

* [x] Tab muting - verified/checked via https://github.com/brave/brave-browser/issues/21829
* [ ] Cross-site cookies
* [ ] Greaselion service, particularly during shutdown
* [ ] Clear data on exit (UI and functionality)
* [ ] Popup windows, e.g., Rewards panel, Shields
* [x] Sync - verified/checked via https://github.com/brave/brave-browser/issues/21850
* [x] Component updater - verified/checked via https://github.com/brave/brave-browser/issues/21850
* [x] Private/Tor profiles - verified/checked via https://github.com/brave/brave-browser/issues/21850
* [x] Focus colors, theming, system colors, etc.
* [x] Wallet (correctly showing data, importing external wallet) - @SergeyZhukovsky is running through `Brave Wallet` verification's using `macOS`. Would have found issues caused by `C100` by now.
