### ISSUE TITLE
Manual test run on Windows x64 for 0.56.x - Release Hotfix 1

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2180]
## Per release specialty tests
 - [x] Cookies not imported - follow up to 1545.([#2013](https://github.com/brave/brave-browser/issues/2013))
 - [x] Stats not imported during auto-upgrade.([#2014](https://github.com/brave/brave-browser/issues/2014))
 - [x] Upgrade from Chromium 70.0.3538.77 to 70.0.3538.102.([#2099](https://github.com/brave/brave-browser/issues/2099))

### Installer

- [x] Check that installer is close to the size of last release
- [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x] Make sure that data from the last version appears in the new version OK
- [x] With data from the last version, verify that
  - [x] bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] cookies are preserved
  - [x] installed extensions are retained and work correctly
  - [x] opened tabs can be reloaded
  - [x] stored passwords are preserved
  - [x] unpinned tabs can be pinned

### About pages

- [x] Verify that `chrome://` forwards to `brave://`
- [x] Verify `brave://adblock` loads adblock page
- [x] Verify `brave://newtab` loads a new tab
- [x] Verify `brave://rewards` loads Brave rewards page 
- [x] Verify `brave://settings` loads Brave settings page 
- [x] Verify `brave://version` correctly shows Brave version and Chromium version 
- [x] Verify `brave://welcome` loads the welcome page 

### Import tests

- [x] Verify that you can import bookmarks, cookies, history, passwords and stats from `muon`
- [x] Verify that you can import bookmarks, cookies, history, passwords from Google Chrome 
- [x] Verify that you can import bookmarks, cookies, history, passwords, autofill and search engines from Firefox
- [x] Verify that you can import bookmarks from Edge
- [x] Verify importing `Bookmark HTML` file retains the folder structure on a clean profile

### Context menus

- [x] Verify `Block element via selector` removes a CSS element from page without reloading
- [x] Verify `Clear all CSS rules for this sites` removes the blocked element after page reload
- [x] Verify `Clear all CSS rules for all sites` removes the rule and loads all elements for all pages

## Extensions/Plugins tests

- [x] Verify one item from Brave Update server is installable (Example: Ad-block DAT file on fresh extension)
- [x] Verify one item from Google Update server is installable (Example: Extensions from CWS)
- [x] Verify PDFJS, Torrent viewer extensions are installed automatically on fresh profile and cannot be disabled
- [ ] Verify older version of an extension gets updated to new version via Google server
- [ ] Verify older version of an extension gets updated to new version via Brave server 
- [x] Verify magnet links and .torrent files loads Torrent viewer page and able to download torrent

### CWS

- [x] Verify installing ABP from CWS shows warning message `NOT A RECOMMENDED BRAVE EXTENSION!`but still allows to install the extension
- [x] Verify installing LastPass from CWS doesn't show any warning message 
- [ ] Verify installing an extension that is not vetted by Brave gets blocked

### Flash tests

- [x] Test that Flash gets blocked by default when installed
- [x] Test that once you allow Flash, it turns into a click to play area, and loads flash when allowed

### PDF

- [x] Test that you can print a PDF
- [x] Test that PDF is loaded over HTTPS at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Test that PDF is loaded over HTTP at http://www.pdf995.com/samples/pdf.pdf

### Widevine

- [x] Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x] Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Geolocation

- [x] Check that https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation shows correct location
- [x] Check that https://browserleaks.com/geo works and shows correct location
- [x] Check that https://html5demos.com/geo/ works but doesn't require an accurate location

### Crash Reporting

- [x] Check that loading `brave://crash` causes the new tab to crash
- [x] Check that `brave://crashes` lists all the crashes and includes both Crash Report ID & Local Crash ID
- [x] Verify the crash ID matches the report on brave stats

### Performance test

_Each start should take less than 7 seconds_
- [x] Enable only rewards
- [x] Only import a large set of bookmarks
- [x] Combine rewards, and a large set of bookmarks

### Bravery settings

- [x] Verify that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Verify that toggling `Ads and trackers blocked` works as expected
- [x] Visit https://testsafebrowsing.appspot.com/s/phishing.html, verify that Safe Browsing (via our Proxy) works for all the listed items
- [x] Visit https://brianbondy.com/ and then turn on script blocking, page should not load. Allow it from the script blocking UI in the URL bar and it should load the page correctly
- [x] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked

### Fingerprint Tests

- [x] Visit https://jsfiddle.net/bkf50r8v/13/, ensure 3 blocked items are listed in shields. Result window should show `got canvas fingerprint 0`  and  `got webgl fingerprint 00`
- [x] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ only when `Block all fingerprinting protection` is on
- [x] Test that Brave browser isn't detected on https://extensions.inrialpes.fr/brave/
- [x] Test that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

### Content tests

- [x] Open a page with an input control and type some misspellings on a textbox, make sure they are underlined
- [x] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text
- [x] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

### Tor Tabs

- [x] Visit https://check.torproject.org in a Tor window, ensure its shows success message for using a Tor exit node
- [ ] Visit https://check.torproject.org in a Tor window, note down exit node IP address. Do a hard refresh (Ctrl+Shift+R/Cmd+Shift+R), ensure exit IP changes after page reloads
- [x] Visit https://check.torproject.org in a Tor window, note down exit node IP address. Click `New Tor Identity for this site` in app menu, ensure the exit node IP address changes after page is reloaded
- [x] Visit https://protonirockerxow.onion/ in a Tor window, ensure login page is shown
- [x] Visit http://pdf995.com in a Tor window, should warn about connecting to HTTP site
- [x] Visit https://browserleaks.com/geo in a Tor window, ensure location isn't shown
- [x] Visit https://diafygi.github.io/webrtc-ips/ in a Tor window with block all fingerprinting, ensure WebRTC is blocked and no IP is shown
- [x] Visit https://diafygi.github.io/webrtc-ips/ in a Tor window, disable shields, ensure WebRTC is blocked and no IP is shown
- [x] Verify Flash doesn't work on Tor window even if it is enabled in `brave://settings/content/flash`
- [ ] Verify Torrent viewer doesn't load in a Tor window and warns when trying to load a torrent/magnet link in a Tor window
- [x] Verify Google Widevine doesn't load in Tor window and doesn't prompt Google Windevine notification in URL bar
- [x] Ensure you are able to download a file in Tor window. Verify all Download/Cancel, Download/Retry and Download works in Tor window
- [ ] Disconnect network and open a Tor window, should show modal to retry connection or relaunch Tor window to connect 

### Cookie and Cache

- [x] Go to http://samy.pl/evercookie/ and set an evercookie. Check that going to prefs, clearing site data and cache, and going back to the evercookie site does not remember the old evercookie value

### Session storage

- [x] Temporarily move away your browser profile and test that a new profile is created when browser is launched 
  - macOS - `~/Library/Application\ Support/BraveSoftware/`
  - Windows - `%userprofile%\appdata\Local\BraveSoftware\` 
  - Linux(Ubuntu) - `~/.config/BraveSoftware/`
- [x] Test that windows and tabs restore when closed, including active tab
  - [x] Ensure that the tabs in the above session are being lazy loaded when the session is restored

## Update tests

- [ ] Verify visiting `brave://settings/help` triggers update check
- [ ] Verify once update is downloaded, prompts to `Relaunch` to install update

#### Adblock

- [x] Verify referrer blocking works properly for TLD+1. Visit `https://technology.slashdot.org/` and verify adblock works properly similar to `https://slashdot.org/`

#### Components
- [x]  Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

### Rewards Media (To be verified on YouTube and Twitch) (WIP)

**Comment by kjozwiak** [comment]
Thanks for all the hard work @GeetaSarvadnya 👍
