### ISSUE TITLE
Implement Brave VPN on Android (Part 2)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#22544]
## Description
Follow up to https://github.com/brave/brave-browser/issues/12197
Please search for the spec "Brave VPN on Android" for details

## Related issues / sub-issues 
- [x] [VPN Alerts and Details](https://github.com/brave/brave-browser/issues/13982)
- [x] [Link VPN stats with Brave Stats on the NTP](https://github.com/brave/brave-browser/issues/13983)
- [x] [Add VPN off "Timer"](https://github.com/brave/brave-browser/issues/13984)
