### ISSUE TITLE
[Meta] shield v2 follow-ups 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#22546]
## Description 

Follow-up issues to address from Shields v2 that landed in 1.39.x
https://github.com/brave/brave-browser/issues/18630

- [x] https://github.com/brave/brave-browser/issues/22422
- [x] https://github.com/brave/brave-browser/issues/22415
- [x] https://github.com/brave/brave-browser/issues/22389
- [x] https://github.com/brave/brave-browser/issues/22364
- [x] https://github.com/brave/brave-browser/issues/22539
- [x] https://github.com/brave/brave-browser/issues/22428
- [ ] https://github.com/brave/brave-browser/issues/22496
- [x] https://github.com/brave/brave-browser/issues/22382

## Brave version (brave://version info)

Targeting for 1.39.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes. 1.38.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by nullhook** [comment]
we won't be resolving ipfs issue in this as the work is more involved and requires approvals from various code owners
