### ISSUE TITLE
[Umbrella] Brave-UI: Split cross-functional publishing

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2335]
Brave-UI contains WebUI implementations across features, not just core components. It also has a single brave-core release branch targets.

## Problem

Whilst we have brave-core specific release branches in brave-ui relating to brave-core this is still a lot of overhead that slows development down. It also creates a dependency timing issue whereby features are merged to master (or other release branch) in brave-ui but need some corresponding change in brave-core. It can get pretty complex, when we can avoid all that thought and time completely with one of the solutions below.

## Aims
- Feature A can have some items in brave-core 58.x branch and other items in brave-core 59.x branch
- Feature B can have some items in brave-core 58.x branch and other items in brave-core 59.x branch, separately to feature A
- Brave-ui can have some items in brave-core 58.x branch and other items in brave-core 59.x branch

Nothing UI-related gets merged to brave-core master / branch before it's corresponding brave-core changes are.

### ~1~
~Keep everything in brave-ui github repo, and publish to multiple npm targets, e.g:~
~@brave/ui~
~@brave/ui-feature-sync~
~@brave/ui-feature-rewards-panel~
~@brave-ui-feature-rewards-settings~
#### ~Questions~
- ~How do we do branching for each feature separately?~
- ~Uplift process for feature A and B?~
_Not really that relevant anymore now that brave-ui features are not published to npm_

### 2
Keep brave-ui as core components, move features in to feature repos. In other words, brave-core related features go in to brave-core repo.
- brave-core/components/web-ui
    - features (for now, but probably folded in to actual components)
- brave-core/components/web-ui
    - stories
- brave-core gets `npm run web-ui-storybook`

## Tracking

- [x] Create brave-core storybook https://github.com/brave/brave-browser/issues/2518
- [x] Move NTP https://github.com/brave/brave-browser/issues/5178
- [x] Move Sync https://github.com/brave/brave-browser/issues/5198
- [x] Move Welcome Page https://github.com/brave/brave-browser/issues/5216
- [x] Move Shields https://github.com/brave/brave-browser/issues/5505
- [x] Move Rewards https://github.com/brave/brave-core/pull/3463
- [ ] ~~Optional: enable hot reloading inside webui in dev environment?!~~

**Comment by petemill** [comment]
What is blocking us put the actual brave-core specific webui in to it?

Primary goals
- _Some_ kind of hot-reloading experience (inside the browser or inside a separate local website)

Secondary goals
- Develop UI without building the browser (even with hot-reloading)
- Some kind of storybook deployment to show other teams UI on a website instead of having to run the internal pages in a browser build

All the goals seem to be solved with just adding a storybook to brave-core. The one disadvantage being that for that to work we would still need a separate layer that mocks / provides the `chrome.*` internal APIs (and any other data / actions). But that is what we do anyway whilst also adding the complexity of it being in a whole separate repo with cross-feature contamination too.

**Comment by petemill** [comment]
Updated description for up to date problem description and aims

**Comment by szaimen** [comment]
Any updates here?

**Comment by cezaraugusto** [comment]
Since https://github.com/brave/brave-browser/issues/5198 is now in master, I'm happy to announce that we hit the goal of moving feature-specific components to brave-core. Closing this.
