### ISSUE TITLE
Playlist UI for desktop

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25829]
<details>
<summary> ios specs </summary>

polish a little bit based on iOS current implementation.

First view
https://www.figma.com/proto/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?page-id=1%3A3984&node-id=936%3A42819&scaling=min-zoom&starting-point-node-id=1619%3A97407&show-proto-sidebar=1

menu button on first view
https://www.figma.com/proto/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?page-id=1%3A3984&node-id=1768%3A137175&scaling=min-zoom&starting-point-node-id=1619%3A97407&show-proto-sidebar=1

playlist detail
https://www.figma.com/proto/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?page-id=1%3A3984&node-id=1223%3A60497&scaling=min-zoom&starting-point-node-id=1619%3A97407&show-proto-sidebar=1

player
https://www.figma.com/proto/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?page-id=1%3A3984&node-id=1229%3A60878&scaling=min-zoom&starting-point-node-id=1619%3A97407&show-proto-sidebar=1
</details>

### Desktop design(WIP)
https://www.figma.com/file/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?type=design&t=DFOlyqRgtAMpvy8K-0
```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/31913
- [ ] https://github.com/brave/brave-browser/issues/31159
- [ ] https://github.com/brave/brave-browser/issues/31133
- [ ] https://github.com/brave/brave-browser/issues/31536
- [ ] https://github.com/brave/brave-browser/issues/31186
- [ ] https://github.com/brave/brave-browser/issues/31418
- [ ] https://github.com/brave/brave-browser/issues/31844
- [ ] https://github.com/brave/brave-browser/issues/32540
- [ ] https://github.com/brave/brave-browser/issues/32568
- [ ] https://github.com/brave/brave-browser/issues/32572
- [x] https://github.com/brave/brave-browser/issues/32834
- [ ] https://github.com/brave/brave-browser/issues/32898
- [ ] https://github.com/brave/brave-browser/issues/32922
- [ ] https://github.com/brave/brave-browser/issues/33561
- [ ] https://github.com/brave/brave-browser/issues/33863
- [ ] https://github.com/brave/brave-browser/issues/33864
- [ ] https://github.com/brave/brave-browser/issues/34614
- [ ] https://github.com/brave/brave-browser/issues/32543
- [ ] Crash occurs when/after removing an ite
- [ ] We can get thumbanils from media controls and fill the empty thumbnails. ( global_media_controls::MediaItemUI:)
- [ ] Should use Default folder's image on MoveDialog
```

**Comment by sangwoo108** [comment]
Close as left items can be done after MVP
