### ISSUE TITLE
[Desktop] Set Brave News 2.0 flag (new customize UX) to enabled

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#25890]
This is a tracking issue for required items before we can set this flag to enabled:
- [x] Update the UI https://github.com/brave/security/issues/1055
- [x] Add support for channels (the replacement for categories) https://github.com/brave/brave-browser/issues/25688
- [x] Fetch news from multiple locales https://github.com/brave/brave-browser/issues/25882
- [x] Do not search for rss feeds immediately when any valid url is input in the search field https://bravesoftware.slack.com/archives/CU56GUJ1H/p1665421363721649
- [x] Support migration from Brave News V1 https://github.com/brave/brave-browser/issues/24550
- [x] Lazy load images https://github.com/brave/brave-browser/issues/26161
- [ ] Convert .ico / .svg files on the aggregator to binary so that they can be included in the pcdn https://github.com/brave/news-aggregator/issues/135
- [ ] ~Load all favicons when showing the dialog https://github.com/brave/security/issues/1055~
- [x] Source suggestions (similarity matrix) https://github.com/brave/brave-core/pull/15447 / https://github.com/brave/brave-browser/issues/25563
- [x] List sources by popularity https://github.com/brave/brave-browser/issues/24324
- [x] Duplicate publishers https://github.com/brave/news-aggregator/issues/136
- [x] Channel images (we have signed-off design now) https://github.com/brave/brave-browser/issues/25988, https://github.com/brave/brave-browser/issues/26115
- [x] Translate channel names https://github.com/brave/brave-browser/issues/26116

Blocked by:
1. https://github.com/brave/brave-browser/issues/26184 (~~this needs to be uplifted to 1.46.x~~ Uplifted)
2. https://github.com/brave/brave-browser/issues/26196 (~~this needs to be uplifted to 1.46.x~~ Uplifted)
3. https://github.com/brave/brave-browser/issues/26197 (this greatly improves first open performance. ~~It should probably be uplifted too~~ Uplifted).

**Comment by petemill** [comment]
Closing as almost everything is complete and the flag was enabled via https://github.com/brave/brave-core/pull/15779
