### ISSUE TITLE
Release checklist for 0.58.x (Release Channel)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2630]
Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### Prerequisites

- [ ] Check https://github.com/brave/webtorrent is up to date with its latest upstream.
- [ ] Check https://github.com/brave/bittorrent-tracker is up to date with its latest upstream.
- [ ] Check https://github.com/brave/torrent-discovery is up to date with its latest upstream.
- [ ] Check Tor is up to date with its latest upstream.
- [x] At freeze date, consult with the security team to ensure that all security issues have been included.
- [x] At freeze date, consult with PR team (@catherinecorre) and provide heads up on release timing, screenshots, other deliverables.

### Release Notes to Staging
- [x] Mark closed issues in github as release-notes/exclude or release-notes/include.
- [x] Stage release notes to https://github.com/brave/brave-browser/releases/
- [x] Stage release notes to brave.com/release/ 

### Certification and Builds
- [x] Upload builds to Omaha test channels (`86-r-test`, `64-r-test`, `test`(mac))
- [x] Log into Fastly, clear CDN cache for: `updates-cdn.bravesoftware.com`, `updates.bravesoftware.com`

### Test Staging for Updates
- [x] Install a prior version of the app from test channels (`86-r-test`, `64-r-test`, `test`(mac))
- [x] Go to "About Brave" page to update
- [x] Confirm version matches expectations
- [x] QA summary and build verification report.

### Release to production download locations
- [x] Publish github release (remove 'pre-release' checkmark)
- [x] Create tag in brave-core branch (i.e. v0.57.18) on commit used in brave-browser build
- [x] Upload Mac/Win build to Omaha production channels (`x86-rel`, `x64-rel`, `stable`(mac))
- [x] Sign Linux builds and upload to S3 repositories
- [x] Upload Mac `.dmg` and `.pkg` to S3 bucket (i.e. `aws s3 cp ./Brave-Browser-Dev.dmg s3://brave-browser-downloads/latest/Brave-Browser-Dev.dmg --acl public-read`)
- [x] Upload Windows stub and silent installer to S3 bucket using similar command to Mac dmg above (i.e `BraveBrowserSetup.exe`, `BraveBrowserSetup32.exe`, `BraveBrowserSilentSetup.exe`, `BraveBrowserSilentSetup32.exe`)

### Clear Production Fastly cache
- [x] Log into Fastly, clear CDN cache for: `brave-browser-downloads.s3.brave.com`, `brave-browser-apt-release.s3.brave.com`, `brave-browser-rpm-release.s3.brave.com`, `updates-cdn.bravesoftware.com`, `updates.bravesoftware.com`

### Updates Testing on Production
- [x] Wait for confirmation that Windows live update works
- [x] Wait for confirmation that macOS live update works
- [x] Wait for confirmation that Linux live update works
- [ ] Update the Brave Snap Package under Ubuntu

### Download Binaries from Brave.com
- [x] download binary from https://brave.com
- [x] download binary from https://brave.com/download
- [x] download binary using https://laptop-updates.brave.com/latest/winx64
- [x] download binary using https://laptop-updates.brave.com/latest/winia32
- [x] download binary using https://laptop-updates.brave.com/latest/osx
- [x] download binary to test promos https://brave.com/kjo527 - kjozwiak.github.io [Production]
- [x] download binary to test promos https://brave.com/red194 - Twitch (redPwnie) [Production]
- [x] download binary to test promos https://brave.com/kam253 - YT (kamiljoz) [Production]
- [x] download binary to test promos https://brave.com/bra941 - YT (braveqa1) [Production]

### Announcements
- [x] Publish the release notes to github and brave.com/releases. (@rebron) 
- [x] Announce release on https://community.brave.com/ (@brave-matt)
- [x] Announce release on https://www.reddit.com/r/brave_browser/ (@brave-matt)
- [x] Notify #general, #brave-core, #pr, #testers of the latest release with a link to the release notes

### Update Release channel wiki
- [ ] Update entries here as needed: https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

**Comment by rebron** [comment]
Marking closed. Released 12/20/2018
