### ISSUE TITLE
Release checklist for `1.45.x - Release #9`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26975]
Feel free to copy this into an issue if you want to keep track of items per-milestone.
Be super sure that <version> is replaced with the version you wish to use.

### Prerequisites

- [ ] Double check the previous release/milestone and ensure everything has been QA'd
  - **Note:** If there's issues that need to be checked, create a `master` GH issue that lists the issues that need to be QA'd
- [ ] Ensure that the RC can be launched via the GPS internal test channel (basically verifying that `.aab` updates are working)
- [ ] Consult with the security team to ensure that all security issues have been included.
   - [ ] Release using the `critical` feature (forces users to update/restart) if there's a zero day vulnerability being exploited
- [ ] Consult with PR team (@catherinecorre) and provide heads up on release timing, screenshots, other deliverable's.

### Security/Privacy Checks

 - [ ] Download the latest version of [ClassyShark3xodus](https://f-droid.org/en/packages/com.oF2pks.classyshark3xodus/) and ensure that zero trackers are found within Brave.
   - [ ] Once scanned, ensured that selecting `Settings` -> `Sub Totals` also displays zero trackers

**`Good Example (Brave)`** | **`Good Example (Brave)`** | **`Bad Example (Firefox)`**
---------------------------|---------------------------|------------------------------
![Screenshot_20220411-220522](https://user-images.githubusercontent.com/2602313/162865301-fe3e4efd-dac0-4403-a8c9-5bee07881341.png) | ![Screenshot_20220411-220913](https://user-images.githubusercontent.com/2602313/162865300-6c4b5929-a5ac-47fe-9df4-4faca1f36534.png) | ![Screenshot (Apr  11, 2022 11_42_57)](https://user-images.githubusercontent.com/2602313/165127332-bb756dee-92ec-476c-8730-ded93a8d1677.png)

### Release Notes to Staging

- [ ] Mark closed issues in github as `release-notes/exclude` or `release-notes/include`.
- [ ] Commit release notes to [CHANGELOG_Android.md](https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md) in the [`brave-browser`](https://github.com/brave/brave-browser/) `master` branch
- [ ] Stage release notes to https://github.com/brave/brave-browser/releases/

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.133 Chromium: 107.0.5304.141 (Official Build) (32-bit)
--- | ---
Revision | cddb1ab381a982f400a57e15e14080e1aaaca4b8-refs/branch-heads/5304_105@{#3}
OS | Android 12; Build/SP1A.210812.016
```

![Screenshot_20221124-231957_ClassyShark3xodus](https://user-images.githubusercontent.com/2602313/203901058-ae549688-88ff-4259-bf18-e1c19652d2d5.jpg)

------------

Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` using `Android 12` using the following build(s):

```
Brave | 1.45.133 Chromium: 107.0.5304.141 (Official Build) (32-bit)
--- | ---
Revision | cddb1ab381a982f400a57e15e14080e1aaaca4b8-refs/branch-heads/5304_105@{#3}
OS | Android 12; Build/SP2A.220305.013
```

![Screenshot_20221124_232148_ClassyShark3xodus](https://user-images.githubusercontent.com/2602313/203901064-a29b6c39-00c3-4593-9f05-7c2e0ef83abb.jpg)
