### ISSUE TITLE
extensions.brave.com

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#28]
We would like to have a page showcasing extensions which are installable in the Brave browser. Users could visit this page, find extensions they're interested in, and then install them

## Milestones
- [x] Stand up a REST API around the store functionality. Used to fetch extension details
- [x] Create the minimum HTML/JavaScript needed for a client page to call the REST API and show the results (even just if in a div)
- [x] Get the client page using React (including Brave UI)
- [ ] Update client page with JavaScript needed to install an extension (one of the extensions being listed)
- [ ] If extensions are already installed, show a difference in the UI ("already installed")
- [ ] Have a details page available for each extension. This would route to a different URL like `/store/extension-id-here`. We'd want to be storing enough information to make this useful (ex: instead of just extension id, name, version- we should pull more fields)
- [ ] Componentize the UI code using React - use Brave UI where possible
- [ ] Create unit tests for the REST API
- [ ] Integrate a linter (ex: `standard`) with the project
- [ ] Setup a git pre-push hook to ensure lint/tests pass before a push is done

## Taking this to the next level
There are a few things we could do to make this experience better which are definitely related, but should be captured in different issues.
- Updating extensions (perhaps by calling the REST API?)
- Adding new extensions get added to the store
- Vetting extensions for quality (ex: not malware, not making risky calls)
- Management interface for extensions (for our use- ex: used to approve/reject extensions)

**Comment by bsclifton** [comment]
cc: @sidstamm

**Comment by bbondy** [comment]
Moved this from 0.55.x to 1.0 milestone 
cc @davidtemkin @rebron

**Comment by rebron** [comment]
cc @mrzealot

**Comment by ilyaigpetrov** [comment]
I think extensions.brave.com risks to get censored in some countries because of some extensions published like Dissenter. Could you, please, consider making extensions installable and updatable via IPFS? E.g. from http://localhost:8080/ipns/extensions.brave.com. Let me know if I should create a separate issue for this feature request.

**Comment by bsclifton** [comment]
Closing as stale. I know we'd like to do this - and we had created https://github.com/brave-experiments/brave-extension-store but never finished unfortunately.

If we'd like to tackle this in the future, I think we can create a spec and then either un-archive [brave-extension-store](https://github.com/brave-experiments/brave-extension-store) or create a new repo/page
