### ISSUE TITLE
Enable Website Newsletter blocking in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#28115]
## Description 
Enable blocking of Newsletter overlays, Newsletter divs in Brave. 

## Why?

- Distracts the enduser from website content. Currently we're covering:
  - Preroll overlay:  Shows newsletter on website load 
  - Midroll overlay: Shows on a timer while scrolling or randomly showing
  - Static divs showing through out the web page

Also fix any disabled scrollbars because of newsletter overlays.

## Sample of newsletter distractions:

1. Newsletter overlays:  `https://www.tomshardware.com/news/amd-polaris-forsaken-dx12`

![Newsletter-tomshardware](https://user-images.githubusercontent.com/1659004/215256246-4e906811-2de6-4a81-a5b9-aa96e0fe9c8d.jpg)

2. Newsletter overlays + Scroll blocked: `https://megacatstudios.com/pages/wrestlequest`

![megacat](https://user-images.githubusercontent.com/1659004/215256550-6b60f833-7377-4d88-9938-c10d91513402.jpg)

3. Preroll Newsletter (Loads newsletter overlay on load): `https://www.readtangle.com/`

![tangle-load](https://user-images.githubusercontent.com/1659004/215256768-e588e7f2-e3d3-4bb5-83dd-6b887d9c0000.jpg)

## TODO (Before anything lands)

- [x] Limit existing problem filters: https://github.com/easylist/easylist/commit/02c48a5b794ebad7f373d881bc708b4a6164abb6
- [ ] Add Fanboy newsletter list into `brave://adblock` for testing
- [ ] Cleanup generic rules, remove possible problem filters.
- [ ] Make more site specific rules
- [ ] Audit any existing rules
- [ ] Re-audit and re-check any sites.

No ETA just yet. Enabling Fanboy Annoyances in brave ://adblock will remove these, since this has newsletter blocking by default. We already have a decent user base using Fanboy Annoyances. Seperating newsletters section from Annoyances can be done easily. 

Aggressive mode will be need to be effective also cc: @antonok-edm
