### ISSUE TITLE
Implement Tip / Contribution Banner 3.0

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28148]
## Description

```[tasklist]
### Tasks
- [x] New design https://github.com/brave/brave-browser/issues/29020
- [ ] Use Chromium bubble
- [ ] Make closeable when clicking outside of banner: https://github.com/brave/brave-browser/issues/23740
- [ ] Handle new PCDN entries for Web3 addresses and channel page link
- [x] Implement spinner when balance cannot be fetched (as done for https://github.com/brave/brave-browser/issues/28549?notification_referrer_id=NT_kwDOAK9wRbM1NjE0OTMxNTgxOjExNDk3NTQx#event-8606681291). Resolved with: https://github.com/brave/brave-browser/issues/28793
- [ ] Implement new blue checkmark icon: https://github.com/brave/brave-browser/issues/28208
```

@Miyayes For Figma.

**Comment by LaurenWags** [comment]
@brave/qa-team will do full testing on Windows and macOS, with reduced cases on Linux.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 21H2 (Build 19044.2965)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.113 Chromium: 114.0.5735.53 (Official Build) (64-bit) 
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Ubuntu 18.04 LTS


<details>
<summary>User State 3: Connected - PASSED</summary>

- When the tip panel is opened,
  - The user's BAT balance for their provider should be displayed.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/8afd41d0-63fd-4f47-bf99-8afba6f8d722)|![image](https://github.com/brave/brave-browser/assets/34715963/f38a0e06-78e0-498d-a2bd-3da2a9d469ad)

- When the tip panel is opened and the user is logged out from their wallet provider,
   - A login message should be displayed,
   - And a "Log In" button should be displayed that will take the user to the wallet provider's authorization URL.

Gemini:
![image](https://github.com/brave/brave-browser/assets/34715963/9af9de95-613b-448f-8ee9-fa603bbb0c4c)|![image](https://github.com/brave/brave-browser/assets/34715963/d9201c95-b457-44c6-836a-31f9f0ba19b6)
--|--

- When the tip panel is opened and the publisher does not have the same wallet provider as the user,
  - A "mismatch" message should be displayed.

Gemini:
![image](https://github.com/brave/brave-browser/assets/34715963/e9bbf277-b490-47b5-acb6-c02151eb94d0)|![image](https://github.com/brave/brave-browser/assets/34715963/c7266130-35a6-4724-9273-6922195efd65)
--|--

- When "Send" is clicked with a valid amount,
  - The tip should be sent and the success UI should be displayed,
  - And the "Share" button should open Twitter with a "new post" prompt.

Success Dark UI | Tweet from Dark UI | Success Light UI | Tweet from Light UI
--- | --- | --- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/5cb7465b-61fa-4cde-8658-3211f3a3b2d0)|![image](https://github.com/brave/brave-browser/assets/34715963/71e320fa-c2d2-457f-871b-42bf002e6fa3)|![image](https://github.com/brave/brave-browser/assets/34715963/5e4396f5-f8cc-4921-a3d6-e55e3b154735)|![image](https://github.com/brave/brave-browser/assets/34715963/2559726b-b22a-4b70-b6fa-98c1ee7d3c42)


- When "Send" is clicked and the monthly toggle is set,
  - A one-time tip should be sent,
  - And the success UI should be displayed
  - And a monthly contribution should be added to the "Monthly Contributions" list visible on the Rewards page.


![image](https://github.com/brave/brave-browser/assets/34715963/64c8d598-8a15-4e7d-b206-0de7d4fb4369)|![image](https://github.com/brave/brave-browser/assets/34715963/d408985c-d616-4bbe-a5e4-5fc2551db3d0)|![image](https://github.com/brave/brave-browser/assets/34715963/d5e0def1-e966-4567-9c9b-de551a06e40b)
--|--|--

- When the tip panel is opened and a monthly contribution is already set for the publisher,
  - The tip panel should display a message indicating that a monthly contribution is already set.

![image](https://github.com/brave/brave-browser/assets/34715963/b6f811b9-a053-4d9a-a363-b89a91b411be)|![image](https://github.com/brave/brave-browser/assets/34715963/ea5f843d-4eea-4a41-a203-24868b09fe69)|![image](https://github.com/brave/brave-browser/assets/34715963/9c0adef8-4d2e-48bc-840a-6d026e18291f)|![image](https://github.com/brave/brave-browser/assets/34715963/ce302df1-fa31-49b5-abeb-a7d92babd1bd)
--|--|--|--

- Advanced my computer clock to next monthly contribution date (Jun 12 per Monthly Contributions section of brave://rewards
  - Confirmed monthly tip was sent as expected
  - Confirmed next monthly tip was scheduled per Monthly Contributions section of brave://rewards)

- When the Rewards panel is opened for an unverified publisher,
  - A message should be displayed stating that the publisher is not verified,
  - And the "Send Contribution" button should be disabled.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/2bb57b75-5b8d-4cef-af86-f4e64a468fc9)|![image](https://github.com/brave/brave-browser/assets/34715963/2d75475d-9ed4-4727-b603-e2114b6681f0)


- When the Rewards panel is opened for a verified publisher,
  - The "Send Contribution" button should be enabled.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/5cabe504-4dd7-4249-b4c8-3851604705b2)|![image](https://github.com/brave/brave-browser/assets/34715963/c079446d-3c35-4463-9533-3f333c2b37e7)


- When an in-line tip icon is clicked for an unverified publisher,
  - The Rewards panel should be opened with a message indicating the publisher is not verified,
  - And the "Send Contribution" button should be disabled.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/ee8e74b1-3d5e-4b81-b678-4627d420300f)|![image](https://github.com/brave/brave-browser/assets/34715963/7a5612ae-07ef-4249-85a9-74e37deee2ee)


- When an in-line tip icon is clicked for a verified publisher,
  - The tip panel should be opened.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/4d5c4b72-af75-494b-8269-68cf66feebbd)|![image](https://github.com/brave/brave-browser/assets/34715963/1d993450-75d6-4883-ae58-df899869da16)


- When an error is encountered when creating a transaction with the wallet provider.
  - An error message should be displayed,
  - And a "Try Again" button should be displayed.

Gemini:
![image](https://github.com/brave/brave-browser/assets/34715963/2adfa690-32d7-4349-8ddb-c671a795f042)|![image](https://github.com/brave/brave-browser/assets/34715963/04950a26-5f89-4f30-9646-458aebf54c8e)
--|--


</details>
