### ISSUE TITLE
Individualize Monthly Tip dates based on date they are set (staggered monthly contributions)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28173]
## Description

When set, a Monthly tip attempts to fire off ~30 days after they're set, and every 30 days thereafter. They no longer all go by the same monthly “Next monthly tips date” date regardless of when they are set. 

```[tasklist]
### Tasks
- [ ] Change Monthly Tip timing
- [ ] Show next attempt/recurrence date in the date column in brave://rewards > Monthly Tips
- [ ] Remove the Payment Date line in Monthly Tips section 
- [ ] Remove "Monthly Tip" section and config in the Rewards dropdown panel
```

**Comment by Miyayes** [comment]
Should regression test old monthly tip logic once this lands. However, we will test this new functionality as part of the new tip banner.

**Comment by LaurenWags** [comment]
@brave/qa-team let's test this one on Windows and macOS

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsng Galaxy version 12` running `Bravemonoarm64.apk_1.51.80`

**Comment by GeetaSarvadnya** [comment]
QA Blocked on Android untill the issue is resolved https://bravesoftware.slack.com/archives/CNH9Q6REV/p1681756674373229?thread_ts=1681746838.676479&cid=CNH9Q6REV

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` as https://github.com/brave/brave-browser/issues/29859 is fixed and uplifted to 1.51.x.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.51.109`
