### ISSUE TITLE
Update "Verified creator" blue checkmark icon

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28208]
## Description

Update verified creator icon wherever it appears. 

```[tasklist]
### Tasks
- [ ] In URL bar (on BAT icon)
- [ ] On Rewards panel
- [ ] On Tipping banner
- [ ] On brave://rewards page when verified creators are listed
- [ ] ... Any other 
```
New:  ![image](https://user-images.githubusercontent.com/11497541/216130459-a25e5d51-695c-430e-a133-3c9c5e32555a.png)

Figma: https://www.figma.com/file/2c2RfbIJBzxwa2BXqSLyE0/P2P-Tipping?node-id=1%3A17&t=g8lHMQD7OIO5Evye-0 

Perhaps coordinate with @zenparsing who will be working on the https://github.com/brave/brave-browser/issues/28148 (new tipping banner).

**Comment by GeetaSarvadnya** [comment]
@Miyayes @zenparsing In beta the icon is overlapping on the BAT logo but in the issue description, there is quite some space between both icons. Just wanted to know which one correct spec or the issue description.

cc: @Miyayes 

Beta - 1.53.x | Spec  | Description
--------------|--------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/7b6386cf-d9c9-4084-9b26-a7f258b55bb5) | ![image](https://github.com/brave/brave-browser/assets/38657976/2abca3e0-e6a1-476a-9ccb-3948bd0a2c95) | ![image](https://github.com/brave/brave-browser/assets/38657976/0a66d3a7-2a98-4490-8e26-88ac053dfab6)

**Comment by Miyayes** [comment]
Overlap is fine. @GeetaSarvadnya  I'll update the issue description: 

From figma:
![image](https://github.com/brave/brave-browser/assets/11497541/bafcfd28-8d2e-487e-add1-825424781b03)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/18442

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (x86_64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision	1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS	Linux
```
