### ISSUE TITLE
[Meta Issue] Auto Asset Discovery

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#28732]
This is a meta issue to track auto asset discovery feature development.

Core:
- [X] Trigger asset discovery when restoring wallets or importing accounts. https://github.com/brave/brave-browser/issues/19746
- [X] Expose API for UI to trigger asset discovery and fire OnAssetDiscoveryCompleted when it's done. https://github.com/brave/brave-browser/issues/25820
- [X] Solana Asset discovery. https://github.com/brave/brave-browser/issues/27246
- [X] Added L2 support via using balance scanner contract for EVM chains. https://github.com/brave/brave-browser/issues/28203
- [x] Fire OnAssetDiscoveryStarted/Completed events for both UI and core triggered asset discovery. https://github.com/brave/brave-browser/issues/27776
- [x] https://github.com/brave/brave-browser/issues/28651
- [ ] https://github.com/brave/brave-browser/issues/29304 (Blocked by frontend ERC1155 support)
- [x] https://github.com/brave/brave-browser/issues/29121
- [x] https://github.com/brave/brave-browser/issues/29400

Desktop UI:
- [X] Trigger asset discovery when loading portfolio page https://github.com/brave/brave-browser/issues/26547
- [ ] Handle OnAssetDiscoveryStarted/Completed events.

Android UI:
- [X] Trigger asset discovery when loading portfolio page. https://github.com/brave/brave-browser/issues/27344
- [ ] Handle OnAssetDiscoveryStarted/Completed event.

iOS UI:
- [X] Trigger asset discovery when loading portfolio page. https://github.com/brave/brave-ios/issues/6652
- [ ] Handle OnAssetDiscoveryStarted/Completed events.
