### ISSUE TITLE
[Meta Issue] Speedreader v2.5

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28739]
## Description 

This is a meta issue to track Speedreader v2.5 feature development.

Core:

- [ ] Add text to speech for Windows
- [ ] Add text to speech for macOS
- [ ] Add text to speech for Linux

Desktop UI:
- [ ] Change "reader mode" to "speedreader mode" and existing speedreader mode to "always on" option
- [ ] Update speedreader toggle to Always on UI
- [ ] Update default column width to be more readable
- [ ] Add time to read estimate
- [ ] Add inline toolbar for options for themes, font, and text size
- [ ] Add toolbar for text to speech
- [ ] Move Speedreader settings to brave://settings/getStarted
- [ ] Add site list for Always show in Speedreader with ability to add and remove sites to the list
- [ ] Provide method for any page to enter into speedreader mode

Android UI:

**Comment by HudsonAfonso** [comment]
- [ ] Provide method for any page to enter into speedreader mode
