### ISSUE TITLE
Follow-ups for shared pinned tabs(a.k.a. Persistent pinned tabs)

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#28873]
Follow-ups after https://github.com/brave/brave-browser/issues/28532

```[tasklist]
### Tasks
- [ ] #37125
- [ ] https://github.com/brave/brave-browser/issues/29865
- [x] `I unpinned all of my pinned tabs - and when the last one was unpinned, it crashes the browser` - https://brave.sp.backtrace.io/p/brave/debug?filters=(_deleted=0,_rxid="63320000-69c0-e309-0000-000000000000")&fingerprint=16f71aa104092914f4bb92a3c9e25f980c225ceae58c8d9512218da4e4a7fdb2&debug=("49628a4",0,0) - not reproducible
- [ ] https://github.com/brave/brave-browser/issues/37925
- [ ] https://github.com/brave/brave-browser/issues/38255
- [x] Closing a window with active shared pinned tab removes shared WebContents from other windows too - irreproducible
- [ ] https://github.com/brave/brave-browser/issues/37973
- [ ] https://github.com/brave/brave-browser/issues/38414
- [x] When closing a tab, if it's the last in the window, and there's another window, then close the window. i.e. ignore that there are pinned tabs in the window and don't prevent it closing as normal
- [ ] https://github.com/brave/brave-browser/issues/38444
- [ ] https://github.com/brave/brave-browser/issues/38472
- [ ] https://github.com/brave/brave-browser/issues/38509
- [ ] Restart browser and restore tabs results in duplicate shared pinned tabs, (https://bravesoftware.slack.com/archives/C042KL922P3/p1680714966162409) - this would be expected behavior
```

**Comment by rishiraj88** [comment]
Thanks, @sangwoo108 , for this.

**Comment by TEMP-ad** [comment]
I know this hasn't been touched for almost a year.

But the new **Bring all tabs to this window** https://github.com/brave/brave-core/pull/21933 is crashing the browser.
Many of the things listed here can also cause crashes, especially when you move tabs around and through screens, so this report is another one to the list for future reference when this amazing feature gets picked up again.

**Comment by ajayseeker** [comment]
Hi @sangwoo108,
I would like to work on the following task
"Don't close the pinned tab with cmd-w. Instead ignore it, or close the WebContents instance but leave the site pinned."
Do we still need this behaviour?
Also, I checked other browsers like Chrome, they don't support this. But yes thinking logically, it's a good idea to either not close or ask for confirmation from user when he presses Cmd + w.

**Comment by sangwoo108** [comment]
Hi @ajayseeker , the behavior is only when the shared pinned tab is enabled. That's because we don't want shared pinned tab to be closed accidentally.

**Comment by ajayseeker** [comment]
> Hi @ajayseeker , the behavior is only when the shared pinned tab is enabled. That's because we don't want shared pinned tab to be closed accidentally. If you think we should reconsider it, we always have a room for discussion
> 
> Please refer to [brave/brave-core#17295 (review)](https://github.com/brave/brave-core/pull/17295#pullrequestreview-1318841105)

I think this behaviour is good to have!
I would like to work on this. Can you please assign me this item?
Subsequently, I would like to explore other tasks mentioned in this issue too.

**Comment by sangwoo108** [comment]
@ajayseeker I really appreciate that. I created issue here https://github.com/brave/brave-browser/issues/37125

**Comment by sangwoo108** [comment]
Hi everyone, as of https://github.com/brave/brave-core/pull/23797 , we introduce preference for Shared pinned tab under `settings > appearance > tabs`. The flag will only reveal the preference but not enable the preference. Please turn on the pref if you want keep using it.

**Comment by TEMP-ad** [comment]
when you have a window with a pinned tab and a normal tab, and then you move the non-pinned tab, sometimes (often) it leaves behind a bunch of non visible windows. They disappear when `Show pinned tabs in all windows` is turned off.

From this screenshot I only had 1 window opened and it showed all of those invisible windows to send tabs to.
![image](https://github.com/brave/brave-browser/assets/156715894/0276caf8-6369-47ea-afb4-9712c16c47ec)

Also, drag and dropping a normal tab and attach it to other windows, especially trying to attach it 'back' to its previous window, seem to cause the tab to be blank, if it is a video, you can still hear it but no visible content. I could reproduce it 100% when using multiple monitors, moving a tab from one monitor to the other to an existing window and then back caused it 100%. This is also fixed by turning `Show pinned tabs in all windows` is turned off, so it can be turned off and on to quickly fix it.

1.68.61 Chromium: 126.0.6478.26 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3672)
