### ISSUE TITLE
Persist and reset Confirmations state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2909]
**Subtasks:**

- [ ] Implement ledger service implementation `Save`
- [ ] Implement bat-native-ledger `Save` as a proxy to ledger service implementation `Save`
- [ ] Implement ledger service implementation `Load`
- [ ] Implement bat-native-ledger `Load` as a proxy to ledger service implementation `Load`
- [ ] Implement ledger service implementation `Reset`
- [ ] Implement bat-native-ledger `Reset` as a proxy to ledger service implementation `Reset`

**Comment by tmancey** [comment]
Closing ticket as will be resolved as part of #2912

**Comment by LaurenWags** [comment]
Discussed with Terry/Jimmy - marking as QA/No as testing will be completed with https://github.com/brave/brave-browser/issues/3117
