### ISSUE TITLE
 ☂️ Umbrella issue: Implement multi-chain support in edit-visible assets

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29552]
## Description 
⚠️ This issue is an umbrella tracking issue. Below is a list of check boxes for individual items that need fixing.

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/29555
- [ ] https://github.com/brave/brave-browser/issues/31188
- [ ] https://github.com/brave/brave-browser/issues/27093
- [ ] https://github.com/brave/brave-browser/issues/30251
```

**Comment by Pavneet-Sing** [comment]
Closing, All MC support issue per spec are finished.
