### ISSUE TITLE
Lean on brave://rewards page for most Rewards settings in brave://settings/rewards

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30302]
## Description

We have duplicated many (but not all) Brave Rewards settings into brave://settings/rewards. We should keep some settings there, but remove the bulk of them.

```[tasklist]
### Tasks
- [ ] Keep Show Brave Rewards icon in address bar toggle
- [ ] Keep inline Tip button settings
- [ ] Add "Open full Brave Rewards settings" button that links out to brave://rewards at bottom. (This would only appear if Rewards is enabled.) Add in its own section under "Manage Brave Rewards".
```

![image](https://github.com/brave/brave-browser/assets/11497541/d6ef7acb-ac32-4f65-a497-81ad0413d531)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```

- Verified the test plan from https://github.com/brave/brave-core/pull/18483
