### ISSUE TITLE
Implement activity tab, show tx details and approve dialog(android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30608]
## Description 
Implement activity tab to:

```[tasklist]
### Tasks
- [x] Show all transactions excluding rejected
- [x] Show approval dialog for unapproved transactions
- [x] Show transactions details except unapproved
```

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.44 x64 build
- Verified steps from [brave/brave-core#18631](https://github.com/brave/brave-core/pull/18631)
- Verified activity tab is shown 
- Verified able to view submitted, unapproved, confirmed transactions in activity tab
- Verified rejected transactions are not shown in activity tab
- Encountered [#32199](https://github.com/brave/brave-browser/issues/32199)

https://github.com/brave/brave-browser/assets/17010094/6f7c81e7-f86b-41a2-91a5-618b60822e07
