### ISSUE TITLE
Make native UIs for playlist and functions of them

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#31159]
subtask of https://github.com/brave/brave-browser/issues/25829

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/31777
- [ ] https://github.com/brave/brave-browser/issues/31581
- [ ] https://github.com/brave/brave-browser/issues/31584
- [ ] https://github.com/brave/brave-browser/issues/31635
- [ ] https://github.com/brave/brave-browser/issues/32000
- [ ] https://github.com/brave/brave-browser/issues/32101
- [ ] https://github.com/brave/brave-browser/issues/32102
```

**Comment by sangwoo108** [comment]
DeletePlaylistConfirmDialog
<img width="405" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/bf3fcc57-0392-41ac-ab97-9087b19091e9">

NewPlaylistDialog
<img width="568" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/a247b5eb-af4a-44ef-a551-1975afdb6c5a">

MoveMediaDialog
<img width="387" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/fa68a118-d6bd-45b8-b041-9eacc5389a0d">
