### ISSUE TITLE
Manual test run on Linux for 0.59.x - Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3158]
## Per release specialty tests
 - [x] Corrupted auto-contribute table.([#3134](https://github.com/brave/brave-browser/issues/3134))
 - [x] Browser requires restart for "x-brave-partner" headers to start working.([#3143](https://github.com/brave/brave-browser/issues/3143))
 - [x] Upgrade from 72.0.3626.71 to 72.0.3626.81.([#3146](https://github.com/brave/brave-browser/issues/3146))
 - [x] Pubs which are already in a-c table are getting deleted on upgraded profile after revisiting.([#3162](https://github.com/brave/brave-browser/issues/3162))
 - [x] Weight is not implemented correctly.([#3163](https://github.com/brave/brave-browser/issues/3163))

### Installer

- [x] Check that installer is close to the size of last release
- [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x] Make sure that data from the last version appears in the new version OK
- [x] With data from the last version, verify that
  - [x] bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] cookies are preserved
  - [x] installed extensions are retained and work correctly
  - [x] opened tabs can be reloaded
  - [x] stored passwords are preserved
  - [x] unpinned tabs can be pinned

### Import tests

- [x] Verify that you can import bookmarks, cookies, history, passwords and stats from `muon`
- [x] Verify that you can import bookmarks, cookies, history, passwords from Google Chrome 

### Widevine

- [ ] Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [ ] Test that you can stream on Netflix on a fresh profile after installing Widevine
- [ ] Test that you can stream Premium Content on YouTube on a fresh profile after installing Widevine
- [ ] Test that you can stream Amazon Prime Time on a fresh profile after installing Widevine

### Rewards

- [x] Verify wallet is auto created after enabling rewards
- [x] Verify account balance shows correct BAT and USD value
- [x] Verify you are able to restore a wallet
- [x] Verify wallet address matches the QR code that is generated under `Add funds`
- [x] Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x] Verify adding funds via any of the currencies flows into wallet after specified amount of time
- [x] Verify adding funds to an existing wallet with amount, adjusts the BAT value appropriately
- [x] Verify monthly budget shows correct BAT and USD value
- [x] Verify you are able to exclude a publisher from the auto-contribute table by clicking on the `x` in auto-contribute table and popup list of sites
- [x] Verify you are able to exclude a publisher by using the toggle on the Rewards Panel
- [x] Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [x] Verify when you click on `Send a tip`, the custom tip banner displays
- [x] Verify you are able to make one-time tip and they display in tips panel
- [x] Verify you are able to make recurring tip and they display in tips panel
- [x] Verify you can tip a verified publisher
- [x] Verify you can tip a verified YouTube creator
- [x] Verify tip panel shows a verified checkmark for a verified publisher/verified YouTube creator
- [x] Verify tip panel shows a message about unverified publisher
- [x] Verify BR panel shows message about an unverified publisher
- [x] Verify you are able to perform a contribution
- [x] Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators
- [x] Verify that disabling Rewards and enabling it again does not lose state
- [x] Verify that disabling auto-contribute and enabling it again does not lose state
- [x] Adjust min visit/time in settings. Visit some sites and YouTube channels to verify they are added to the table after the specified settings
- [x] Upgrade from older version
  - [x] Verify the wallet balance is retained and wallet backup code isn't corrupted
  - [x] Verify auto-contribute list is not lost after upgrade
  - [x] Verify tips list is not lost after upgrade
  - [x] Verify wallet panel transactions list is not lost after upgrade

## Update tests

- [ ] Verify visiting `brave://settings/help` triggers update check
- [ ] Verify once update is downloaded, prompts to `Relaunch` to install update

## Chromium upgrade tests

- [x] Verify `brave://gpu` on Brave and `chrome://gpu` on Chrome are similar for the same Chromium version on both browsers

#### Adblock

- [x] Verify referrer blocking works properly for TLD+1. Visit `https://technology.slashdot.org/` and verify adblock works properly similar to `https://slashdot.org/`

#### Components
- [x]  Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

**Comment by btlechowski** [comment]
Looks good to me. Tested on 0.59.33.
