### ISSUE TITLE
Menu for 'reopen closed tab' doesn't exists in Linux

### ISSUE THREAD

**Issue by hbaklan943** [brave/brave-browser#31631]
## Description 

Can't right click the plus icon that is used for opening a new tab. Linux desktop version of brave doesn't seem to have the feature 'reopen closed tab'. That the Windows version has.

## Steps to Reproduce

   1. Open a tab and go to an URL
   2. Close it  
   3. Right click the plus symbol that is used for opening a new tab.

## Actual result:

No menu to select 'reopen closed tab' appears.

## Expected result:
![image](https://github.com/brave/brave-browser/assets/39270324/c35e0af7-469e-43a9-97d3-e42ff6054840)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit) 
Revision	c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS	Linux

## Version/Channel Information:

Only in linux as far I noticed.

- Can you reproduce this issue with the current release?  -YES
- Can you reproduce this issue with the beta channel? -N/A
- Can you reproduce this issue with the nightly channel? -N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I used Ubuntu if that helps.

```[tasklist]
### Tasks
- [ ] Adding the feature that is already exists in Windows version of Brave to Linux versions.
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
