### ISSUE TITLE
Playlist Web UI features

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#31913]
```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/31942
- [ ] https://github.com/brave/brave-browser/issues/31969
- [ ] https://github.com/brave/brave-browser/issues/32027
- [ ] https://github.com/brave/brave-browser/issues/32034
- [ ] https://github.com/brave/brave-browser/issues/32101
- [ ] https://github.com/brave/brave-browser/issues/32102
- [ ] https://github.com/brave/brave-browser/issues/32116
- [ ] https://github.com/brave/brave-browser/issues/32055
- [ ] https://github.com/brave/brave-browser/issues/32117
- [ ] https://github.com/brave/brave-browser/issues/32081
- [ ] https://github.com/brave/brave-browser/issues/32119
- [ ] https://github.com/brave/brave-browser/issues/32177
- [ ] https://github.com/brave/brave-browser/issues/32219
- [ ] https://github.com/brave/brave-browser/issues/32253
- [ ] https://github.com/brave/brave-browser/issues/32290
- [ ] https://github.com/brave/brave-browser/issues/32331
- [ ] https://github.com/brave/brave-browser/issues/32407
- [ ] https://github.com/brave/brave-browser/issues/32433
- [ ] https://github.com/brave/brave-browser/issues/32454
- [ ] https://github.com/brave/brave-browser/issues/32471
- [ ] https://github.com/brave/brave-browser/issues/32515
- [ ] https://github.com/brave/brave-browser/issues/32745
- [ ] https://github.com/brave/brave-browser/issues/32611
- [ ] https://github.com/brave/brave-browser/issues/32960
- [ ] https://github.com/brave/brave-browser/issues/33030
- [ ] https://github.com/brave/brave-browser/issues/33157
- [ ] https://github.com/brave/brave-browser/issues/34216
- [ ] https://github.com/brave/brave-browser/issues/33404
- [ ] https://github.com/brave/brave-browser/issues/32600
- [ ] https://github.com/brave/brave-browser/issues/33589
- [ ] https://github.com/brave/brave-browser/issues/34214
- [x] [Playlist] Default font isn't applied to Video player doesn't
- [x] Selected items should have background color
- [x] Playlist item should have maximium height
- [x] Remove played items
- [x] Don't set the current time if the item reached the end of file
- [x] Update sidebar icon
- [x] Revert overlay style player control
- [ ] https://github.com/brave/brave-browser/issues/34885
- [ ] https://github.com/brave/brave-browser/issues/34947
- [x] [Playlist] Notification stack
- [ ] https://github.com/brave/brave-browser/issues/32928
- [ ] https://github.com/brave/brave-browser/issues/32929
- [ ] Item suggestion from empty playlist folder
```

**Comment by sangwoo108** [comment]
Close as left items are not in MVP.
