### ISSUE TITLE
[Brave News]: Feed Upgrade Tracking Issue

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#32172]
@LorenzoMinto and @mattmcalister have been working on a redesigned feed for Brave News. This is a tracking issue for the work in Brave Core:

**Design Document**
https://docs.google.com/document/d/1bSVHunwmcHwyQTpa3ab4KRbGbgNQ3ym_GHvONnrBypg

**Prototype PR**
https://github.com/brave/brave-core/pull/18965

**Sub Issues** (in order)
- https://github.com/brave/brave-browser/issues/31747
- https://github.com/brave/brave-browser/issues/32131
- https://github.com/brave/brave-browser/issues/32171
- https://github.com/brave/brave-browser/issues/32173
- https://github.com/brave/brave-browser/issues/32174
- https://github.com/brave/brave-browser/issues/32175
- https://github.com/brave/brave-browser/issues/32320
- https://github.com/brave/brave-browser/issues/32820

cc @aurangzaib048 @petemill
```[tasklist]
### MVP Tasks
- [x] Determining whether there are updates to the feed
- [ ] https://github.com/brave/brave-browser/issues/35193
- [ ] https://github.com/brave/brave-browser/issues/34950
- [ ] https://github.com/brave/brave-browser/issues/34967
- [ ] https://github.com/brave/brave-browser/issues/34749
- [ ] https://github.com/brave/brave-browser/issues/34595
- [ ] https://github.com/brave/brave-browser/issues/34525
- [ ] https://github.com/brave/brave-browser/issues/34498
- [ ] https://github.com/brave/brave-browser/issues/34591
- [ ] https://github.com/brave/brave-browser/issues/33505
- [ ] https://github.com/brave/brave-browser/issues/33672
- [ ] https://github.com/brave/brave-browser/issues/34330
- [ ] https://github.com/brave/brave-browser/issues/33510
- [ ] https://github.com/brave/brave-browser/issues/34206
- [ ] https://github.com/brave/brave-browser/issues/34143
- [ ] https://github.com/brave/brave-browser/issues/33296
- [ ] https://github.com/brave/brave-browser/issues/34028
- [ ] https://github.com/brave/brave-browser/issues/33645
- [ ] https://github.com/brave/brave-browser/issues/33819
- [ ] https://github.com/brave/brave-browser/issues/33897
- [ ] https://github.com/brave/brave-browser/issues/33998
- [ ] https://github.com/brave/brave-browser/issues/34083
- [ ] https://github.com/brave/brave-browser/issues/34592
- [ ] https://github.com/brave/brave-browser/issues/34593
- [ ] https://github.com/brave/brave-browser/issues/34594
- [ ] https://github.com/brave/brave-browser/issues/34621
- [ ] https://github.com/brave/brave-browser/issues/34751
- [ ] https://github.com/brave/brave-browser/issues/34782
- [ ] https://github.com/brave/brave-browser/issues/34819
```

```[tasklist]
### NOT MVP
- [ ] Search
- [ ] https://github.com/brave/brave-browser/issues/34497
- [ ] All topics card
- [ ] Discovery card: channel suggestions
- [ ] Now trending sidebar section
- [ ] Expanding grouped clusters ("view more")
- [ ] https://github.com/brave/brave-browser/issues/33669
- [ ] https://github.com/brave/brave-browser/issues/34121
- [ ] [Brave News]: Fancy scroll down animation
```

### Uplift to 1.62.x
(tick when uplift PR created, rather than when uplifted)
- [x] https://github.com/brave/brave-core/pull/21281
- [x] https://github.com/brave/brave-core/pull/21282
- [x] https://github.com/brave/brave-core/pull/21144
- [x] https://github.com/brave/brave-core/pull/21146
- [x] https://github.com/brave/brave-core/pull/21143
- [x] https://github.com/brave/brave-core/pull/21142
- [x] https://github.com/brave/brave-core/pull/21230
- [x] https://github.com/brave/brave-core/pull/21111
- [x] https://github.com/brave/brave-core/pull/21295
- [x] https://github.com/brave/brave-core/pull/21302
- [x] https://github.com/brave/brave-core/pull/21323
- [x] https://github.com/brave/brave-core/pull/21347
- [x] https://github.com/brave/brave-core/pull/21393
- [x] https://github.com/brave/brave-core/pull/21410
- [x] https://github.com/brave/brave-core/pull/21427
- [x] https://github.com/brave/brave-core/pull/21439
- [x] https://github.com/brave/brave-core/pull/21414
- [x] https://github.com/brave/brave-core/pull/21413
- [x] https://github.com/brave/brave-core/pull/21476
- [x] https://github.com/brave/brave-core/pull/21495
- [x] https://github.com/brave/brave-core/pull/21507
- [x] https://github.com/brave/brave-core/pull/21516
- [x] https://github.com/brave/brave-core/pull/21557
- [x] https://github.com/brave/brave-core/pull/21581
- [x] https://github.com/brave/brave-core/pull/21602
- [x] https://github.com/brave/brave-core/pull/21590
- [x] https://github.com/brave/brave-core/pull/21580

**Comment by fallaciousreasoning** [comment]
Meeting notes from 2023-11-02 https://github.com/brave/brave-browser/issues/34048
