### ISSUE TITLE
🏖 Portfolio and NFT wallet 2.0 filters Umbrella issue

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#32438]
## Description 
Portfolio and NFT wallet 2.0 filters Umbrella issue

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/31926
- [ ] Allow Multiple Selection for Network Filters
- [ ] Sort assets by High-Low (default), Low-High, A-Z, Z-A
- [ ] Hide assets less than $0.05 value toggle.
- [ ] Network Filter, All networks selected by default, except test networks
- [ ] Account Filter, All accounts selected by default
- [ ] Group By (Accounts, networks, none)
- [ ] https://github.com/brave/brave-browser/issues/31921
```
