### ISSUE TITLE
[Playlist] Iterate Design QA

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#32540]
Source: https://www.figma.com/file/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?type=design&node-id=1568%3A50&mode=design&t=UNaXB3xFo8h7YY6S-1

```[tasklist]
### Tasks
- [x] Header icons size is too big
- [x] Context menu should be on top of other ui
- [x] Playlist item's cached check icon is too big
- [x] Fix the width for context menu anchor button
- [x] context menu anchor button icon size is too big
- [x] Playlist folder's thumbnail aspect ratio isn't right
- [x] Playlist folder's background should be blurred
- [x] Video palyer should reach lef and right edges
- [x] Video player's controls' size is too big
- [x] Video player should show favicon
- [x] Player's control area should have a subtle background - blured thumbnail
- [x] player area should have shadow
```
