### ISSUE TITLE
Enhance links on Player

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#33030]
```[tasklist]
### Tasks
- [x] ContextMenu to go to the original page
- [x] Clicking Miniplayer's title should navigate to the original folder
- [x] Miniplayer need close button on the top-right side
```
