### ISSUE TITLE
[ads] Neural text classification model

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33871]
MVP:
- [x] [[ads] Transition text classification v2 models from JSON to FastBuffers](https://github.com/brave/brave-browser/issues/33336)
- [x] [[ads] Transition text classification v1 models from JSON to FastBuffers](https://github.com/brave/brave-browser/issues/33831)
- [x] [[ads] Change text classification model version to support major.minor](https://github.com/brave/brave-browser/issues/33830)
- [x] [[ads] Add text classification model v1 flatbuffer support for non en languages](https://github.com/brave/brave-browser/issues/33829)
- [x] [[ads] Generate flatbuffer text classification model component language resource ids](https://github.com/brave/brave-browser/issues/33828)
- [x] [[[ads] Transition text classification FlatBuffers model from in-memory to a memory mapped file](https://github.com/brave/brave-browser/issues/33812)
- [x] [[ads] Generate and upload text classification CRX component resource packages](https://github.com/brave/brave-browser/issues/33832)

--

https://github.com/brave/brave-browser/projects/26#column-19669846

**Comment by tmancey** [comment]
@iambrianfung all of the above for the MVP has been completed
