### ISSUE TITLE
[ads] iOS unification

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33870]
**Q2/2024:**
- [x] [[ads] Unify iOS federated learning](https://github.com/brave/brave-browser/issues/33787)
- [x] [[ads] Sanity test iOS `NotifyTab*ContentDidChange` business logic](https://github.com/brave/brave-browser/issues/37936)
- [x] [[ads] Sanity test iOS NotifyTabDidChange business logic](https://github.com/brave/brave-browser/issues/37935)

--

https://github.com/brave/brave-browser/projects/26#column-19651416

--

As part of the above, we will also work on browser layer issues; see https://github.com/brave/brave-browser/projects/26#column-19667912.

**Comment by tmancey** [comment]
Closing issue as resolved tasks for Q2.
