### ISSUE TITLE
[Playlist] Enhance Playlist player controls

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#34216]
```[tasklist]
### Tasks
- [x] The next/prev button : If it's shorter than a 10 minute file, start from the beginning, otherwise start form the last played position
- [x] Don't change items order even when it's shuffled
- [x] the loop button for 1. play list in a loop, 2. play one song on repeat, and 3. reset/original state
```
