### ISSUE TITLE
Rewards giftbox image needs `margin-bottom: -Xpx`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#34293]
The giftbox image extends a bit too far downward, likely because of a dropshadow. As a result, text under looks too far from the main part of the image. To fix this, we can add negative bottom margin:

```[tasklist]
### Tasks
- [ ] NTP Rewards widget `-10px` 
- [ ] Rewards panel `-10px`
- [ ] brave://rewards `-25px` 
```

**Comment by Miyayes** [comment]
Ready: https://www.figma.com/file/VIkvO8TBQXVBnvKn4w8iYu/BR-onboarding?type=design&node-id=0-1&mode=design&t=Y6VPK3pDyMDuc3xq-0
