### ISSUE TITLE
Meta Issue: Transaction Simulation Improvements

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34570]
## Description 

Transaction Simulations fail for the following events

Solana
- [ ] Sending SOL  
- [ ] Sending SPL Tokens

[Ethereum](https://metamask.github.io/test-dapp/) 

- [ ]  Deploying contracts
- [ ] Malicious ETH Transfer
- [ ] Malicious Approval for All
- [ ] Scan Malicious Sign Request (Out of scope)

**Comment by josheleonard** [comment]
https://github.com/brave/brave-browser/issues/34617

**Comment by josheleonard** [comment]
Latest test results:

Sign and Send Transaction (Legacy)
- failed -- A response parsing error has occurred: 

Sign and Send Transaction (v0)
- failed -- A response parsing error has occurred: 

Sign and Send Transaction (v0 + lookup table) (devnet only
- Works

Sign and Send Transaction (Request)
- failed -- A response parsing error has occurred: 

Sign and Send SPL Token Transaction
- failed -- A response parsing error has occurred: 

Sign Transaction
- failed -- A response parsing error has occurred

Sign Transaction (Invalid blockhash)
- Doesn’t open

Sign Transaction (Request)
- failed -- A response parsing error has occurred

Sign Transaction (v0)
- failed -- A response parsing error has occurred

Sign Transaction (v0) (Request)
- A response parsing error has occurred

Sign Transaction (v0 + lookup table)
- Simulation Works 
- Buttons flipped, but no issues show 

Sign All Transactions (multiple)
- failed -- A response parsing error has occurred

Sign All Transactions (Invalid blockhash)
- Doesn’t open 
Sign All Transactions (multiple) (Request)
- failed -- A response parsing error has occurred

Sign All Transactions (multiple) (v0)
- failed -- A response parsing error has occurred: 

Sign All Transactions (multiple) (v0) (Request)
- Simulation Works
- Confirm/reject swapped - no issues shown

Sign All Transactions (multiple) (v0 + lookup table)
- Simulation Works
- Confirm/reject swapped - no issues shown

Sign All Transactions (single)
- failed -- A response parsing error has occurred

Sign All Transactions (single) (Request)
- failed -- A response parsing error has occurred

Sign Message
- Sign panel opens

Sign Message (Request)
- Sign panel opens

Sign Message (Hex display)
- Sign panel opens

Sign Message (Hex display + Request
- Sign panel opens


Brave Swap 
- Works

JUP Swap 
- Works - Buttons swapped though 
    - issue shown
    - Pressing reject doesn’t close

Brave SOL Send
- Worked

Brave SPL (fungible) Send
- Works

Brave SPL (non-fungible) Send
- Works

Brave EVM Eth Send
- Works

Brave EVM ERC-20 Token Send
- Works

Brave EVM NFT Send
- Works

Brave EVM Deploy contract (MM test Dapp)
- -- Invalid txObject data. Please refer to the documentation for a full request body specification
    - Maybe due to TO address being “0x”, should be empty

Malicious set approval for all
- A response parsing error has occurred

Malicious ETH Send
- Works


UI Bugs

- Sign risk cancel doesn’t close
- Confirm reject simulation button padding
-

**Comment by josheleonard** [comment]
UI bugs fixed

Confirm reject simulation button padding
issues not shown on sol simulated sign panel, buttons swapped



Sign risk cancel will close the panel, but not update if loaded into brave://wallet-panel.top-chrome for now

**Comment by josheleonard** [comment]
Added simulation skip whenever "safer-sign" can be used

**Comment by josheleonard** [comment]
New broken tx list:

**SVM** 
Sign and Send Transaction (Legacy)
- failed -- A response parsing error has occurred:

Sign and Send Transaction (v0)
- failed -- A response parsing error has occurred:

Sign and Send Transaction (Request)
- failed -- A response parsing error has occurred:

Sign and Send SPL Token Transaction
- failed -- A response parsing error has occurred:

Sign Transaction
- failed -- A response parsing error has occurred

Sign Transaction (Request)
- failed -- A response parsing error has occurred

Sign Transaction (v0)
- failed -- A response parsing error has occurred

Sign Transaction (v0) (Request)
- failed -- A response parsing error has occurred

Sign All Transactions (multiple)
- failed -- A response parsing error has occurred

Sign All Transactions (multiple) (Request)
- failed -- A response parsing error has occurred

Sign All Transactions (multiple) (v0)
- failed -- A response parsing error has occurred:

Sign All Transactions (multiple) (v0) (Request)
- Normal Sign panel opens

Sign All Transactions (single)
- failed -- A response parsing error has occurred

Sign All Transactions (single) (Request)
- failed -- A response parsing error has occurred

Sign Message
- Normal Sign panel opens

Sign Message (Request)
- Normal Sign panel opens

Sign Message (Hex display)
- Normal Sign panel opens

Sign Message (Hex display + Request
- Normal Sign panel opens

**EVM**
Brave EVM Deploy contract (MM test Dapp)
- Invalid txObject data. Please refer to the documentation for a full request body specification
- Maybe due to TO address being “0x”, should be empty

Malicious set approval for all
- A response parsing error has occurred

**Comment by josheleonard** [comment]
New test results:
### SVM
| Action | Status |
|--------|--------|
| Sign and Send Transaction (Legacy) | **_Parsing Error_** |
| Sign and Send Transaction (v0) | **_Parsing Error_** |
| Sign and Send Transaction (v0 + lookup table) (devnet only) | Success |
| Sign and Send Transaction (Request) | **_Parsing Error_** |
| Sign and Send SPL Token Transaction | **_Parsing Error_** |
| Sign Transaction | **_Parsing Error_**  |
| Sign Transaction (Request) | **_Parsing Error_** |
| Sign Transaction (v0) | **_Parsing Error_** |
| Sign Transaction (v0) (Request) | **_Parsing Error_** |
| Sign Transaction (v0 + lookup table) | Success |
| Sign All Transactions (multiple) | **_Parsing Error_** |
| Sign All Transactions (multiple) (Request) | **_Parsing Error_** |
| Sign All Transactions (multiple) (v0) | **_Parsing Error_** |
| Sign All Transactions (multiple) (v0) (Request) | **_Parsing Error_** |
| Sign All Transactions (multiple) (v0 + lookup table) | Success |
| Sign All Transactions (single) | **_Parsing Error_** |
| Sign All Transactions (single) (Request) | **_Parsing Error_**  |
| Sign Message | Not supported |
| Sign Message (Request) | Not supported |
| Sign Message (Hex display) | Not supported |
| Sign Message (Hex display + Request | Not supported |

### EVM

- [ ] Brave EVM Deploy contract (MM test Dapp)
- [ ] Malicious set approval for all

**Comment by onyb** [comment]
**Update:** use https://xpj8pg.csb.app for executing the Solana provider tests.

**Comment by onyb** [comment]
All the remaining Solana cases are actually self-transfers, hence the transactions do not have any state change. This is no longer considered an error in the backend (see https://github.com/brave/brave-core/pull/21796/commits/0799a0935e689637b246505304bfd3e708646874) as they are valid transactions. The frontend should appropriately indicate that there are no state changes.
