### ISSUE TITLE
Add support for Bitcoin Ordinals

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#34771]
Probably just autodiscovery + image fetching APIs to start
```[tasklist]
### Tasks
- [ ] [Show ordinals warning only for transactions spending ordinals](https://github.com/brave/brave-browser/issues/37249)
- [ ] Support spending utxo with ordinals, but return owning sats back as change
- [ ] Present owned ordinals to user
- [ ] Support BRC-20 tokens
```

**Comment by lukemulks** [comment]
This will be fantastic. Udi has offered support, if needed, but looks like you all have what you need.
