### ISSUE TITLE
Enhance PIP UI 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35147]
https://www.figma.com/file/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?type=design&node-id=1%3A29&mode=design&t=qd8wPCr4slkQFIUU-1

* PIP UI should be restyled
* We need more UI component, such as slider and timestamp

VideoOverlayWindow(Views) is the important class to represent the UI

Current state:
<img width="260" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/af0812db-ecce-4872-bd7d-0a51acc49be0">

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/35259
- [ ] https://github.com/brave/brave-browser/issues/35263
- [ ] https://github.com/brave/brave-browser/issues/15416
- [ ] https://github.com/brave/brave-browser/issues/35409
- [ ] https://github.com/brave/brave-browser/issues/31657
```

**Comment by dpthegrey** [comment]
related to PIP enhancements https://github.com/brave/brave-browser/issues/31657

**Comment by sangwoo108** [comment]
We have many PIP types and controls could be different

### Slide https://googlechrome.github.io/samples/media-session/slides.html
<img width="534" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/927eee94-267c-4afd-885e-00a84e1aabcb">

###

**Comment by sangwoo108** [comment]
We have different types of picture-in-picture other than 'video', and each of them has their own controls

### Video conference
<img width="320" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/59354655-12f1-4309-8afd-fd7345e6a2db">

### Slide
<img width="491" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/6406ddab-32dc-4b2f-88a4-9b3c85dd4d87">

**Comment by dpthegrey** [comment]
Hi @sangwoo108  sharing this for reference read about Document Picture-in-Picture API here: 
https://developer.chrome.com/docs/web-platform/document-picture-in-picture/  
it shows video controls in PIP mode and even a pomodoro in PIP mode. Is it possible on browser level or websites have to use it?
![image](https://github.com/brave/brave-browser/assets/49444980/54213219-ee6f-4590-8158-661e76b61fe3)
![image](https://github.com/brave/brave-browser/assets/49444980/f07e1b13-6a69-4f07-a4cb-1134bda8e292)

**Comment by sangwoo108** [comment]
Hi @dpthegrey ! Thanks for sharing. I believe both browser side and web dev side effort is required to use the Document-picutre-in-picture. But the browser side implementation is already enabled by default (brave://flags/#document-picture-in-picture-api) on Brave Nightly version. So when you visit sites implementing Document pip, it should work You can try the pomodoro example with Brave https://lazy-guy.github.io/tomodoro/index.html

**Comment by jenningsb2** [comment]
Hey @sangwoo108 —will this release allow for automatic PiP to be enabled?

https://developer.chrome.com/blog/automatic-picture-in-picture

One of the main features I enjoyed with the [Arc browser](https://arc.net/integrations/google-meet) was the ability to navigate to new tabs and have PiP automatically invoked for both Google Meet and YouTube.

**Comment by sangwoo108** [comment]
Hi @jenningsb2 . I think that should work when you enable the `brave://flags/#media-session-enter-picture-in-picture` flag.

**Comment by jenningsb2** [comment]
@sangwoo108 —got it! Thanks for the response. I am a heavy PiP user, so I am glad to see that this feature is receiving more attention!
