### ISSUE TITLE
[Speedreader] Add debug view

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#35201]
It would be very useful to have some kind of debugging view of the speedreaded page.

```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/35324
- [ ] It should show the scores of the elements and why this score is given
- [ ] Is should show what elements were processed
- [ ] It should show candidates of top elements
```
