### ISSUE TITLE
Seeker on PIP window enhancement

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35409]
```[tasklist]
### Tasks
- [x] The seeker bar can't be used because PiP resizing action will be triggered on Windows
- [x] Seeker doesn't scrub on Windows
- [x] When video is paused in Youtube, and you go PiP, it starts with 00:00 and it is only when you click play when it goes to the correct position
- [x] it also shows weird timestamp in livestreams like Twitch, so don't know if this can be improved
- [x] Keyboard arrows didn't scrub videos either through the PiP
```
