### ISSUE TITLE
Add external link icon "Go to my {{ provider }} account" in Rewards panel white menu and open in new tab

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35620]
```[tasklist]
### Tasks
- [ ] Desktop Rewards panel, add icon and open in new tab
- [ ] Desktop brave://rewards page, add icon and open in new tab
- [ ] Android brave://rewards page, add icon and open in new tab
```
![image](https://github.com/brave/brave-browser/assets/11497541/6d963059-0c42-466e-bb11-e57b90c1383d)

**Comment by Miyayes** [comment]
Closing as duplicate.
