### ISSUE TITLE
[Leo] Tracking issue for context limit behaviors

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#35733]
Tracking the issues for improving issues around various context limit behaviors

**Back-end:**

- [x] https://github.com/brave/aichat/issues/11
- [x] https://github.com/brave/aichat/issues/128 
- [x] https://github.com/brave/aichat/issues/126

**Page context:**

- [x] https://github.com/brave/brave-browser/issues/34131
- [x] https://github.com/brave/brave-browser/issues/36649
- [ ] https://github.com/brave/brave-browser/issues/34701
- [x] https://github.com/brave/brave-browser/issues/32346
- [x] https://github.com/brave/brave-core/pull/19813
- [x] https://github.com/brave/brave-browser/issues/29608
- [ ] https://github.com/brave/brave-browser/issues/36179
- [x] https://github.com/brave/brave-browser/issues/36175

**User input:**

- [x] https://github.com/brave/brave-browser/issues/30233
- [x] https://github.com/brave/brave-browser/issues/33006
- [ ] https://github.com/brave/brave-browser/issues/33880
- [ ] https://github.com/brave/brave-browser/issues/34322
- [x] https://github.com/brave/aichat/issues/19
- [x] https://github.com/brave/brave-browser/issues/36138
- [x] https://github.com/brave/brave-browser/issues/36144

More information in the doc https://docs.google.com/document/d/1ThBz6-HB_UufCcD3732VLyvaX7Co7_SYm9AnfM7CdtE/edit

**Comment by mattmcalister** [comment]
As discussed last week, I'm closing this tracking issue as most of it is done and what's remaining will be reevaluated along with other context-related issues after the latest upgrades land.
