### ISSUE TITLE
[ads] New tab takeover iOS video ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#36435]
**Q1/2024**

**POC**
- [x] [[ads] Investigate NTT video ad file sizes for low, medium and high quality videos](https://github.com/brave/brave-browser/issues/36477)
- [x] [[ads] Implement POC playback of NTT video ads](https://github.com/brave/brave-browser/issues/36481)

**MVP targeting 1.66.x**
- [x] [[ads] Implement playback of NTT video ads basing on updated design](https://github.com/brave/brave-browser/issues/36621)
- [x] [[ads] Deliver compressed NTT video ad in component updater package](https://github.com/brave/brave-browser/issues/36479)
- [x] [[ads] Autoplay long form NTT video ad muted for n seconds](https://github.com/brave/brave-browser/issues/36487)
- [x] [[ads] Implement play/pause buttons for long form NTT video ads](https://github.com/brave/brave-browser/issues/36482)
- [x] [[ads] Support short form NTT video playback](https://github.com/brave/brave-browser/issues/36709)
- [x] [[ads] Transition to landing page when a user clicks on an NTT video ads CTA button](https://github.com/brave/brave-browser/issues/36488)
- [x] [[ads] Fadeout/fadein stats on NTP when NTT video is started playing](https://github.com/brave/brave-browser/issues/37104)
- [x] [[ads] Add support for fit-to-fill mode for NTT video](https://github.com/brave/brave-browser/issues/37105)
- [x] [[ads] Do not show NTT video for iPhone in landscape mode](https://github.com/brave/brave-browser/issues/37106) 
- [x] Implement Brave Rewards metrics:
    - [x] [[ads] Implement NTT video impressions metrics for Rewards users](https://github.com/brave/brave-browser/issues/36490) 
    - [x] [[ads] Implement NTT video clicks metrics for Rewards users](https://github.com/brave/brave-browser/issues/36491) 
    - [x] [[ads] Implement NTT video visits on landing page metrics for Rewards users](https://github.com/brave/brave-browser/issues/36492)
    - [x] [[ads] Implement NTT video metrics for the length of time the ad is viewed for Rewards users](https://github.com/brave/brave-browser/issues/36493)
    - [x] [[ads] Implement NTT video metrics for number of clicks on play button for Rewards users](https://github.com/brave/brave-browser/issues/36715)
- [x] Implement non-Brave Rewards metrics:
    - [x] [[ads] Implement NTT video impressions for non-Rewards users](https://github.com/brave/brave-browser/issues/36494)
    - [x] [[ads] Implement NTT video clicks metrics for non-Rewards users](https://github.com/brave/brave-browser/issues/36495)
    - [x] [[ads] Implement NTT video visits on landing page metrics for non-Rewards users](https://github.com/brave/brave-browser/issues/36496)
    - [x] [[ads] Implement NTT video metrics for the length of time the ad is viewed for non-Rewards users](https://github.com/brave/brave-browser/issues/36497)
    - [x] [[ads] Implement NTT video metrics for number of clicks on play button for non-Rewards users](https://github.com/brave/brave-browser/issues/36716)
- [x] [[ads] Configure NTT video blank space color when viewing video in letterbox/pillar-box modes](https://github.com/brave/brave-browser/issues/36610)
- [x] [[ads] Tapping on the video during 6 seconds autplay starts video NTT playback](https://github.com/brave/brave-browser/issues/37273)

PR: https://github.com/brave/brave-core/pull/22701

**Backlog:**
- [ ] [[ads] NTT video background blinks when showing after last tab is closed](https://github.com/brave/brave-browser/issues/37313)
- [ ] [[ads] Implement NTT video metrics tests](https://github.com/brave/brave-browser/issues/37393)

--

https://github.com/brave/brave-browser/projects/26#column-19787507

**Comment by kjozwiak** [comment]
The above requires `1.66.81` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on `iPhone` running `iOS 17.3.1` using version `1.66.80`

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running version `7.4.1 ` using version `1.66.104`

- Spot checked test cases 1-8 on iPad and ensured behavior is similar to iPhone. 

**Test Case 9:**

- Ensured Video NTT autoplay is enabled.
- Ensured changing device to landscape orientation does not interrupt video play and no UI issues are observed.
- Ensured CTA logo, Play button, Favorites, Stats, Brave News are visible when autoplay finishes.
- Ensured tapping on the play button start full screen playback. 
  - Video is played from the beginning.
  - Video is played with sound.
  - Cancel button appears in top right corner.
  
 _UI_

Example | Example | Example | Example
-|-|-|-
![IMG_1371](https://github.com/brave/brave-browser/assets/17885425/572c8617-dd3d-44fd-aaa5-a8f307ca56d3) | ![IMG_1372](https://github.com/brave/brave-browser/assets/17885425/cd7925cc-07aa-4ab0-9aeb-b12a151b12fb) | ![IMG_1365](https://github.com/brave/brave-browser/assets/17885425/f9cac3a8-987d-4b22-a33e-0da1493baadc) | ![IMG_1374](https://github.com/brave/brave-browser/assets/17885425/aa571b7d-94fd-4ded-84ee-f8dd3ffda168)

_Attribution / Rewards_

Open Video NTT

![Screenshot 2024-05-09 at 5 59 44 PM](https://github.com/brave/brave-browser/assets/17885425/32a2cad2-4bd1-4146-b2d0-71c6a1a25421)

Playback 

![Screenshot 2024-05-09 at 6 00 22 PM](https://github.com/brave/brave-browser/assets/17885425/46b01eea-8ede-4061-af8d-d97b302e3405)

Playback finishes

![Screenshot 2024-05-09 at 6 01 17 PM](https://github.com/brave/brave-browser/assets/17885425/5eee7d4a-fc2c-4686-aeb3-0953a1a95fab)

Tap on Video Sponsor logo

![Screenshot 2024-05-09 at 6 06 06 PM](https://github.com/brave/brave-browser/assets/17885425/1863b710-8e65-4a06-8678-20a0fa4b460d)

Landed event after 10 secs on sponsor homepage

![Screenshot 2024-05-09 at 6 06 18 PM](https://github.com/brave/brave-browser/assets/17885425/81133496-1f93-41a5-bbdc-9fce8092f890)

**Case: Disabling background images/sponsored images**

- Ensured Sponsored images and video NTT is not shown when disabling `Background Images` in `New Tab Page` settings
- Ensured changing `Image Type` to `Default Images` will not show any sponsored images on NTP.

Example | Example | Example | Example
-|-|-|-
![IMG_1375](https://github.com/brave/brave-browser/assets/17885425/eddcdb52-2867-471f-8c1e-18b8fcfbf565)
![IMG_1376](https://github.com/brave/brave-browser/assets/17885425/1a062d63-5274-42a4-86da-60a874a3dc08)
![IMG_1377](https://github.com/brave/brave-browser/assets/17885425/c11a069b-d709-4b65-8b8d-44837dd21a8a)
![IMG_1378](https://github.com/brave/brave-browser/assets/17885425/2a0c3649-c8f4-45e7-b46e-b37be9bc7450)
