### ISSUE TITLE
Leo - UI updates Feb2024

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36448]
```[tasklist]
### Header
- [x] Changed the header text style to match new branding guidelines https://github.com/brave/brave-browser/issues/36916
- [x] Change name from Leo to **Leo AI** on iOS https://github.com/brave/brave-browser/issues/36917
- [x] Added a "Close" button on Desktop to close the panel with a divider on the left of it https://github.com/brave/brave-browser/issues/36202
```

```[tasklist]
### Contextual indicator / Text input
- [ ] Hide contextual indicator when input focus is lost (Desktop / Android) https://github.com/brave/brave-browser/issues/36920
- [ ] Hide contextual indicator when input focus is lost (iOS) https://github.com/brave/brave-browser/issues/36921
- [x] Slash command tools (This one needs to be broken up into the corresponding issues) https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=864:19162&mode=design&t=xERKWbOP5SnDNod0-1
```

```[tasklist]
### Conversations
- [ ] Conversation divider if the user switches models in the middle of a conversation (Desktop / Android) https://github.com/brave/brave-browser/issues/36922
- [ ] Conversation divider if the user switches models in the middle of a conversation (iOS) https://github.com/brave/brave-browser/issues/36923
- [ ] Limit the maximum width of the content in Leo's panel https://github.com/brave/brave-browser/issues/35102
- [ ] https://github.com/brave/brave-browser/issues/37234
- [ ] https://github.com/brave/brave-browser/issues/37233
- [x] Remove color banding in conversations https://github.com/brave/brave-browser/issues/37504
```

**Comment by aguscruiz** [comment]
Sure. I'll check the ones that are done and add comments here if necessary

**Comment by aguscruiz** [comment]
@mattmcalister marked as done the ones I've seen.

This one 
https://github.com/brave/brave-browser/issues/36917 appears done in desktop/android but not yet on iOS. At least on the latest nightly I have

**Comment by mattmcalister** [comment]
@Brandon-T here's a little one for you: https://github.com/brave/brave-browser/issues/36917. it's only a `P4` but would be good to keep some momentum on these polish issues.

The other two iOS-specific issues from the list above (https://github.com/brave/brave-browser/issues/37234 and https://github.com/brave/brave-browser/issues/36919) are lower priority at the moment.

**Comment by mattmcalister** [comment]
we're using roadmap issues as issue trackers now, so I'm going to close this one as stale
