### ISSUE TITLE
Pending verification's/Release Notes from `1.63.x` milestones (includes all `iOS` issues)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36538]
Current list of issues that have been fixed/resolved via [`1.63.x - Release`](https://github.com/brave/brave-browser/milestone/450), [`1.63.x - Release #3`](https://github.com/brave/brave-browser/milestone/468), [`1.63.x - Release #4`](https://github.com/brave/brave-browser/milestone/469) & [`1.63.x - Release #5`](https://github.com/brave/brave-browser/milestone/471) haven't been verified by QA and should be completed before `1.63.x` goes out on `iOS`:

* [x] Add daily/monthly usage ping P3A metrics for iOS #36177
* [x] Remove NFT tab from Filecoin account details view #36428
* [x] Connected Dapps text has extra padding #36429
* [x] Transaction Details not updating transaction status automatically #36468
* [x] Sharesheet menu is broken, Copy Clean Link and Report a Broken Site can't be added to the Favorites #36506
* [x] Add new UD domains #36131
* [x] Implement Brave Leo on iOS #36585
* [x] [iOS] - Leo Design Changes 1.63.x #36596
* [x] Crash when selecting token to send #36431
* [x] Issues with settings menu for Leo #36650
* [x] Use production url on release channel for Manage Subscriptions (active credentials) #36653
* [x] Menu cut off when opened on iPad #36656
* [x] [Leo] Regenerate function is working only towards the last query #36659
* [x] Error being returned when sending feedback for Leo responses (rating) #36652
* [x] Add 1.63 translations #36723
* [x] Add Brave Leo deep link #36800
* [x] Upgrade Now button is only clickable when tapping on the text/string (entire button should be clickable) #36787
* [x] clicking on Restore causes infinite spinner when there's no subscription to restore #36788
* [x] Sending feedback form for Leo posts fails [bad request] #36780
* [x] upgrading/purchasing Leo doesn't remove the Rate Limit Reached paywall #36824
* [x] default modal for new conversations not respecting user choice and always reverting to Mixtral #36816
* [x] [Follow up to #36723] Shape answers based on the page's contents doesn't fit the screen in Portrait Mode #36856
* [x] Need to update font's color for the Add Feedback when device is in Dark Mode #36857 
* [x] Default modal for new conversations reverting to Mixtral after restarting Brave - Follow up to #36816 #36886
* [x] Leo premium status not shown correctly for IAP [sandbox] #36692

Current list of issues that are labelled as `QA/No` but landed in various `1.63.x` milestones via [`1.63.x - Release`](https://github.com/brave/brave-browser/milestone/450), [`1.63.x - Release #3`](https://github.com/brave/brave-browser/milestone/468), [`1.63.x - Release #4`](https://github.com/brave/brave-browser/milestone/469) & [`1.63.x - Release #5`](https://github.com/brave/brave-browser/milestone/471):

* Crash from adblock rules with $from option #36275 - https://github.com/brave/brave-browser/issues/36275
* Expose BraveWalletP3A to iOS #35703
* [iOS] - Crash on Prefs registration for AIChat #35050
* Separate testing build & running unit tests in fastlane #36391
* Fix flakey UserAssetStoreTests.testUpdate unit test #36268
* Buy/Send/Swap not opening from Asset Details #36266
* Update JitsiSDK to 8.6.3 #36353
* Problem ASA Custom Onboarding Linked Screen #36326
* Url bar falsely showing insecure state in 1.62+ #36024
* Brave IOS: Can not access Synology DSM website, OpenWRT Luci Website, Portainer website and other sites with private ssl certs #36688
* iOS unit tests sometimes fail on CI citing an xctest failure #36536
* Brave Leo Duplicated translations keys #36726
* Audit finding: https://github.com/advisories/GHSA-cxjh-pqwp-8mfp #36809

Current list of issues that were `release-notes/include` via [`1.63.x - Release`](https://github.com/brave/brave-browser/milestone/450), [`1.63.x - Release #3`](https://github.com/brave/brave-browser/milestone/468), [`1.63.x - Release #4`](https://github.com/brave/brave-browser/milestone/469) & [`1.63.x - Release #5`](https://github.com/brave/brave-browser/milestone/471): and should be added into the release notes for the `iOS 1.63.x` release:

**`Quick note:`** some issues that would have been labelled as `release-notes/exclude` are labelled as `release-notes/exclude` due to those issues going out via `1.62.1` or `1.62.2` and will be mentioned via https://github.com/brave/brave-ios/blob/development/CHANGELOG.md.

* Transaction Details not updating transaction status automatically #36468
* Implement Brave Leo on iOS #36585

**Comment by kjozwiak** [comment]
Closing the above as QA is basically done with `1.63.x`. The above was used a reference to track the various issues that landed throughout the `1.63.x` milestones that were for `iOS`.
