### ISSUE TITLE
Wallet: FEVM transaction support

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#36636]
```[tasklist]
### Tasks
- [ ] Translate FEVM addresses to f410 addresses in send
- [ ] Support sending f1 to typed f4 addresses
- [ ] Support sending from f4 to typed f1 addresses
- [ ] Transaction confirmation/summary/details display correct f1 and f4 addresses
```
