### ISSUE TITLE
Pending verification's/Release Notes from `1.64.x` milestones

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36959]
Current list of issues that have been fixed/resolved via [`1.64.x - Release`](https://github.com/brave/brave-browser/milestone/459) and haven't been verified by QA and should be completed before `1.64.x` goes out on `iOS`:

* [x] Add delta balance percentage change on wallet portfolio page #36772
* [x] Cache token balances #35986
* [x] Add brave-core debounce layers for iOS #33275
* [x] [ads] Unify iOS kShouldAlwaysRunBraveAdsServiceFeature #35520
* [x] [iOS] Brave is crashing when opening View all version info. while in Landscape mode and then switching to Portrait mode #36098
* [x] Add Catalan language to the iOS app #36261
* [x] Move Transaction Sent P3A metric reporting into core #36156
* [x] Upgrade from Chromium 123.0.6312.46 to Chromium 123.0.6312.58 #36938
* [x] iOS builds use "unknown" channel even when KSChannelID is embedded #36901
* [x] Do not show decimal values for NFT in send screen #36771
* [x] Cursors jumps back to first word input when space is typed in restore screen #36775
* [x] Tab bar interaction is broken after it becomes visible #36591
* [x] YouTube full screen black screen after unlocking the phone #36064
* [x] Fix Add to Metamask error on Coingecko #36797
* [x] [Follow up to #36261][L10n] Some strings are not translated to Catalan language #37000
* [x] Add Account not prompted if account exists for same coin type on other keyring #37114
* [x] Remove Swap from Filecoin Account details view #37167
* [x] Leo search overlay entry point should be at the bottom of the list #37263
* [x] Wallet: Asset Deposit #35988
* [x] Deposit can shown incorrect accounts for token #37123
* [x] [iOS] - Export Skus Internals #37222
* [x] Expose brave://flags on iOS #37149
* [x] [iOS] - Expose brave://skus-internals #37315
* [x] [Follow-up] URL bar falsely showing insecure state in 1.62+ #36951
* [x] Add access to developer menus & logs in release & beta channels #36961

Current list of issues that were `release-notes/include` via [`1.64.x - Release`](https://github.com/brave/brave-browser/milestone/459) and should be added into the release notes for the `iOS 1.64.x` release:

* Do not show decimal values for NFT in send screen #36771
* YouTube full screen black screen after unlocking the phone #36064
* [iOS] Brave is crashing when opening View all version info. while in Landscape mode and then switching to Portrait mode #36098
* Upgrade from Chromium 123.0.6312.46 to Chromium 123.0.6312.58 #36938
