### ISSUE TITLE
Split view MVP tasks

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36986]
https://www.figma.com/file/uiDbQ0ocpqiraWEeQVUyId/Tabs---Vertical-%2F-Split-%2F-Sidebar?type=design&node-id=35%3A6412&mode=dev

![image](https://github.com/brave/brave-browser/assets/5474642/356dd567-342d-428c-8f61-311fa690d251)

```[tasklist]
### Tasks
- [x] Make flag to enable split view
- [x] Tab group should be considered
- [x] Drag and drop should work for both tabs.
- [ ] https://github.com/brave/brave-browser/issues/37088
- [x] Make context menu item to tile two tabs in split view / unset tiled views
- [x] BrowserView::GetAccessiblePane
- [ ] https://github.com/brave/brave-browser/issues/37231
- [x] https://github.com/brave/brave-browser/issues/37274
- [ ] https://github.com/brave/brave-browser/issues/37539
- [ ] https://github.com/brave/brave-browser/issues/37413
- [x] Open link test
- [ ] https://github.com/brave/brave-browser/issues/37326
- [ ] https://github.com/brave/brave-browser/issues/37328
- [x] https://github.com/brave/brave-browser/issues/37408
- [ ] https://github.com/brave/brave-browser/issues/37576
- [ ] https://github.com/brave/brave-browser/issues/37577
- [ ] https://github.com/brave/brave-browser/issues/37677
- [ ] https://github.com/brave/brave-browser/issues/37717
- [ ] https://github.com/brave/brave-browser/issues/37678
- [ ] https://github.com/brave/brave-browser/issues/37712
- [ ] https://github.com/brave/brave-browser/issues/37761
- [x] Make test for case where tile breaks after moving tabs https://github.com/brave/brave-core/pull/22933#issuecomment-2043481378
- [x] Blank tab behavior - https://github.com/brave/brave-browser/issues/37447#issuecomment-2050309959
- [ ] https://github.com/brave/brave-browser/issues/37803
- [ ] https://github.com/brave/brave-browser/issues/37804
- [ ] https://github.com/brave/brave-browser/issues/37850
- [ ] https://github.com/brave/brave-browser/issues/37851
- [ ] https://github.com/brave/brave-browser/issues/37852
- [ ] https://github.com/brave/brave-browser/issues/37919
- [ ] https://github.com/brave/brave-browser/issues/37924
- [ ] https://github.com/brave/brave-browser/issues/38302
- [ ] https://github.com/brave/brave-browser/issues/38356
- [ ] https://github.com/brave/brave-browser/issues/38392
- [ ] https://github.com/brave/brave-browser/issues/38584
- [ ] https://github.com/brave/brave-browser/issues/38656
- [ ] https://github.com/brave/brave-browser/issues/38691
- [ ] https://github.com/brave/brave-browser/issues/38908
- [ ] https://github.com/brave/brave-browser/issues/38903
- [ ] https://github.com/brave/brave-browser/issues/38710
- [ ] https://github.com/brave/brave-browser/issues/39004
- [ ] https://github.com/brave/brave-browser/issues/38740
- [ ] https://github.com/brave/brave-browser/issues/39006
- [ ] https://github.com/brave/brave-browser/issues/39598
- [ ] https://github.com/brave/brave-browser/issues/39682
- [ ] When you click to activate a tab in split view, the window onfocus event is always called twice with different event.timeStamp - this might be because we swaps web views
- [ ] Permission dialog pops up when the tab is not active in split view
```

```[tasklist]
### TBD / Follow-ups
- [ ] location bar
- [x] Focuses wrong ui component  - https://github.com/brave/brave-browser/issues/37447#issuecomment-2050309959 - may not be problem
- [ ] Video fullscreen doesn't work well
- [ ] https://github.com/brave/brave-browser/issues/40062
- [ ] 3+ split view
- [ ] Need menu button in the gap between split views
```

**Comment by bridiver** [comment]
Similar to the follow up issue we should include more content here rather than just linking to Figma. This is currently completely opaque to anyone outside of Brave and I don't even know if everyone inside of Brave already has a Figma login or not.

**Comment by sangwoo108** [comment]
I intentionally left figma link just in case. Asked @aguscruiz if it's okay to open our design public.

**Comment by aguscruiz** [comment]
Hi. This would probably be solved if we just add more screenshots to issues, right? 

I try to add them sparingly because the problem with them is that they get outdated as soon as I make a tiny change. That's why I prefer figma links.

Regarding Figma access, everyone who has a @brave.com email has access to all of our Figma environment, so that shouldn't be a problem.

**Comment by TEMP-ad** [comment]
Just throwing some general feedback of Split View progress.

1. ${{\color{Orange}\huge{\text{  Add Menu button to split view separator 38584\}}}}\$: In Vertical tabs, when you enable Split view, and then you you expand or minimize it the VT, the button doesn't follow the split line, just resizing a little will fix it though. 
![image](https://github.com/brave/brave-browser/assets/156715894/dc2810db-0c92-40e6-867a-9af9bc1d9ae4)
2. ${{\color{green}\huge{\text{ Resized amount for split view tile should be kept per tile 38392\}}}}\$: This is still keeping the size of the split view **per window**, so for example, you enable Split view and change the size and then you split other tabs in the same window, it will show the same size, but not in a new window.
  I don't mind about the size being per window, because I think it would be good to have a have a 'reset' button to quickly reset everything to be 50/50 or have a way to specify it.
3. ${{\color{green}\huge{\text{ Draw border for contents web views in split view mode 37804 \}}}}\$  this one looks nice, but doesn't let activate or move tabs by using the top of the tabs, like other normal tabs, so going from normal to split tabs can be weird.
4. ${{\color{red}\huge{\text{ Add "Swap Split view position" 38656\}}}}\$: the context menu "Swap tab positions" can be used when you select a split tab and a non-split tab(s), which causes Browser to crash. 
5. ${{\color{BrickRed}\huge{\text{ alleviate flickering when switching tabs with split view 38691\}}}}\$: seems better but still happens sometimes, especially Vertical tabs, tested two twitch streams in a clean profile and it did a tiny flickering in VT but not in HT.
  I ran some tests, and the biggest issue is Custom Adblock rules too, for example, Outlook causes sometimes long black seconds while trying to redraw/layout the page in my main profile, and that's because I have a simple custom rule `outlook.live.com###MainModule + div`, without it, barely or no flickering but with it after my email is loaded, but with it, it can do even a 500ms long black screen. So there is something going on between Custom rules and the way it does it in split view.
  BTW, I modified the default list `iodkpdagapdfkphljnddpjlldadblomo` and added the same custom rule and the problem is not present BTW, so that's why I am 100% sure it is about the adblocking and what it does internally about the two engines it has and the merging and all that.

**Comment by sangwoo108** [comment]
Hi @TEMP-ad , Thanks for reporting.

As for the `#3` one, I guess you mean the background around the tabs when they're in a split view, not the border around the web views. Let me check if we can do something.

And `#5` would be tricky to tell what's going on. As far as I can tell, the long loading black screen with custom rule could be due to renderer or GPU part. If that's the case, it'd be hard to fix it perfectly.

**Comment by TEMP-ad** [comment]
tabn@sangwoo108 yeah, since you added the background around the split views, it is not possible to click and go to the tabs or move the split view, it will move the window, so it is inconsistent with how the other tabs work.

I also got a tiny little issue that I forgot to mention, it has to do with `Cycle through the most recently used tabs with Ctrl-Tab`; it doesn't work properly with Split view tabs, especially across different split view tabs.

https://github.com/brave/brave-browser/assets/156715894/229b8545-a539-4291-a52b-a7684db6c771

It's hard to tell what the video is about, but first I click on tab 2nd and then 3rd tab (so different split views) and then you see it goes to the 4th tab, now I did the opposite from 3 to 2, and it goes to the 1st tab.

Then it's hard to tell what I do, because you can't see when I press ctrl+tab, but it does what it is suppose to do but I have to press ctrl+tab twice, to go tom 4th tab to 2nd tab, then I have to press twice ctrl+tab for it to go back to the 4th tab.

And same from 1st to 3rd tab. and then trying to go back to the 1st tab.

When it comes to split view tabs vs nonsplit view tabs, 
And clicking on a non split view tab, 5th tab, then I click on the 4th tab, and it will require require also two ctrl+tab to do the job. 

And then the last part of the video is me showing how I click on the 5th tab (non split view) and then 3rd tab, but then it jumps to the 4th tab before going to the 5th tab which is the 'recent one' so basically if you go from one non split tab and click on the left tab of a split view it will go through both tabs when ctrl+tab, but if you click on the left tab of the split it will require two ctrl+tab to properly cycle with the recent tab.

It is a tiny little miss behavior but forgot to report it, I am sure it will make more sense when you enable it (in brave://settings/braveContent)

**Comment by TEMP-ad** [comment]
Thanks for the fixes! Sorry if I reported even the smallest flickering, but everything is working great now with `Reduce split view flickering using SetFastResize()` Vertical and Horizontal tabs, switching from split to non-split tabs, and since I use 128391832 custom rules in every page, seems like that's not an issue anymore and there is no more flickering and/or seeing DOM being recalculated on switching tabs, everything feels smooth now.

Amazing superpowers work as usual Split views is a great feature for Brave to have 👍. Let's hope I won't bother anytime soon 😁

**Comment by sangwoo108** [comment]
@TEMP-ad your report never bothered. I really appreciate your reporting. It makes features a way better!

**Comment by TEMP-ad** [comment]
@sangwoo108

Thanks for the Horizontal Split view, it is a nice addition. It has a tiny little issue: the web content is not being re-layout when you switch modes, when it switches mode, the content will stay just like Vertical split and leave a blank space on the right of the split view. It will only fill the web content and move things around, until you click on the content (not the blank space) or you resize the split window or the window.

1.69.38 Chromium: 126.0.6478.114 (Official Build) nightly (64-bit)  - Windows 11 Version 23H2 (Build 22631.3737)

https://github.com/brave/brave-browser/assets/156715894/a87c3ee1-ff09-41d7-9992-2b3460b8d786

**Comment by sangwoo108** [comment]
oh, thanks. I missed something

**Comment by bridiver** [comment]
This feature seems problematic to me because the urlbar can only reflect one of them. I also think this is going to create a lot of complexity and be subject to a lot of security and other issues. I don't think the complexity and potential issues surrounding this justify a very niche feature.

**Comment by bridiver** [comment]
Sorry I'm finding this so late in the process after so much work has been done, but I feel very strongly that this should not be released. Sharing two webcontents in one tab is a recipe for problems.

**Comment by sangwoo108** [comment]
@bridiver We have security review going here https://github.com/brave/reviews/issues/1646

**Comment by bridiver** [comment]
I have already found several bugs that I'll post, but I did notice one thing that makes it less concerning which is that it doesn't actually share a single tab in the UI. There are still two separate tabs, but that wasn't obvious when watching the video.

**Comment by bridiver** [comment]
A few things I found in just a few minutes of testing:
1. Open in split view and open dev tools in the right view. It will no longer be highlighted when active
2. Split tabs don't restore as split tabs
3. It's not obvious that the devtools are not shared between the two tabs. When I clicked back and forth I expected the devtools to update to match the active tab. I had to be prompted by @rebron to open the devtools again in the other tab.
4. Open https://permission.site/ on one split and any other site in the other. Trigger a notification and it requires two clicks in the other tab to activate it
5. Screen share permission displays in the middle between the two views

I expect there are a lot more similar issues as there are still a lot of edge cases even without sharing a single tab

**Comment by bridiver** [comment]
Just found another one. Open a third tab next to the split view tabs and select it. Now click and drag (don't let the button up) and it will drag all three. If you do the same thing with a tab that is not adjacent to the split view it will move that tab to be adjacent to the split view

**Comment by bridiver** [comment]
cmd-w closes both tabs instead of just the active tab

**Comment by Saoiray** [comment]
Hey @sangwoo108 and @rebron,

I’ve encountered a couple of issues with Split View that I’m hoping can be addressed:

When initiating Split View, it always starts with a new second tab. Would it be possible to have an option to merge existing tabs into Split View instead of opening a new one each time?

Once in Split View, there’s no way to swap out tabs. For example, if I have Twitter and Reddit open in Split View, but I want to swap Reddit for an open GitHub tab, the only option is to unsplit or navigate directly to GitHub from the Reddit tab (losing whatever I had on the tab that had Reddit). It would be helpful to have the ability to swap tabs in and out from the two Split View locations

**Comment by insilications** [comment]
Will we be able to click links and open them in split view with a shortcut, similar to how we use CTRL + click to open a link in a new tab?

**Comment by jeffgoh** [comment]
With my ultra-wide gaming monitor, I can easily accommodate 4 pane horizontal split. Hardware awaiting the software to catch up.

I'd really like to be able to drag a tab into any split-view pane and have it displayed there - so the pane geometry doesn't change but I can independently change the contents of each pane. Maybe that's just me?

**Comment by rodrigoswz** [comment]
Is this test for now available only on Nightly channel?

**Comment by bridiver** [comment]
> bump
> 
> > Based on [#32071](https://github.com/brave/brave-browser/issues/32071), it seems this has already been implemented for Android but is unfortunately limited to just tablets. Can this limitation please be removed?
> 
> 

You are misunderstanding, that ticket is about split view between two apps. Split view in Brave is not implemented on Android.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 

```
Brave | 1.76.64 Chromium: 133.0.6943.126 (Official Build) beta (64-bit)
-- | --
Revision | 2dc93241b0b0866917c257f1598fe62790bb51d6
OS | Windows 11 Version 24H2 (Build 26100.2894)
```
<details>
<summary>Case 1: Creating a Split View </summary>

A. Tab context menu 
1. Installed 1.76.64
2. launched Brave
3. right clicked to open context menu of a tab
4. confirmed `New Split View` is below Reload in the menu
5. selected `New Split View` option
6. confirmed the selected tab appeared on the left and a new tab page appeared on the right.
7. confirmed Focus (with a border) appeared on the newly created split item.
8. In the tab bar, the items in the split view should come together and look combined and the split in focus should be highlighted.
9. opened a website with few links (time.com) 
10. confirmed it opened on the right screen as it was focused

16. 
step 5 | step 6 | step 7-8 | step 10 | 
----- | ------ | ----
![Image](https://github.com/user-attachments/assets/ff646cba-61c0-455d-83e2-d3e10dd7b233)|![Image](https://github.com/user-attachments/assets/c835a327-5ba6-4ff6-adc4-e6ce46b399d4)|![Image](https://github.com/user-attachments/assets/094e3615-a3e3-448b-b302-4dba68f7c802)|![Image](https://github.com/user-attachments/assets/6b879512-bbe2-4221-82ab-2d02106b089c)

B. Website context menu

1. continue from Case 1
     - Split view is shown with website loaded in the right split view screen
 2. select `Unsplit tabs` from tab context menu 
 3. right clicked to open context menu  
4.  confirmed `Open Link in Split View` is below `Open Link in Private Window with Tor`
5.  Select Open Link in Split View and the linked page should appear to the right of the existing page. Focus should appear on the newly created split item.
6. Select two tabs, and select Open in Split View. Ensure that both tabs are opened in split view of equal size within the window and the right side split is in focus.
7. Select two tabs like above but in three more variations, 1. Pinned tab and a normal tab. 2. Tabs within a group. 3. Tabs that are not adjacent to each other.
8. Repeat above steps in Vertical tab mode. 

![Image](https://github.com/user-attachments/assets/f6e22ca7-0661-4e83-8d83-3ff419a26991)
![Image](https://github.com/user-attachments/assets/a1e8baa4-8be2-4ae1-aeeb-e9eee8b9ecce)

**Comment by btlechowski** [comment]
Verification **PASSED** on

Brave | 1.76.69 Chromium: 134.0.6998.24 (Official Build) beta (64-bit)
-- | --
Revision | 55ecc732897c3be718a5d828607782d3c54a2271
OS | Linux


- Verified the test plan from https://github.com/brave/brave-core/pull/27553


<details>
<summary>Case 1_Creating a Split View_PASSED</summary>

1. Right click on a tab and check that `New Split View` is below `Reload` in the menu. Select `New Split View`. The selected tab should appear on the left and a new tab page should appear on the right. Focus should appear on the newly created split item. In the tab bar, the items in the split view should come together and look combined and the split in focus should be highlighted.

![Image](https://github.com/user-attachments/assets/ac6b2143-9a6f-40f6-8805-37035489d654)|![Image](https://github.com/user-attachments/assets/c381bd34-55c1-4765-a6ac-c384b1aca106)
--|--

</details>

<details>
<summary>Case 2_Creating a Split View_PASSED</summary>

2. Open a web page of your choice that has a few links and right click on a link. Check that `Open Link in Split View` is below `Open Link in Private Window with Tor`. Select `Open Link in Split View` and the linked page should appear to the right of the existing page. Focus should appear on the newly created split item.

![Image](https://github.com/user-attachments/assets/04f9d080-916d-4134-949c-558b98a62b94)|![Image](https://github.com/user-attachments/assets/3c503eb9-78ff-4fd5-913d-c38f9302d088)
--|--

</details>

<details>
<summary>Case 3_Creating a Split View_PASSED</summary>

3. Select two tabs, and select `Open in Split View`. Ensure that both tabs are opened in split view of equal size within the window and the right side split is in focus. 


</details>

<details>
<summary>Case 4_Creating a Split View_PASSED</summary>

4. Select two tabs like above but in three more variations, 1. Pinned tab and a normal tab. 2. Tabs within a group. 3. Tabs that are not adjacent to each other. 

![Image](https://github.com/user-attachments/assets/d327f24f-c382-4c9f-9642-0429468f3dad)|![Image](https://github.com/user-attachments/assets/3101fb2c-ee3e-4c18-a237-e22f14412ecf)
--|--

</details>

<details>
<summary>Case 5_Creating a Split View_PASSED</summary>

- Verified the steps above 1, 2, 3 and 4 on Vertical tabs
- Confirmed that split tabs works fine on Vertical tab orientation 

![Image](https://github.com/user-attachments/assets/c61ad2a5-a804-491c-9541-214050d4f0e5)|![Image](https://github.com/user-attachments/assets/a865b2a5-1232-415a-9e79-d0385eedd041)
--|--

![Image](https://github.com/user-attachments/assets/7f6b4490-1212-4467-943b-ce3861f7548c)|![Image](https://github.com/user-attachments/assets/186623d5-6b68-4687-b42d-713821e788ff)
--|--

![Image](https://github.com/user-attachments/assets/360f5e3b-b4ad-4fdd-82fc-735c5245672f)|![Image](https://github.com/user-attachments/assets/78163380-ca11-42eb-b74f-c244956e4d5d)
--|--

</details>

<details>
<summary>Case 6_Unsplit Tabs_PASSED</summary>

**Unsplit Tabs**
1. Right click on a split view tab and select `Unsplit Tabs`. Tabs should be unsplit and look like before and will be next to each other.
2. Have a split view open, and select the the Split view button in the middle of the split and select `Unsplit Tabs`. Tabs should be unsplit and look like before.

![Image](https://github.com/user-attachments/assets/f2efb3a4-82b0-4cc1-8fec-9fb9a865ecd4)|![Image](https://github.com/user-attachments/assets/b55f22ad-595e-42f3-968a-41136826cbbe)
--|--



</details>

<details>
<summary>Case 7_Unsplit Tabs_PASSED</summary>

**Closing a tab in split view**
1. Closing a tab in split view should act like normal and close the tab, either by selecting the x or by shortcut. By closing a tab within a split view automatically unsplits the tab and the other tab should remain. Restoring that tab should only restore the tab and not the split.

![Image](https://github.com/user-attachments/assets/636c4163-b2c9-4e0e-95c0-8998b766876a)|![Image](https://github.com/user-attachments/assets/cd5f55ee-767c-4cce-959f-c2ee9d1dbe98)
--|--

</details>

<details>
<summary>Case 8_Drag and Dropping a Split View_PASSED</summary>

**Drag and Dropping a Split View**

1. Have several tabs open and also have a split view. Select the split view tabs and drag and drop to different positions within a full tab bar.
2. From step 2 above, check that you can drag a split view into a tab group.
3. Select split view tabs and drag the split view out to create a new window with just the split view. Drag the split view items from the new window and ensure you can drag back into the original window or any other open window.

- Encountered https://github.com/brave/brave-browser/issues/44150
- Encountered https://github.com/brave/brave-browser/issues/44151
- Encountered https://github.com/brave/brave-browser/issues/44153

![Image](https://github.com/user-attachments/assets/e5b3d4d9-c95a-4872-b6d3-3c4a93529af4)|![Image](https://github.com/user-attachments/assets/33947c92-3dad-4b60-be6d-475e9c89b601)
--|--

**Known/expected:**

```
1. When 2 split view tabs are adjacent, drag and drop 1st split view will drag 2nd split tab view as well 

2. When a split view tab is dragged to a new window, along with split view the tab that is present next to the split view will also be dragged to a new window 

3. When there are two split views on a tab bar (not adjacent, there few tabs in-between the two split views) add/remove a split view into a tab group will add/remove both split views 

```
</details>

<details>
<summary>Case 9_Pinning/unpinning a Split View_PASSED</summary>

**Pinning/unpinning a Split View**
1. Pin a split view by selecting the split view tab and right clicking to Pin. Ensure that Pinned split view shows focus when selecting one of the split view items.
2. Ensure you can Unpin a split view by right clicking either Pinned split view item.

- Encountered the issue https://github.com/brave/brave-browser/issues/44089
- Encountered https://github.com/brave/brave-browser/issues/44155

![Image](https://github.com/user-attachments/assets/ef932610-fe3b-433b-9e5e-13129b561dfa)|![Image](https://github.com/user-attachments/assets/4bc3b9b1-a39d-4274-be9b-fb5522492e21)|![Image](https://github.com/user-attachments/assets/02ca43c9-bdd0-4dd6-95d7-90a269ce0c9d)
--|--|--

</details>

<details>
<summary>Case 10_Resizing and Swapping Tab Positions_PASSED</summary>

**Resizing and Swapping Tab Positions**

1.  Right click on split tab and select `Swap Tab Positions`. Tab position should switch. 
2. Select split view button in the middle of the screen and select `Swap Tab Positions`. Tabs positions should switch.
3. Hover over the separator (in the middle of the split) and the mouse pointer should turn into a resize pointer. Resize the window left and right and there should be a minimum width of the smaller window. 

![Image](https://github.com/user-attachments/assets/72a5fb9d-8e1c-4ac8-8a59-4f8284b9c802)|![Image](https://github.com/user-attachments/assets/92a8095d-d762-4267-9e4e-b95a2f83a48b)
--|--

![Image](https://github.com/user-attachments/assets/ce829746-4e2c-47b9-8695-0ecfea1b4bd7)|![Image](https://github.com/user-attachments/assets/ca0fd966-0753-495d-878d-dcb4b6072002)
--|--

</details>

<details>
<summary>Case 11_Appearance and security UI_PASSED</summary>

**Appearance and security UI**
1. When in a split view, check that the focused tab has a border around it and that the split tab in the tab bar is highlighted and also in focus. 
2. Check that the unfocused tab shows the url of the page on the top left of the split view. 
3. Select the tune/permissions button in the url bar and check that domain is the same as the focused tab.
4. Select the Shields button and check that domain is the same as the focused tab.


![Image](https://github.com/user-attachments/assets/e3a00eff-fa4c-4c3b-858b-471b705fe750)|![Image](https://github.com/user-attachments/assets/08f4bf67-6245-43a9-8293-320bcad7c8d8)
--|--

</details>

<details>
<summary>Case 12_Permission prompt split views_PASSED</summary>

- Confirmed that able to add permission prompt tab and normal tab without any issues
- Unable to add two permission prompt tabs in split view - https://github.com/brave/brave-browser/issues/44323
- Encountered the issue https://github.com/brave/brave-browser/issues/44313



</details>

<details>
<summary>Case 13_Split view for local file system tabs_PASSED</summary>

- Confirmed that user can add local file systems tabs to split view 
- Split view tab width for local file system tabs is smaller - https://github.com/brave/brave-browser/issues/44326

![Image](https://github.com/user-attachments/assets/6fc5b364-340a-4081-a425-1da51674d443)

</details>

<details>
<summary>Case 14_Split views in Private and Tor tabs_PASSED</summary>

**Private tabs:**

- Confirmed that split view cab be created via context menu by right clicking on existing tab by selecting the context menu option `New split view`
- Confirmed that split view cab be created between the two tabs via context menu
- Confirmed that user can create split view by right clicking on the link on webpage by selecting the context menu  `New split view`
- Confirmed that user can create split view within the tab group
- Confirmed that user can create split view between the adjacent tabs on the tab bar
- Confirmed that user can create split view between the distant tabs on the tab bar 
- Confirmed that user can un-split tabs using context menu option
- Confirmed that user can swap the tabs using the context menu
- Confirmed that user can drag and drop split view on the tab bar
- Confirmed that user can drag and drop the split view on the tab group
- Confirmed that user can pin the the split view on the tab bar
- Confirmed that user can create the split view between the pin tab and normal tab 
- Confirmed that user can drag the split view out to create a new window
- Verified the above steps on vertical tab orientation on Private tab 

![Image](https://github.com/user-attachments/assets/535cdccf-fdfc-48b2-80a3-5209c1cdb42a)

**Tor tabs:**

- Confirmed that split view cab be created via context menu by right clicking on existing tab by selecting the context menu option `New split view`
- Confirmed that split view cab be created between the two tabs via context menu
- Confirmed that user can create split view by right clicking on the link on webpage by selecting the context menu  `New split view`
- Confirmed that user can create split view within the tab group
- Confirmed that user can create split view between the adjacent tabs on the tab bar
- Confirmed that user can create split view between the distant tabs on the tab bar 
- Confirmed that user can un-split tabs using context menu option
- Confirmed that user can swap the tabs using the context menu
- Confirmed that user can drag and drop split view on the tab bar
- Confirmed that user can drag and drop the split view on the tab group
- Confirmed that user can pin the the split view on the tab bar
- Confirmed that user can create the split view between the pin tab and normal tab 
- Confirmed that user can drag the split view out to create a new window
- Verified the above steps on vertical tab orientation on Private tab 

![Image](https://github.com/user-attachments/assets/91ba6cdc-f598-4b06-a7c9-bb72bdad65c0)

</details>
