### ISSUE TITLE
[Android] Fire/Shred button 

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#37601]
This issue is to implement Fire/Shred button to clear browser data.
```[tasklist]
### Tasks
- [ ] UI changes : [Follow Figma](https://www.figma.com/file/rsiGfV4XiqTGz0UdODaTAc/Shred-browser-data?type=design&node-id=201-20847&mode=design&t=tL7Y5D3qULcW7CwO-0)
- [ ] Add animation for shred
- [ ] Apply changes to clear browsing data [based on](https://slack-files.com/T04PX1BU8-F06UBD12C5T-70bd6e6d05) (Reach out to @deeppandya for clarification)
```

Test Plan : TBD
