### ISSUE TITLE
[ads] Sanity test iOS `NotifyTab[Html/Text]ContentDidChange` business logic

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#37936]
Sanity test:

- [x] Confirm that we do NOT call `ads_service_->NotifyTabHtmlContentDidChange` or `ads_service_->NotifyTabTextContentDidChange` if restoring a tab **[Works for me]**
- [x] Confirm that we do NOT call `ads_service_->NotifyTabHtmlContentDidChange` or `ads_service_->NotifyTabTextContentDidChange` if the tab is NOT a new navigation (user tapped forward/back button or refreshed the tab) **#38278, #38273 and #38270**
- [x] Confirm that we do NOT call `ads_service_->NotifyTabHtmlContentDidChange` or `ads_service_->NotifyTabTextContentDidChange` if the tab redirect chain is empty **[Works for me]**
- [x] Confirm that we do NOT call `ads_service_->NotifyTabHtmlContentDidChange` or `ads_service_->NotifyTabTextContentDidChange` if the tab is displaying an error page **#38271**
- [x] Confirm that we do NOT call `ads_service_->NotifyTabTextContentDidChange` for non-Rewards users **[Works for me]**
- [x] Confirm that we call `ads_service_->NotifyTabHtmlContentDidChange` and `ads_service_->NotifyTabTextContentDidChange` if the tab web content is a single page application (same document) **[Filed brave/brave-browser/issues/38276]**
- [x] Confirm that we call `ads_service_->NotifyTabHtmlContentDidChange` and `ads_service_->NotifyTabTextContentDidChange` if the tab web content is a multi page application (document changed) **[Works for me]**

Please fix any bugs via this issue because they would affect conversions, purchase intent and text classification. See desktop/Android business logic in `brave/browser/brave_ads/tabs/ads_tab_helper.cc`
