### ISSUE TITLE
[NTP Search]: Enable NTP search by default in Nightly

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38300]
## Description 

Flip the switch brave://flags/#brave-ntp-search-widget and enable by default in Nightly channel.

## Blocking issues

```[tasklist]
### Tasks
- [x] Fix top padding of search box
- [x] Can't search when suggestions are disabled
- [x] Searchbox text should be white
- [x] Separate from Brave News (searchbox should show even when News is disabled)
- [ ] ~~Ask Leo should be Answer with AI~~ this is the same string used in the omnibox
- [ ] Icon for Answer with AI results
- [ ] https://github.com/brave/brave-browser/issues/38305
```

## Related Issues

Figma link: https://www.figma.com/design/lVTufBkl5eNrtOQjlAHxjb/Search-box-in-NTP?node-id=220-17509&t=r4vAQxbMdJ6n8sKZ-0

Main issue: https://github.com/brave/brave-browser/issues/35535

**Comment by fallaciousreasoning** [comment]
https://github.com/brave/brave-browser/issues/38303 fixes the UX bugs

**Comment by fallaciousreasoning** [comment]
Okay @rebron there are a couple of PRs and I think we can flip the flag

**Comment by aguscruiz** [comment]
### Some notes on visual polish

### Initial state
<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/e7ad97a5-8b99-4ef7-b24f-44579cc5dc8d">

- [ ] There's a weird second glass effect above the search input
- [ ] Icons (carat-down and search icon) should have a glass/50 color
- [ ] Removed the outline on the dropup for engine selection, and added a divider. Cleans up the view a bit
- [ ] Placeholder text should be glass/70 and use font/large/regular
- [ ] The whole search input doesn't use a regular divider, uses a custom one called strokegradient/dark

--------------------

### Autosuggestions

<img width="583" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/89675879-fe84-475f-8659-39c6e066ba6d">

- [ ] Search term is black, should be glass/100
- [ ] Search icons on the left shouldn't have a square background, and the color is glass/50
- [ ] If we can divide the "Ask Leo" item like on the design, that'd be ideal
- [ ] General stroke is the same as initial state, strokegradient/dark
- [ ] Need to add a close button when the input text is entered to clear the box

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

1. Installed 1.68.86
2. launched Brave
3. confirmed `NTP search widget` is shown on the new tab page
4. opened `#brave-ntp-search-widget` in a new tab page
5. confirmed `Brave Search Widget on the NTP` flag is enabled by default 


example | example | example 
----- | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/96fff471-9db6-4ec4-b28e-576ecba0b3e3)|!![image](https://github.com/brave/brave-browser/assets/98358127/e5307002-3eb7-4f28-8116-16f04f9f96a8)|![image](https://github.com/brave/brave-browser/assets/98358127/f0e3e549-95a7-4701-b0af-26870a96ecf9)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (x86_64)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.68.86`
2. launched Brave
3. confirmed NTP search widget is shown on the new tab page
4. opened `brave://flags/#brave-ntp-search-widget` in a new tab page
5. confirmed `Brave Search Widget on the NTP` flag is enabled by default

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2024-06-12 at 4 36 59 PM" src="https://github.com/brave/brave-browser/assets/387249/a7731a1a-aaff-46b2-a54a-023e8dd8b873"> | <img width="1312" alt="Screen Shot 2024-06-12 at 4 39 07 PM" src="https://github.com/brave/brave-browser/assets/387249/0d866273-f5cd-49cd-8502-e6bbf8924194"> | <img width="1312" alt="Screen Shot 2024-06-12 at 4 38 39 PM" src="https://github.com/brave/brave-browser/assets/387249/fc4ef347-eea2-4cdb-8fc3-4dc02849ca45">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (64-bit) 
Revision	786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS	Linux
```

### Steps:

1. installed `1.68.87`
2. launched Brave
3. confirmed NTP search widget is shown on the new tab page
4. opened `brave://flags/#brave-ntp-search-widget` in a new tab page

### Confirmed `Brave Search Widget on the NTP` flag is enabled by default

example | example | example
---------|----------|---------
<img width="1314" alt="Screen Shot 2024-06-13 at 2 41 12 PM" src="https://github.com/brave/brave-browser/assets/387249/914ad52a-d481-429e-a1e6-2de4112364f8"> | <img width="1314" alt="Screen Shot 2024-06-13 at 2 42 32 PM" src="https://github.com/brave/brave-browser/assets/387249/28d6bd34-0e68-4514-b3df-00e9b25a37bc"> | <img width="1314" alt="Screen Shot 2024-06-13 at 2 41 51 PM" src="https://github.com/brave/brave-browser/assets/387249/2e0b589b-e704-4830-9b1d-a0d65270e55f">
