### ISSUE TITLE
Remove PDF.js in favor of using PDFium

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#3846]
## Test plan 
See https://github.com/brave/brave-core/pull/2342

## Justification
Some of the reasons for removing include:
- high memory overhead
- large number of reported PDF issues

## Tasks
- [x] remove option to disable PDF.js from settings
- [x] remove PDF.js manifest override
- [x] remove existing install of PDF.js (if present)
- [x] update build / GN flags to ensure PDFium is included/enabled
- [x] test existing PDF issues and close ones which are fixed with PDFium
- [x] security review

## Round-up of PDF.js issues this will fix:
- [x] Printing from Google web apps (Docs, Sheets, etc) saves to PDF instead of opening print dialog #3694
- [x] Dynamically generated PDF does not load properly #884
- [x] Cannot open pdf file in new window, No problems with Chrome. #3119

## Issues that we'll have to ask users for help re-testing:
- [ ] PDF embed on a site that require login doesn't open. #2092
- [ ] Issue loading coldfusion generated PDF's #4216 
- [ ] Weird "dirt" over a PDF file view #4001

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/google-chrome-like-pdf-inline-pdf-viewer/54283/2

**Comment by CalamariDude** [comment]
Hi not sure if this is the right place to ask this but: I've been looking forward to this feature and I see it deployed to the nightly builds which I have. How do I update my stable brave browser to the newest release?

Thanks!

**Comment by bbondy** [comment]
@CalamariDude you can grab Nightly here:
https://brave.com/download-nightly/

Every 3 weeks it'll migrate from Nightly to Dev
Dev to Beta
Beta to Release

There's a different download page for each.

**Comment by dionyziz** [comment]
Does this fix the issue with the URL bar not showing just the PDF URL also?

**Comment by tycho01** [comment]
@dionyziz just upgraded to nightly, looks like it does!

**Comment by btlechowski** [comment]
Awesome work!

Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-core/pull/2342

Verified that  [PDF.js extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) can still be installed and used as default. 

Verified that  PDF.js is deleted after update to PDFium
![image](https://user-images.githubusercontent.com/34715963/62093064-1afb3080-b278-11e9-8412-7b6fc70dcef2.png)

Verified opening pdfs over [http ](http://www.pdf995.com/samples/pdf.pdf) and [https](https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf) works

**Comment by dteiml** [comment]
Is there any way to enable the old viewer? I loved its functionality

**Comment by tycho01** [comment]
@dteiml:
> Is there any way to enable the old viewer? I loved its functionality

I think you can just [install it from the store](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm).

**Comment by bsclifton** [comment]
@dteiml what @tycho01 shared is correct - you can install PDF.js from the store 😄 
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

Once installed, it should work great! Please let us know if you run into any issues

**Comment by tycho01** [comment]
I don't think this still lets you use PDF.js for local files anymore though... :disappointed:
