### ISSUE TITLE
Pending verification's/Release Notes from previous `1.66.x` milestones

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#38832]
Current list of issues that have been fixed/resolved via [`1.66.x - Release #6`](https://github.com/brave/brave-browser/milestone/495) but haven't been verified by QA and should be completed before `1.66.1` goes out on `iOS`:

* [x] [iOS] Update User Agent to 17.5 #38322
* [x] [ads] iOS Brave News ads are not served for restored NTP tab #38378
* [x] [iOS] Add Tab Debug clipboard action #38449
* [x] Loading a URL that would trigger a calendar invite doesn't work on NTP/other websites #38548
* [x] Download prompts can appear after switching tabs #38551
* [x] Brave crashes when alerts/action sheets are dismissed while WebKit is awaiting a response #38651
* [x] [iOS] - Sometimes Playlist Items save offline but won't delete #38665
* [x] [ads] Unable to trigger Brave News inline ad viewed event when opted-in to News from NTP #38698

Current list of issues that were `release-notes/include` via [`1.66.x - Release #6`](https://github.com/brave/brave-browser/milestone/495) and should be added into the release notes for the `1.66.1` release:

* Loading a URL that would trigger a calendar invite doesn't work on NTP/other websites #38548
* Download prompts can appear after switching tabs #38551
* Remove Brave Swap Fee #38566
* Brave crashes when alerts/action sheets are dismissed while WebKit is awaiting a response #38651
* [iOS] - Sometimes Playlist Items save offline but won't delete #38665
* Upgrade from Chromium 125.0.6422.147 to Chromium 125.0.6422.165 #38803

**Comment by kjozwiak** [comment]
Closing as all the issues from the previous `1.66.x` milestone have been addressed.
