### ISSUE TITLE
AI Chat full page / conversation history tracker

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#38873]
```[tasklist]
### MVP Tasks
- [ ] Service architecture refactor (required for persistance) https://github.com/brave/brave-browser/issues/31623
- [ ] Persistence layer https://github.com/brave/brave-core/pull/19503
- [ ] List of Conversations - WebUI frontend
- [ ] Responsiveness for existing conversation area components - WebUI frontend
- [ ] iOS frontend
```

```[tasklist]
### Other Tasks
- [ ] Sync
- [ ] Search
```

<img width="633" alt="image" src="https://github.com/brave/brave-browser/assets/741836/9648d95f-e4e1-438f-9697-f53b2f66f240">

**Comment by diracdeltas** [comment]
The persistence feature needs a security/privacy review.

**Comment by bsclifton** [comment]
@petemill can we close this?

**Comment by petemill** [comment]
@bsclifton still has sync and notifications as open tasks. Will create follow-ups.
