### ISSUE TITLE
Keybord not working in brave on Ubuntu 24.04

### ISSUE THREAD

**Issue by abdulrahim2002** [brave/brave-browser#39082]
### Description

**THIS IS AN ISSUE WITH SNAP**

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
**

I installed brave from snap: https://snapcraft.io/brave

The keyboard(**mouse works although**) is not working, whenever i press a key,  a warning is generated in logs:
```
(brave:14390): IBUS-WARNING **: 19:23:55.856: Events queue growing too big, will start to drop.
```

Here's my system details:
```
{20:02}~ ➭ neofetch --off
name@name
--------- 
OS: Ubuntu 24.04 LTS x86_64 
Host: Victus by HP Laptop 16-e0xxx 
Kernel: 6.8.0-35-generic 
Uptime: 1 hour, 35 mins 
Packages: 2146 (dpkg), 22 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 46.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-orange-dark [GTK2/3] 
Icons: Yaru-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 4.280GHz 
GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 3729MiB / 7269MiB
```

Here's detailed logs:
```
{19:22}~ ➭ brave 
Gtk-Message: 19:22:09.372: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(brave:14390): Gtk-WARNING **: 19:22:09.484: GTK+ module /snap/brave/416/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 19:22:09.484: Failed to load module "canberra-gtk-module"

(brave:14390): Gtk-WARNING **: 19:22:09.488: GTK+ module /snap/brave/416/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 19:22:09.488: Failed to load module "canberra-gtk-module"
/usr/share/libdrm/amdgpu.ids: No such file or directory
[14390:14390:0616/192211.100968:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/

(brave:14390): IBUS-WARNING **: 19:22:12.585: Unable to connect to ibus: Could not connect: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
[14463:14463:0616/192219.453833:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[14463:14463:0616/192219.455766:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[14463:14463:0616/192224.154722:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Jun 16 19:23:38.575 [notice] Tor 0.4.8.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.0.13, Zlib 1.3.1, Liblzma N/A, Libzstd N/A and Glibc 2.35 as libc.
Jun 16 19:23:38.576 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 16 19:23:38.576 [notice] Read configuration file "/home/kaku/snap/brave/416/.config/BraveSoftware/Brave-Browser/biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.35/tor-torrc".
Jun 16 19:23:38.576 [notice] Read configuration file "/home/kaku/snap/brave/416/.config/BraveSoftware/Brave-Browser/biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.35/tor-torrc".
Jun 16 19:23:38.578 [notice] Opening Socks listener on 127.0.0.1:0
Jun 16 19:23:38.578 [notice] Socks listener listening on port 43145.
Jun 16 19:23:38.578 [notice] Opened Socks listener connection (ready) on 127.0.0.1:43145
Jun 16 19:23:38.578 [notice] Opening Control listener on 127.0.0.1:0
Jun 16 19:23:38.578 [notice] Control listener listening on port 40181.
Jun 16 19:23:38.578 [notice] Opened Control listener connection (ready) on 127.0.0.1:40181
Jun 16 19:23:38.000 [notice] Bootstrapped 0% (starting): Starting
Jun 16 19:23:38.000 [notice] Starting with guard context "default"
Jun 16 19:23:38.000 [notice] New control connection opened from 127.0.0.1.
Jun 16 19:23:38.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 16 19:23:39.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 16 19:23:39.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 16 19:23:43.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 16 19:23:43.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Jun 16 19:23:43.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Jun 16 19:23:43.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Jun 16 19:23:52.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Jun 16 19:23:52.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Jun 16 19:23:53.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Jun 16 19:23:53.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Jun 16 19:23:53.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7087, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Jun 16 19:23:54.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors

(brave:14390): IBUS-WARNING **: 19:23:55.856: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:55.951: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:55.989: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.070: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.139: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.211: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.273: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.302: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.417: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.435: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.517: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.521: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.569: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:23:56.706: Events queue growing too big, will start to drop.
Jun 16 19:23:58.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Jun 16 19:23:59.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors

(brave:14390): IBUS-WARNING **: 19:24:00.129: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.284: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.301: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.429: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.448: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.458: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.474: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.489: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.522: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.529: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.602: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.619: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.624: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.630: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.632: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.705: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.712: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.715: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.720: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.736: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.783: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.858: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.862: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.867: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.874: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:00.969: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.116: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.136: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.167: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.168: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.171: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.173: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.177: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.181: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.185: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.190: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.213: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.217: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.248: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:01.292: Events queue growing too big, will start to drop.
Jun 16 19:24:01.000 [notice] Bootstrapped 60% (loading_descriptors): Loading relay descriptors
Jun 16 19:24:02.000 [notice] Bootstrapped 69% (loading_descriptors): Loading relay descriptors
Jun 16 19:24:02.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 16 19:24:02.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 16 19:24:02.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 16 19:24:03.000 [notice] Bootstrapped 100% (done): Done
[14390:14390:0616/192404.095498:ERROR:interface_endpoint_client.cc(722)] Message 0 rejected by interface blink.mojom.WidgetHost

(brave:14390): IBUS-WARNING **: 19:24:06.033: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:06.065: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:06.677: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:06.776: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:06.872: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:06.947: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:08.835: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.026: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.027: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.143: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.214: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.293: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.379: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.390: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.470: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.472: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.511: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.606: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.639: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.685: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.786: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.823: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.827: Events queue growing too big, will start to drop.

(brave:14390): IBUS-WARNING **: 19:24:09.937: Events queue growing too big, will start to drop.

```

### Steps to reproduce

1. 
2. 
3. 

### Actual result

nothing/unresponsive.

### Expected result

characters should be inserted, shortcuts should work

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

brave --version
Brave Browser 126.1.67.116 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I believe this is a chromium issue, since it doesnt work in chromium either

**Comment by abdulrahim2002** [comment]
i am closing this because this is an issue with snap
since i was able to get it from flatpak and it works nicely
