### ISSUE TITLE
[ads] New tab takeover Android video ads

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#39988]
**Q3/2024**

**MVP**
- [ ] [[ads] Implement playback of NTT video ads based on design](https://github.com/brave/brave-browser/issues/39989)
- [ ] [[ads] Autoplay long form NTT video ad muted for n seconds](https://github.com/brave/brave-browser/issues/39990)
- [ ] [[ads] Implement play/pause buttons for long form NTT video ads](https://github.com/brave/brave-browser/issues/39992)
- [ ] [[ads] Support short form NTT video playback](https://github.com/brave/brave-browser/issues/39993)
- [ ] [[ads] Transition to landing page when a user clicks on an NTT video ads CTA button](https://github.com/brave/brave-browser/issues/39994)
- [ ] [[ads] Fadeout/fadein stats on NTP when NTT video is started playing](https://github.com/brave/brave-browser/issues/39995)
- [ ] [[ads] Add support for fit-to-fill mode for NTT video](https://github.com/brave/brave-browser/issues/39996)
- [ ] [[ads] Do not show NTT video for Android in landscape mode](https://github.com/brave/brave-browser/issues/39997) 
- [ ] [[ads] Configure NTT video blank space color when viewing video in letterbox/pillar-box modes](https://github.com/brave/brave-browser/issues/39998)
- [ ] [[ads] Tapping on the video during 6 seconds autplay starts video NTT playback](https://github.com/brave/brave-browser/issues/39999)

--

https://github.com/brave/brave-browser/projects/26#column-19787507

**Comment by tmancey** [comment]
Blocked as may be superseded by https://github.com/brave/brave-browser/issues/41698

**Comment by tmancey** [comment]
Closing as will be superseded by https://github.com/brave/brave-browser/issues/41698
