### ISSUE TITLE
missing passwords and autofills

### ISSUE THREAD

**Issue by exiledmachinist** [brave/brave-browser#40121]
### Description

after newest version update to v1.68.131 Chromium 127.0.6533.73 autofill and passwords are missing this is after the cloud strike debacle.  rolled back to previous version V1.67.134 Chromium: 126.0.6478.186 autofill and passwords are there so info isnt gone just unaccessible in the newest version.

### Steps to reproduce

1. save new passwords and autofill in the password manager  save and close  reopen there gone have repeated this a dozen times 
2. 
3. 

### Actual result

the passwords and auto save manager no longer lists the passwords and autofill like the previous version 

### Expected result

im hoping this is fixed in the next stable version released 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.68.131 Chromium 127.0.6533.73 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

thank you to the dev and people who much smarter then i for making such a great browser if this is a simple fix that i need to do in my computer please just tell me what to do.  again thank you 
```[tasklist]
### Tasks
```

**Comment by exiledmachinist** [comment]
ok sorry mods and everyone i did a full uninstall and wipe of brave and reinstalled again fixed the issue and reloaded all my saved passwords and autofills and extension  sorry im not super computer smart sometimes thank you again for all the hard work

**Comment by exiledmachinist** [comment]
im sorry i should have tried a full uninstall first instead of wasting your time
