### ISSUE TITLE
When Ad and Tracker Blocking is Set to Aggressive Custom Blocking Rules Don't Work

### ISSUE THREAD

**Issue by DanielProg39** [brave/brave-browser#40162]
### Description

When ad and tracker blocking is set to aggressive, custom blocking rules generally don't work, and refreshing pages for which custom blocking rules have been set will sometimes block content and sometimes not. If ad and tracker blocking is set to standard, custom blocking works.

### Steps to reproduce

1. Block an element on a webpage
2. Set ad and tracker blocking to aggressive
3. Refresh the page several times
4. Set ad and tracker blocking to standard
5. Refresh the page several times

### Actual result

When ad and tracker blocking is set to aggressive, sometimes the element is blocked and sometimes not. If ad and tracker blocking is set to standard, custom blocking works properly.

### Expected result

When ad and tracker blocking is on, custom rules should work every time the page is opened.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.68.128 Chromium: 127.0.6533.73 (Official build) (64 bit)
Revision: 800676fd9ede2eb4174bac98c186e53749c7201f
OS: Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Also noticed that cosmetic filtering may have become worse when filtering is set to aggressive.

**Comment by antonok-edm** [comment]
@DanielProg39 we've just pushed out a change that might help - can you try updating `Brave Ad Block Updater` to version `1.0.7178` or later and let me know if that fixed it?

**Comment by DanielProg39** [comment]
Yes, that seems to have fixed it. Set blocking to aggressive and everything is blocked properly.

Unrelated: could you look at #32533? I opened it a while ago, and many Brave versions later, it is still unresolved.
