### ISSUE TITLE
Enabling AdGuard URL Tracking Protection Filters breaks Custom Adblock rules to be applied.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#40358]
### Description

@ryanbr I am tagging you because I know you implemented the list, but something is going on with it.

As the title says, the issue is pretty simple to explain: no new custom rule will be applied until you either disable-enable the list or restart the browser.

I tested with Brave started with `--user-data-dir=` to make sure it wasn't anything else, and then I could finally filtered it as the AdGuard URL Tracking Protection Filters list causing this whole issue.

This only happens when the Custom rules are applied after the list is being enabled, if you disable and then enable the list immediately, new custom rules will work, if you apply the rule and then enable the list the rule will work as well, but if you then disable the rule and refresh page, it will not work, so the problem is when the list is after the list is _downloaded and applied_.

https://github.com/user-attachments/assets/d8d76ab2-40f1-4f93-84c0-284c1de75055

### Steps to reproduce

1. Enable AdGuard URL Tracking Protection Filters list
2. add brave.com##*
3. nothing happens
4. disable the list, the filter should work fine

### Actual result

When list is enabled no new custom filter will work.

### Expected result

custom filters should work as usual.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.57 Chromium: 127.0.6533.100 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3958)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
Fixed by https://github.com/brave/adblock-resources/pull/198

**Comment by ShivanKaul** [comment]
Thanks for reporting this, we're working on preventing this from happening again: https://github.com/brave/adblock-resources/issues/199.
