### ISSUE TITLE
macOS: Some Meta keys are prevent from being recorded with JavaScript

### ISSUE THREAD

**Issue by TheLostProgrammer** [brave/brave-browser#40494]
### Description

Here's the following JavaScript:
```js
document.addEventListener('keydown', function(event) {
    event.preventDefault()
    console.log(event)
})
```
This JavaScript listens for the keydown event and then will log that to the console. If you do CMD (macOS Meta key) + Y/Z/A it doesn't show up. Here is an example of a recorded key:
```
KeyboardEvent {isTrusted: true, key: 'c', code: 'KeyC', location: 0, ctrlKey: false, …}
isTrusted: true
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyC"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
isComposing: false
key: "c"
keyCode: 67
location: 0
metaKey: true
repeat: false
returnValue: false
shiftKey: false
sourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}
srcElement: textarea
target: textarea
timeStamp: 1487490
type: "keydown"
view: Window {window: Window, self: Window, document: document, name: '', location: Location, …}
which: 67
[[Prototype]]: KeyboardEvent
```
`metaKey` is `true` and `key` is `"c"`. This will not show up with CMD + A, CMD + Y or CMD + Z.  

I believe it is a bug as it doesn't have any issues on Windows or with any other Chromium-based browser.

### Steps to reproduce

1. Run the provided JS in the console
2. Click the website and hold CMD with A, Y or Z
3. Check the console for output
4. The only output should be the Meta key such as MetaLeft or MetaRight, there will be no other key recorded.
5. Now try with other combinations like CMD with C, P, X, V, etc...

### Actual result

The combination with CMD (meta key on macOS) with A, Y or Z is not recorded. Only the meta key itself.

### Expected result

I expect to see the key pressed while the meta key is held down. It should show up as it does on any other browser like Firefox and other Chromium-based browsers.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.68.141 Chromium: 127.0.6533.120 (Official Build) (arm64)
Revision: b3f23500b575d50584510ea1814ef440d30741a8
OS: macOS Version 15.1 (Build 24B5024e)
JavaScript: V8 12.7.224.18

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome
