### ISSUE TITLE
Pending verification's/Release Notes from previous `1.69.x` milestones

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#40859]
Current list of issues that have been fixed/resolved via [`1.69.x - Release #2`](https://github.com/brave/brave-browser/milestone/515, [`1.69.x - Release #3`](https://github.com/brave/brave-browser/milestone/517), [`1.69.x - Release #4`](https://github.com/brave/brave-browser/milestone/519) & [`1.69.x - Release #5`](https://github.com/brave/brave-browser/milestone/520) but haven't been verified by QA and should be completed before `1.69.x - Release #5` goes out on `iOS`:

* [x] [Brave Leo]: Update model names in Leo models menu #40464
* [x] [iOS] Update User Agent to 17.6 #40578
* [x] [hackerone] UI Spoofing #40709
* [x] [Hackerone] Fix sandbox downloads #40846
* [x] Upgrade from Chromium 128.0.6613.114 to Chromium 128.0.6613.120 #40804
* [x] Upgrade from Chromium 128.0.6613.120 to Chromium 128.0.6613.127 #40862
* [x] [iOS] - Receipt Linking on TestFlight not working #40874
* [x] [Follow up to 36409] 'Server' and 'Support' subtitles switched on VPN settings page #40843
* [x] Crash when closing 'Share Rewards Internals' dialog #40819
* [x] Plus sign button in tab bar is cut off [iPad] #40500
* [x] Save to Files is missing from Share menu, and instead Create PDF is shown, which doesn't work at all #40918
* [x] In Standard Shields, significant text check should happen before partiness check #40967
* [x] Upgrade from Chromium 128.0.6613.120/128.0.6613.127 to Chromium 128.0.6613.138 #40972
* [x] Add 1.69 translations #41007

Current list of issues that were `release-notes/include` via [`1.69.x - Release #2`](https://github.com/brave/brave-browser/milestone/515, [`1.69.x - Release #3`](https://github.com/brave/brave-browser/milestone/517), [`1.69.x - Release #4`](https://github.com/brave/brave-browser/milestone/519) & [`1.69.x - Release #5`](https://github.com/brave/brave-browser/milestone/520) and should be added into the release notes for the `1.69.x - Release` release:

* In Standard Shields, significant text check should happen before partiness check #40967
* [iOS] Invalid content blocker rules #36039
* [iOS] Update UX with advanced server selection #36409
* Enable Bitcoin by default on iOS #38775
* Leo - Update input box to match design tweaks #38960
* Update twitter.com to x.com #39322
* Fix issues with RequestBlockingScript.js #39546
* [iOS] Per-site adblocking setting is all-or-nothing #39573
* Improve VPN Country Server Details #39824
* [Brave Leo]: Update model names in Leo models menu #40464
* [hackerone] UI Spoofing #40709
* [Hackerone] Fix sandbox downloads #40846
* Upgrade from Chromium 128.0.6613.120/128.0.6613.127 to Chromium 128.0.6613.138 #40972
