### ISSUE TITLE
AIChat: refactor tracker

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#41171]
This tracks code issues of any size that anyone might notice and want to prioritize to be fixed:

- [ ] `brave/browser/ai_chat` should be a target and not use sources.gni
- [ ] `ConversationHandlerUnitTest` could use params instead of different tests for different variations
- [ ] Duplicated mock test classes could be de-duplicated to test_support.h/cc or similar
- [ ] Context menu could store data in the tab helper instead of a separate user data key
