### ISSUE TITLE
Pending verification's/Release Notes from previous `1.70.x` milestones

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#41251]
Current list of issues that have been fixed/resolved via [`1.70.x - Release #2`](https://github.com/brave/brave-browser/milestone/523), [`1.70.x - Release #3`](https://github.com/brave/brave-browser/milestone/526), [`1.70.x - Release #4`](https://github.com/brave/brave-browser/milestone/527) & [`1.70.x - Release #5`](https://github.com/brave/brave-browser/milestone/528) but haven't been verified by QA and should be completed before `1.70.x - Release` goes out on `iOS`:

* [x] Support Dark Mode & Tinted Icons on iOS 18 #41088
* [x] Picker layouts in settings screens are incorrect on iOS 18 SDK builds #41114
* [x] [Follow up to #36036] Filter search not returning correct results #41168
* [x] [iOS] - Update JitsiMeetSDK #40829
* [x] [Follow up to #36036] Filter search not returning correct results #41168
* [x] Tinted mode not working for some Brave widgets [iOS 18] #41178
* [x] [Follow up to #41088] Adjust dark mode icons #41211 (spot check only)
* [x] 'Open in Brave' from X app share widget not working [iOS 18] #41296 
* [x] Crash in Playlist when saving offline and internet connection disabled #41388
* [x] Blocking summary popup crashes the app when presented #41443
* [x] Launching the app via the Shortcuts Widget Search button may crash #41457
* [x] Crash when displaying internal pages #41445
* [x] [Wallet/iOS] User Assets are deletable  #41357
* [x] [Wallet/iOS] Crash happens when delete NFT from Edit User Assets #41387
* [x] [Wallet/iOS] Transaction Status will be dismissed automatically after tx gets confirmed #41563
* [x] RTL/BiDi Language Support #40471
* [x] Add 1.70 translations #41679
* [x] [iOS][hackerone] Fix url formatting #41716
* [x] [hackerone] Fix interstitial not showing deceptive site warning #41803

Current list of issues that were `release-notes/include` via  [`1.70.x - Release`](https://github.com/brave/brave-browser/milestone/505), [`1.70.x - Release #2`](https://github.com/brave/brave-browser/milestone/523), [`1.70.x - Release #3`](https://github.com/brave/brave-browser/milestone/526), [`1.70.x - Release #4`](https://github.com/brave/brave-browser/milestone/527) & [`1.70.x - Release #5`](https://github.com/brave/brave-browser/milestone/528) and should be added into the release notes for the `1.70.x - Release` release:

* [iOS] Add search to filter lists screen #36036
* Have a way to force-update adblock lists #35982
* [ads] Clear ads history, conversion URLs, etc when browsing history is cleared #39051
* Crash when you open address bar and press the settings next to the search engine options #39136
* Edit custom search engines #39552
* [Follow up to #38340] Add Bookmark for <X> Tabs button shows wrong count when NTP is opened in background #39590
* iOS transaction confirmation panel contract address link out #39720
* [iOS] - Use DarkReader for NightMode #39786
* [iOS] Leo - Change eraser icon to a "new chat" icon #39818
* [Leo] Support modifying user prompt on iOS #39831
* Focus input box when opening Leo (iOS) #39858
* Try both RFC and Chromium URL parsing in Debouncer #39866
* Add Leo to Shortcuts Widget #39886
* Upgrading to https not handling a serverside https downgrade #40346
* RTL/BiDi Language Support #40471
* [iOS] Update "Indirect Support" text for non-connected users in Rewards 2.5 panel #40909
* Support Dark Mode & Tinted Icons on iOS 18 #41088
* Launching the app via the Shortcuts Widget Search button may crash #41457
* Crash when displaying internal pages #41445
* Blocking summary popup crashes the app when presented #41443
* Crash in Playlist when saving offline and internet connection disabled #41388
* 'Open in Brave' from X app share widget not working [iOS 18]  #41296
* [iOS][hackerone] Fix url formatting #41716
* [hackerone] Fix interstitial not showing deceptive site warning #41803

**Comment by kjozwiak** [comment]
@Uni-verse once we're closer to completing `1.70.x`, probably a good idea run through https://github.com/brave/brave-browser/milestone/505 and ensure that the issues are labelled correctly re: `release-notes/include` or `release-notes/exclude`.
