### ISSUE TITLE
unexpected red UI when sharing to Brave Talk

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#41455]
### Description

When attempting to share my screen with Brave Talk, there's a lot of unexpected red UI elements.

Maybe related to https://github.com/brave/brave-browser/issues/40490? Or possibly Chromium 130.

Also observed by @aguscruiz via 

### Steps to reproduce

1. Be on a Brave Talk call
2. Go to share screen
3. See red UI

### Actual result

![Image](https://github.com/user-attachments/assets/afc1cc62-adf2-4e8d-870a-dd91015b02b9)

### Expected result

should look more like 1.70.123

![Image](https://github.com/user-attachments/assets/136d3e0c-10d2-4f98-a6a4-91124f6d232e)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.61 Chromium: 130.0.6723.31 (Official Build) nightly (x86_64)
-- | --
Revision | 273634c75c90bd6f08065720aa3335fc32fd725d
OS | macOS Version 14.7 (Build 23H124)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @aguscruiz @fallaciousreasoning

**Comment by LaurenWags** [comment]
Somewhat reproduces with `1.72.59 Chromium: 129.0.6668.89`. Not sure if caused by https://github.com/brave/brave-browser/issues/40490 and then exacerbated by Chromium 130 or something else?

![Image](https://github.com/user-attachments/assets/910989f9-81ff-47d0-863d-74a661c76fe0)

**Comment by emerick** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/25832. Even though that pull request references the task manager, that page and this page both use an underlying table view and related colors which are at the root of the problem.

**Comment by fallaciousreasoning** [comment]
Hopefully https://github.com/brave/brave-core/pull/25863 should prevent a bunch of these popping up in the future

**Comment by kjozwiak** [comment]
> Should be fixed by [brave/brave-core#25832](https://github.com/brave/brave-core/pull/25832). Even though that pull request references the task manager, that page and this page both use an underlying table view and related colors which are at the root of the problem.

Definitely resolved. Checked `1.72.61 Chromium: 130.0.6723.31` and was able to reproduce the the above and then installed `1.72.67 Chromium: 130.0.6723.31` which seems to have fixed the issue re: the incorrect colours being used.

**`1.72.61 Chromium: 130.0.6723.31`** | **`1.72.67 Chromium: 130.0.6723.31`**
-------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/02a73f5c-6a21-4f67-9194-997710f34e51) | ![Image](https://github.com/user-attachments/assets/4d4f37fe-9385-440e-a9cd-24964232d193)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Reproduced the issue in 

1.72.61 Chromium: 130.0.6723.31|1.71.114 Chromium: 130.0.6723.58
------- | -------
![Image](https://github.com/user-attachments/assets/4aa4d680-858b-4982-8257-d474ccc1717b)|![Image](https://github.com/user-attachments/assets/2d9ccac6-5db5-459a-b70c-686e1f22b1af)

Verified the issue using the STR from the description in https://github.com/brave/brave-browser/issues/41455#issue-2571389115


**_Brave talk_** 

<details>

Light theme | Dark theme | Custom theme 
----- | ----- | -----
![Image](https://github.com/user-attachments/assets/dd9943e4-cf30-4e03-8137-d6cfb9ce9e7d)|![Image](https://github.com/user-attachments/assets/ee668a36-57cf-4fcf-bc97-7875d49d8219)|![Image](https://github.com/user-attachments/assets/dfb6fb12-b3bf-4fba-9914-977d6d85dbef)
</details>

**_Bookmarks dialog_**

<details>

![Image](https://github.com/user-attachments/assets/5ffa9be6-26e5-4f69-be1c-f7331264116e)
</details>

**_Task Manager_**
<details>

![Image](https://github.com/user-attachments/assets/58dc9375-b7f5-4921-bfa9-760c1289595a)
</details>


**_Native buttons_**
<details>

example | example | example | example | example | example 
----- | ------ | ------ | ------ | ------- | -------
![Image](https://github.com/user-attachments/assets/79a93a33-3307-434b-bce6-161f0e37d812)|![Image](https://github.com/user-attachments/assets/4c92b7ca-c748-4154-9f5e-b1e1cf976134)|![Image](https://github.com/user-attachments/assets/72742a8c-fe25-499c-b8e7-364dc069478c)|![Image](https://github.com/user-attachments/assets/186f48a3-b822-49aa-abd9-54b1782fff7a)|![Image](https://github.com/user-attachments/assets/d9cb2690-8e2d-4898-82f7-7b8674a488bc)|![Image](https://github.com/user-attachments/assets/960d38ee-150e-4df8-87de-2caf3e7784db)
</details>
