### ISSUE TITLE
[ads] `NotifyTab[Text|Html]ContentDidChange` are not triggered for domains blocked by aggressive tracker and ad blocking

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#41622]
### Description

`NotifyTab[Text|Html]ContentDidChange` are not triggered if a user has enabled aggressive tracker and ad blocking, and then proceeds to the page. This affects both conversions and text classification.

### Steps to reproduce

1. Enable aggressive tracker and ad blocking
2. Visit a domain which is blocked
3. Click "Proceed"

### Actual result

`NotifyTab[Text|Html]ContentDidChange` are not called, which prevents conversions and text classification from being processed.

### Expected result

`NotifyTab[Text|Html]ContentDidChange` should be called so that conversions and text classification can be processed.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

.

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by tmancey** [comment]
Closing as issue as will be resolved by https://github.com/brave/brave-core/pull/25523
