### ISSUE TITLE
Remove Google tracking parameters

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#41739]
### Description

Google Search has some tracking parameters in the URL that are not removed by Brave:

1. sca_esv
2. ei
3. iflsig
4. ved
5. gs_lp

### Steps to reproduce

1. Access Google search at www.google.com (or any other domain from another country, such as www.google.es)
2. Search for something in the search bar (in my test, I used the word "test")

### Actual result

Note: I removed part of the parameters and replaced them with 3 dots (...) for privacy reasons.

https://www.google.com/search?q=test&sca_esv=6298c17...&source=hp&ei=TNgTZ7u0...&iflsig=AL9hbdgA...&ved=0ahUKEwi...&uact=5&oq=test&gs_lp=Egdnd3Mt...&sclient=gws-wiz

### Expected result

https://www.google.com/search?q=test&source=hp&uact=5&oq=test&sclient=gws-wiz

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)
89c4031c685a4296315a6f421f46275f0b72dd55
Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by fmarier** [comment]
Extensions to look at:
- https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1/
- https://chromewebstore.google.com/detail/google-link-fixer/pcpdkhaeeohmogfgcheopfcigcfdaioj?hl=en
