### ISSUE TITLE
Pending verification's/Release Notes from previous `1.71.x` milestones

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#41808]
Current list of issues that have been fixed/resolved via [`1.71.x - Release #2`](https://github.com/brave/brave-browser/milestone/530), [`1.71.x - Release #3`](https://github.com/brave/brave-browser/milestone/531), [`1.71.x - Release #4`](https://github.com/brave/brave-browser/milestone/533) & [`1.71.x - Release #5`](https://github.com/brave/brave-browser/milestone/534) but haven't been verified by QA and should be completed before `1.71.x - Release` goes out on `iOS`:

* [x] [Shred] Tab and data not deleted when using 'App Close' for Auto Shred #40484
* [x] [iOS] - User cannot cancel history deletion #41148
* [x] [iOS] - Playlist Crash #41232
* [x] [hackerone][iOS] Fix Reader Mode #41444
* [x] [iOS] - Requesting Speech Recognizer from a Website crashes #41639
* [x] [iOS] - MessageHandlers don't exist immediately after deleting them #41653
* [x] Shred button displayed unnecessarily on certain screens #41671
* [x] Loading a bundled favicon sometimes can crash #41697
* [x] Crash on launch with shred feature and keep private tabs setting enabled #41765
* [x] [iOS/Wallet] Transaction Activity Tab is fetching NFT metadata using duplicate nft_id #41839
* [x] Install VPN Profile is incorrectly shown after a failed App Store subscription restore #41012
* [x] Shred doesn't clear site from Recently Closed Tabs #41769
* [x] [Hackerone] History and Bookmarks and ShieldsPanel and 3-Dot menu URL-Eliding #41954
* [x] Shred intermittently not clearing all data #41897
* [x] [iOS] Add 1.71 Translation #42110 
* [x] [Follow up to #40051][l10n] The whole Sync chain regressed and was not translated into non-English languages. #41731
* [x] [Follow up to #41445] Crash when displaying internal pages #42162

Current list of issues that were `release-notes/include` via [`1.71.x - Release #2`](https://github.com/brave/brave-browser/milestone/530), [`1.71.x - Release #3`](https://github.com/brave/brave-browser/milestone/531), [`1.71.x - Release #4`](https://github.com/brave/brave-browser/milestone/533) & [`1.71.x - Release #5`](https://github.com/brave/brave-browser/milestone/534) and should be added into the release notes for the `1.70.x - Release` release:

* Support local vector search for the selection of key text segments of page and video context #36801
* [Follow up to #38086] Refresh your credentials button is not working on VPN paywall when opening it from Settings > Brave Firewall + VPN #39871
* Leo - Edit generated AI replies on iOS #40208
* [Brave News]: add localised version of News Widgets #40298
* Fail to create non-compressed Solana NFT send transaction #40424
* Add new UD TLDs #40543
* Support running iOS app in compatibility mode on VisionOS #40579
* Strip behiiv link IDs from URLs #40716
* Enable New Playlist UI by default #40911
* Strip srsltid from all URLs #40912
* [Brave News]: Add it_IT and es_AR to list of enabled locales for News #40996\
* [iOS] - User cannot cancel history deletion #41148
* [Hackerone] Handle assign in signing of signature requests #41219
* [iOS] - Playlist Crash #41232
* [hackerone][iOS] Fix Reader Mode #41444
* [iOS] - Requesting Speech Recognizer from a Website crashes #41639
* Loading a bundled favicon sometimes can crash #41697
