### ISSUE TITLE
[ads] Transition diagnostics from brave://rewards-internals to brave://ads-internals

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#42034]
- [x] https://github.com/brave/brave-core/pull/39119
- [x] https://github.com/brave/brave-core/pull/39120
- [x] https://github.com/brave/brave-core/pull/39121
- [x] https://github.com/brave/brave-core/pull/39122
- [x] https://github.com/brave/brave-core/pull/39123
- [x] https://github.com/brave/brave-core/pull/39124
- [x] https://github.com/brave/brave-core/pull/39125
- [x] https://github.com/brave/brave-core/pull/39126

<img width="1392" height="1522" alt="Image" src="https://github.com/user-attachments/assets/95b20580-3f8d-438d-bd51-b954a7c53458" />
<img width="1392" height="1522" alt="Image" src="https://github.com/user-attachments/assets/0f397493-ecdd-46cf-9d56-55cbfd2c8c71" />
<img width="1392" height="1522" alt="Image" src="https://github.com/user-attachments/assets/06db94d1-7149-40aa-bcf9-81513ea8c9ab" />
<img width="1392" height="1522" alt="Image" src="https://github.com/user-attachments/assets/5a5a74af-6ed6-45b2-92d3-308352914497" />

**Comment by btlechowski** [comment]
Verified with

Brave | 1.95.93 Chromium: 152.0.7977.64 (Official Build) beta (x86_64)
-- | --
Revision | fcee9eb7a6d14a76c03af244997dc23f71c647c7
OS | Linux

### Diagnostics

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/4b828ee9-a79d-4e85-8107-b3c53c15d899" />

### Conversions

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/cce6ab65-6e1e-4180-9181-c7f1dd8109e9" />

### Events

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/1f7ab1eb-8da6-4af3-a452-a3100faccb80" />

### Logs

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/a73ec7fe-c979-4cea-aa2c-44e21bd9f8cb" />

**Comment by btlechowski** [comment]
Verification passed on Brave v1.95.97 on Lenovo TB-8506FS (Android 11.0)


### Diagnostics

<img width="800" height="1280" alt="Image" src="https://github.com/user-attachments/assets/40f5a9ed-cbd3-40a3-8c76-3915630cd62c" />

### Conversions

<img width="800" height="1280" alt="Image" src="https://github.com/user-attachments/assets/f86e4dbd-5315-43d4-90aa-a84d03102456" />

### Events

<img width="800" height="1280" alt="Image" src="https://github.com/user-attachments/assets/9ea03479-7cba-4a8f-bcc7-f1c9f00fb5ba" />

### Logs

<img width="800" height="1280" alt="Image" src="https://github.com/user-attachments/assets/9e560f41-448c-4077-9da1-d27b5d96840b" />
