### ISSUE TITLE
Enabling AdGuard URL Tracking Protection Filters can cause reddit.com to infinitely pend and cancel loading, lagging and sometimes crashing the browser

### ISSUE THREAD

**Issue by LegalizeNukes** [brave/brave-browser#42147]
### Description

If the "AdGuard URL Tracking Protection Filters" filter is enabled under the content filters setting for Brave, occasionally Reddit will infinitely pend and cancel loading hundreds of times per second. This will cause the browser to lag and occasionally cause the browser to crash as well.

This behavior described above can be observed in the network tab of the developer console.

Video showcasing the issue:

https://github.com/user-attachments/assets/a61ad223-9e49-47f9-a127-01d41e748d24

### Steps to reproduce

1. 
2. 
3. 

### Actual result

Failure of reddit.com to load, causing browser to lag and in some cases crash.

### Expected result

Reddit.com loads properly.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.123 Chromium: 130.0.6723.116 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LegalizeNukes** [comment]
I retested with just the AdGuard URL Tracking Protection Filters on (no additional or custom filters of any kind), with my shields settings being shown in the screenshot below, and the issue persisted. It may be an issue with the following parameter in the filter list itself:

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt
||reddit.com^$removeparam=rdt

In the video above, you can see that the Reddit link ends in ?rdt=52553.

Therefore, it may not be a Brave-specific issue and more so an issue with the filter list itself.

Shields settings (with only AdGuard URL Tracking Protection Filters enabled):
![Image](https://github.com/user-attachments/assets/5643314c-5caf-41ff-a351-4fe4f8c791bd)

**Comment by LegalizeNukes** [comment]
Seems to be fixed last time I checked in Brave v.1.76.
