### ISSUE TITLE
Mouse clicks do not interact with web pages on VR device (Meta Quest 2)

### ISSUE THREAD

**Issue by AlexRemix64** [brave/brave-browser#42189]
### Description

When using a USB mouse with an OTG adapter, mouse clicks do not interact with content on web pages, the mouse interacts without problems with the browser interface, certain interactions on web pages such as scrolling with the wheel and detecting the position of the cursor over a link also work.

(Sorry if it is poorly written, I am using a translator)

### Steps to reproduce

1. use an otg mouse
2. open any web page
4. click on anything on the web page

### Actual result

Mouse click does not interact with the web page
https://github.com/user-attachments/assets/fbb116a5-4334-4fe6-b707-0e2335675aa1

### Expected result

Mouse click interacts with the web page (To interact I'm using head tracking, hand tracking also works)
https://github.com/user-attachments/assets/1f77b12d-3a37-442e-b4ed-5b499c8da4db

### Reproduces how often

Easily reproduced

### Brave version

Brave Nightly 1.75.7, Chromium 131.0.6778.39![Image](https://github.com/user-attachments/assets/2216b6d0-3067-4ad1-a3f6-0d32d1d8a835)

### Device

- Brand/model: Meta Quest 2
- Android version: Android 12; Build/SQ3A.220605.009.A1

### Channel information

- [x] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I have already tried with stable and nightly versions of the browser and they have the same problem.

Mouse works fine in the browser interface
https://github.com/user-attachments/assets/188fc87a-2c89-4da2-adef-f7822488e0ce
