### ISSUE TITLE
Pending verification's/Release Notes from previous `1.73.x` milestones (formally `1.72.x`)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#42335]
Current list of issues that have been fixed/resolved via [`1.73.x - Release`](https://github.com/brave/brave-browser/milestone/522), [`1.73.x - Release #2`](https://github.com/brave/brave-browser/milestone/537) & [`1.73.x - Release #3`](https://github.com/brave/brave-browser/milestone/538) but haven't been verified by QA and should be completed before `1.73.x - Release` goes out on `iOS`:

* [x] Brave iOS crashes if Leo/Leo settings are accessed while Leo is disabled in flags #42150
* [x] [iOS] - VPN Receipt Not Found when Linking #42302
* [x] [iOS] - BraveVPN crashes if purchasing Leo AFTER VPN #42268
* [x] Change Leo to a 7-day Free Trial #37961
* [x] Bookmarks shortcut not shown for existing users [iPad] #42320
* [x] [iOS] - Update Leo Yearly ID on Nightly #41931
* [x] Playlist allowing playback while background playback continues from an open tab. #42344
* [x] Opening a Playlist item in a private tab opens it in regular mode the first time #42357
* [x] Solana swaps have very high rate of being dropped #42434
* [x] User unable to edit the order of media in playlist #42318
* [x] New Playlist UI can crash in the background due to excessive CPU usage #42408
* [x] New Playlist audio stops and starts momentarily when locking/unlocking the device #42468
* [x] Generic cosmetic filter list rules are not applied on some sites #42471
* [x] Playlist UI can be unresponsive and hang #42501
* [x] 1.70 Night mode not working on old.reddit.com and community.brave.com #41888
* [x] Brave crashes if using REWRITE when sending a query if Leo is opened via NTP #42443
* [x] [iOS] HTTPS-Only is broken in 1.73 #42542
* [x] http scheme is shown in the URL bar when visiting insecure sites #42070
* [x] [iOS] Add Transaltion for 1.73 #42622
* [x] Adding he, th, vi locales #42181

Current list of issues that were `release-notes/include` via [`1.73.x - Release`](https://github.com/brave/brave-browser/milestone/522), [`1.73.x - Release #2`](https://github.com/brave/brave-browser/milestone/537) & [`1.73.x - Release #3`](https://github.com/brave/brave-browser/milestone/538) and should be added into the release notes for the `1.73.x - Release` release:

* Support procedural cosmetic filtering #16935
* Favicons empty on NTP after loading webpage in Private mode #40935
* Changeable Shortcut Button #41031
* VPN Server doesn't immediately update after switch in menu #41051
* [Follow up to #39552] Title for Edit button needs to be updated to Done when editing custom SE #41210
* Playlist Items can't be deleted if the underlying offline cache is cleaned up incorrectly #41252
* Clean Copy URL feature should work when copying from the URL bar #41302
* Improve toolbar icon sizing/balance #41405
* Internationalization Support for Leo system prompts (For locales fr, de, it, es) #41554
* Bookmarking a base URL results in URL being sent to search engine #41910
* Brave iOS crashes if Leo/Leo settings are accessed while Leo is disabled in flags #42150
* Change Leo to a 7-day Free Trial #37961
* [iOS] - BraveVPN crashes if purchasing Leo AFTER VPN #42268
* User unable to edit the order of media in playlist #42318
* New Playlist UI can crash in the background due to excessive CPU usage #42408
* Playlist allowing playback while background playback continues from an open tab. #42344
* Opening a Playlist item in a private tab opens it in regular mode the first time #42357
* Generic cosmetic filter list rules are not applied on some sites #42471
* Playlist UI can be unresponsive and hang #42501
* New Playlist audio stops and starts momentarily when locking/unlocking the device #42468
* Solana swaps have very high rate of being dropped #42434
* 1.70 Night mode not working on old.reddit.com and community.brave.com #41888
* Brave crashes if using REWRITE when sending a query if Leo is opened via NTP #42443
* http scheme is shown in the URL bar when visiting insecure sites #42070
* Adding he, th, vi locales #42181
