### ISSUE TITLE
Add built-in Ethereum remote client / wallet / Dapp browser

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4494]
We're in the process of adding a first class Ethereum remote client / wallet feature to Brave by integrating a [fork of Metamask](https://github.com/brave/ethereum-remote-client) that we'll modify, enhance and maintain.   Sometimes native APIs that only Brave supports will be used, in those cases it probably doesn't make sense to upstream those parts.

We'll be upstreaming as much as we can to MetaMask. We have been, and will continue to collaborate with the MetaMask team as this work progresses.

Some bigger main differences will be:

- Initial UI will not include a browser action button, but be a menu item in the hamburger menu that opens up the full wallet view.  
- Dapp detection UI and popup UI will be used. The user will need to give permission to a page to see any available API (e.g. EIP 1102 `window.ethereum` and `web3`).
- It will use Brave branding.
- The UI will be modified in some ways.
- The seed key will be derived from the Brave key (currently only used for Sync) via a 1 way transformation.  Which means you only need to backup 1 set of BIP-39 style codewords and then you can use either or both of client side encrypted sync and the wallet.  Sync uses curve25519 whereas Ethereum uses secp256k1.

Rollout:

- Desktop will be rolled out first.
- Android is in the process of being re-written on top of Brave Core and it will support this feature after we add extension support here https://github.com/brave/brave-browser/issues/4493. We are planning to also tie into Samsung and HTC private enclave and / or wallet.

Future Brave rewards features will integrate and use this wallet support for P2P transactions.

---

## Some stats from MetaMask which are relevant :

Here's some stats for the month of April for MetaMask:

```
264,000 MAU
30% of active users confirm on chain transactions
1.5152M transactions 

Of 100% of network type activity:
- 63% of activity happens on mainnet
- 14.5% Ropsten
- 8% Rinkeby
- 6% Ganache
- 2% Kovan
- 6.5% Other

Of 100% of initiation type for transactions:
- 76% via popup from apps
- 24% via the user
Privacy Preserving Product Analytics (P3A)

Of 100% transaction types:
- 18% token transfers
- 12% ETH sends
- 3% approve
- 2.5% transfer from
- 0.2% contract deployment
- 64% Other contract interaction

Top mainnet sites by volume:
- 0x universe
- Cryptokitties
- Dice 2 Win
- Axie Infinity
- Fork Delta

Diversity of transactions to apps:
- Over 25 apps have over 5k transactions
```

Source:
https://medium.com/metamask/metamask-metrics-fbec0e2ceaa7

---

Here are the issues closed as part of this feature:
https://github.com/brave/brave-browser/issues?q=label%3Afeature%2Fcrypto-wallets+is%3Aclosed

**Comment by bbondy** [comment]
This is on Nightly, there will be follow up work but I'm closing!

**Comment by bbondy** [comment]
Added test plan above.

**Comment by kjozwiak** [comment]
@bbondy would running through https://github.com/brave/ethereum-remote-client/wiki/Testing be sufficient enough for QA verification? It's basically similar to what's outlined under https://github.com/brave/brave-browser/issues/4494#issue-445696447 but more detailed.

**Comment by bbondy** [comment]
sgtm

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

### Account Creation

- [x] There should be no prompt to opt-in to MetaMetrics telemetry during the onboarding process.
- [x] After password creation, a 24 word seed phrase should be generated for you, and it should process during the verification step.
- [x] The backup file should contain the intact 24 word seed phrase.

### Import & Recovery

- [x] Ensure that text fields for seed phrases only accept 24 word phrases
- [x] Upon successful recovery, the exact wallet should be loaded as the main account. Balances for each network should be retained.

### Settings page
- [x] There should be no About tab present --> Created #6271
- [x] Under the advanced tab, there should be no prompt for Mobile Sync --> Created #6272
- [x] The Info & Help tab should not be present in the main dropdown menu --> Created #6273
- [x] There should be no link to the MetaMask TOS
- [x] There should be no option to opt-in to MetaMetrics telemetry from the Security tab

### Branding
- [x] There are no appearances of the word MetaMask.
- [x] Links to MetaMask resources, such as websites and emails, should point to Brave resources.
- [x] In downloadable resources, such as the recovery key, the name MetaMask should not be in the filename. Created --> #6275
- [x] The MetaFox logo should not be present anywhere. (Check the welcome page, header, and login page)
- [x] Muli and Poppins fonts should be in use throughout the extension

### BAT
- [x] The BAT Token should be added by default to each eth network.

### Dapps

Use a dapp such as https://www.cryptokitties.co/ for testing

- [x] The Dapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Transactions relating to the dapp's functionality can be signed and completed via a pop-up notification
- [x] All dapp transactions where assets are sent/received show up in the account activity view within the extension

### Transactions

- [x] A QR code is visible for the generated address on Account Details
- [x] Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] For send transactions, Gas is calculated appropriately and can be adjusted for different speeds

### Accounts/Hardware
- [x] Multiple accounts be created via the dropdown menu, whether new or imported
- [x] An account can be created by connecting a Trezor hardware device
- [x] An account can be created by connecting a Ledger hardware device
 ERC-20 assets can be added to the token list

### Failed Transactions

<img width="969" alt="Screen Shot 2019-10-02 at 3 47 41 AM" src="https://user-images.githubusercontent.com/2602313/66026706-68d62400-e4c7-11e9-93b4-9c45c374e4dc.png">

<img width="406" alt="Screen Shot 2019-10-02 at 3 33 57 AM" src="https://user-images.githubusercontent.com/2602313/66026738-77244000-e4c7-11e9-8e84-c6d5da2a50d2.png">

### Successful Transactions

<img width="621" alt="Screen Shot 2019-10-02 at 3 40 41 AM" src="https://user-images.githubusercontent.com/2602313/66026784-8acfa680-e4c7-11e9-86eb-bcb9f782dd85.png">

<img width="335" alt="Screen Shot 2019-10-02 at 3 40 23 AM" src="https://user-images.githubusercontent.com/2602313/66026911-d1bd9c00-e4c7-11e9-9396-bbff31be04bb.png">

### Transaction appearing under Uphold

<img width="1194" alt="Screen Shot 2019-10-02 at 3 44 15 AM" src="https://user-images.githubusercontent.com/2602313/66026819-9de27680-e4c7-11e9-8009-3e7f12c15711.png">

### Connected to Nano Ledger

<img width="1008" alt="Screen Shot 2019-10-02 at 3 59 41 AM" src="https://user-images.githubusercontent.com/2602313/66027542-2281c480-e4c9-11e9-8e72-b690a889ac11.png">

<img width="449" alt="Screen Shot 2019-10-02 at 3 59 21 AM" src="https://user-images.githubusercontent.com/2602313/66027553-27467880-e4c9-11e9-8b5a-6ba53944234c.png">

<img width="344" alt="Screen Shot 2019-10-02 at 4 00 44 AM" src="https://user-images.githubusercontent.com/2602313/66027602-447b4700-e4c9-11e9-80d9-90791a12e79b.png">

### Connected to Trezor

<img width="1223" alt="Screen Shot 2019-10-02 at 4 13 07 AM" src="https://user-images.githubusercontent.com/2602313/66028381-f9faca00-e4ca-11e9-8ea5-b6cf6796401c.png">

**Comment by srirambv** [comment]
Most verification passed on 


Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

### Account Creation

- [x] There should be no prompt to opt-in to MetaMetrics telemetry during the onboarding process.
- [x] After password creation, a 24 word seed phrase should be generated for you, and it should process during the verification step.
- [x] The backup file should contain the intact 24 word seed phrase.

### Import & Recovery

- [x] Ensure that text fields for seed phrases only accept 24 word phrases
- [x] Upon successful recovery, the exact wallet should be loaded as the main account. Balances for each network should be retained.

### Settings page
- There should be no About tab present --> Blocked on #6271
- Under the advanced tab, there should be no prompt for Mobile Sync --> Blocked on  #6272
- The Info & Help tab should not be present in the main dropdown menu --> Blocked  #6273
- [x] There should be no link to the MetaMask TOS
- [x] There should be no option to opt-in to MetaMetrics telemetry from the Security tab

### Branding
- There are no appearances of the word MetaMask. Blocked on #6103, #6102, #6100, #6038
- Links to MetaMask resources, such as websites and emails, should point to Brave resources. Blocked on #6039, #6101, #6102, #6103, #6104
- In downloadable resources, such as the recovery key, the name MetaMask should not be in the filename. Blocked on #6275, #6281
- [x] The MetaFox logo should not be present anywhere. (Check the welcome page, header, and login page). This is blocked on #6038
- [x] Muli and Poppins fonts should be in use throughout the extension

### BAT
- [x] The BAT Token should be added by default to each eth network.

### Dapps

Use a dapp such as https://www.cryptokitties.co/ for testing

- [x] The Dapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Transactions relating to the dapp's functionality can be signed and completed via a pop-up notification
- [x] All dapp transactions where assets are sent/received show up in the account activity view within the extension

### Transactions

- [x] A QR code is visible for the generated address on Account Details
- [x] Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] For send transactions, Gas is calculated appropriately and can be adjusted for different speeds

### Accounts/Hardware
- [x] Multiple accounts be created via the dropdown menu, whether new or imported
- [x] An account can be created by connecting a Trezor hardware device
- [x] An account can be created by connecting a Ledger hardware device
- [x]  ERC-20 assets can be added to the token list

**Comment by srirambv** [comment]
Most verification passed on 


Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.523)

### Account Creation

- [x] There should be no prompt to opt-in to MetaMetrics telemetry during the onboarding process.
- [x] After password creation, a 24 word seed phrase should be generated for you, and it should process during the verification step.
- [x] The backup file should contain the intact 24 word seed phrase.

### Import & Recovery

- [x] Ensure that text fields for seed phrases only accept 24 word phrases
- [x] Upon successful recovery, the exact wallet should be loaded as the main account. Balances for each network should be retained.

### Settings page
- There should be no About tab present --> Blocked on #6271
- Under the advanced tab, there should be no prompt for Mobile Sync --> Blocked on  #6272
- The Info & Help tab should not be present in the main dropdown menu --> Blocked  #6273
- [x] There should be no link to the MetaMask TOS
- [x] There should be no option to opt-in to MetaMetrics telemetry from the Security tab

### Branding
- There are no appearances of the word MetaMask. Blocked on #6103, #6102, #6100, #6038
- Links to MetaMask resources, such as websites and emails, should point to Brave resources. Blocked on #6039, #6101, #6102, #6103, #6104
- In downloadable resources, such as the recovery key, the name MetaMask should not be in the filename. Blocked on #6275, #6281
- [x] The MetaFox logo should not be present anywhere. (Check the welcome page, header, and login page). This is blocked on #6038
- [x] Muli and Poppins fonts should be in use throughout the extension

### BAT
- [x] The BAT Token should be added by default to each eth network.

### Dapps

Use a dapp such as https://www.cryptokitties.co/ for testing

- [x] The Dapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Transactions relating to the dapp's functionality can be signed and completed via a pop-up notification
- [x] All dapp transactions where assets are sent/received show up in the account activity view within the extension

### Transactions

- [x] A QR code is visible for the generated address on Account Details
- [x] Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] For send transactions, Gas is calculated appropriately and can be adjusted for different speeds

### Accounts/Hardware
- [x] Multiple accounts be created via the dropdown menu, whether new or imported
- [x] An account can be created by connecting a Trezor hardware device
- [x] An account can be created by connecting a Ledger hardware device
- [x]  ERC-20 assets can be added to the token list

### Successful wallet creation
![image](https://user-images.githubusercontent.com/17010094/66069213-ea0bd600-e51c-11e9-9ff2-231fbca22556.png)

### Ledger Nano connected
![image](https://user-images.githubusercontent.com/17010094/66069235-f7c15b80-e51c-11e9-8d14-bcf7f7d48806.png)

### Trezor Connected
![image](https://user-images.githubusercontent.com/17010094/66069256-01e35a00-e51d-11e9-8e04-ace8c05abf06.png)

### Successful transaction
![image](https://user-images.githubusercontent.com/17010094/66069282-0c9def00-e51d-11e9-98dc-2bd3f2058c77.png)

### Transaction notification
![image](https://user-images.githubusercontent.com/17010094/66069302-158ec080-e51d-11e9-872e-a1b9358819b7.png)

### Dapp connect
![image](https://user-images.githubusercontent.com/17010094/66069364-37884300-e51d-11e9-9d73-5664e70bd3b5.png)

### Dapp sign
![image](https://user-images.githubusercontent.com/17010094/66069323-1fb0bf00-e51d-11e9-987f-0ee2e4914b2f.png)

### Insufficient funds
![image](https://user-images.githubusercontent.com/17010094/66069338-2808fa00-e51d-11e9-82b3-f727df8b63ce.png)

**Comment by radeksvarz** [comment]
> Android is in the process of being re-written on top of Brave Core and it will support this feature after we add extension support here #4493. 

Can you please elaborate, why it needs to wait for it?
