### ISSUE TITLE
[Meta issue] Customizing settings menu

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4819]
There are a lot of Chromium related items in Settings menu:
We need to remove them or replace to Brave's

- [x] Cleanup from main settings screen https://github.com/brave/brave-browser/issues/6173
- [x] Add Search engine section in main settings screen (https://github.com/brave/brave-browser/issues/6191)
- [x] Add Welcome Tour to basic category in main settings screen 
([Done] UI stub: https://github.com/brave/brave-browser/issues/6343)
(Functionality: https://github.com/brave/brave-browser/issues/6548)
- [x] Add Display category in main settings screen https://github.com/brave/brave-browser/issues/4851 by @yrliou 
- [x] Add Control category in main settings screen https://github.com/brave/brave-browser/issues/6293
- [x] Cleanup from site settings screen https://github.com/brave/brave-browser/issues/6174
- [x] Add `Brave Rewards` item in `Advanced` section https://github.com/brave/brave-browser/issues/6829 by @yrliou 
- [ ] Styles such as text colors

**Comment by srirambv** [comment]
@SergeyZhukovsky  can this be closed since most are done?

**Comment by SergeyZhukovsky** [comment]
yep, closing that, only colours left that will be ported in a general port from an old repo.
