### ISSUE TITLE
BraveRewardsBrowserTest.* tests frequently time out

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5397]
Brave Rewards tests are frequently timing out which causes each PR to take longer and also takes longer for people checking tests locally on their tasks.

As an example:

> BraveRewardsBrowserTest.ProcessPendingContributions (TIMED OUT)

But there are others too (8) that frequently timeout. 

cc @NejcZdovc 

Here are some ideas for cleaning up tests:

- [x] Add a method to enable Rewards without using the Rewards Page UI, and switch tests to it where possible. (#7002)
- [x] Replace use of sleep/polling with a `MutationObserver` that will watch for the page to be modified. (https://github.com/brave/brave-browser/issues/7060)
- [x] Switch tests to use `TipViaCode` where possible. (https://github.com/brave/brave-browser/issues/7184)
- [x] Add a method to claim an initial grant without going through the Rewards Page or Rewards Panel UI, and switch tests to using it where possible. (https://github.com/brave/brave-browser/issues/9129)
- [ ] Add a method to open the Site Banner without going through the Rewards Panel, and switch tests to using it where possible.
- [x] Move utility functions into a separate file.
- [x] Split Rewards Service tests into multiple files based on test category. (https://github.com/brave/brave-browser/issues/9204)

**Comment by bsclifton** [comment]
@NejcZdovc is this still a problem? Or can we close this out

**Comment by NejcZdovc** [comment]
@bsclifton this is an epic. We still have couple of them to complete, before we can close this one.

**Comment by kjozwiak** [comment]
Just a heads up, created https://github.com/brave/brave-browser/issues/9339. Looks like `BraveRewardsBrowserTest.NotVerifiedWallet` has been failing intermittently here and there. I'm not sure if this work will fix that issue but figured I would mention it here.

**Comment by kjozwiak** [comment]
Just an update, still seeing the following failure from time to time:

```
03:29:38  [  FAILED  ] BraveRewardsBrowserTest.ProcessPendingContributions, where TypeParam =  and GetParam() =  (37759 ms)
03:29:38  [539/540] BraveRewardsBrowserTest.ProcessPendingContributions (38025 ms)
03:29:44  [540/540] BraveRewardsBrowserTest.SplitProcessorAutoContribution (5241 ms)
03:29:44  1 test failed:
03:29:44      BraveRewardsBrowserTest.ProcessPendingContributions (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2186)
```

**Comment by NejcZdovc** [comment]
This was fixed here https://github.com/brave/brave-browser/issues/9687, so probably just not running the latest code

**Comment by bsclifton** [comment]
@NejcZdovc should we close this issue out?

**Comment by NejcZdovc** [comment]
closing as nothing new is planned for this and browser tests are stable now
