### ISSUE TITLE
Manual test run on Linux for 0.68.x - Release

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5747]
## Per release specialty tests
 - [ ] Use new adblock-rust library.([#4793](https://github.com/brave/brave-browser/issues/4793))
 - [x] Downloads not being instantly displayed under "brave://downloads" until window resize.([#5330](https://github.com/brave/brave-browser/issues/5330))
 - [x] Seek (forward or backward) on vimeo video messes up entire AC table.([#5725](https://github.com/brave/brave-browser/issues/5725))

### Installer

- [x] Check that installer is close to the size of last release
- [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x] Make sure that data from the last version appears in the new version OK
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Installed extensions are retained and work correctly
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Unpinned tabs can be pinned
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained

### Widevine

- [x] Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x] Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Brave Ads

- [x] Upgrade Cases
  - [x] Verify when updating from the previous version Ads info in the panel is not lost
  - [x] Update to latest version from 0.62.51 (or a version without Ads available). Verify you are notified to try ads via a BAT logo notification but Ads are not automatically turned on for you.
  - [x] Update to latest version from some Ads enabled versions (0.63.x, 0.64.x). Verify Ads status (on/off) is the same as it was prior to update.

### Rewards

- [x] Upgrade from older version
  - [x] Verify the wallet balance is retained and wallet backup code isn't corrupted
  - [x] Verify auto-contribute list is not lost after upgrade
  - [x] Verify tips list is not lost after upgrade
  - [x] Verify wallet panel transactions list is not lost after upgrade

## Update tests

- [x] Verify visiting `brave://settings/help` triggers update check
- [x] Verify once update is downloaded, prompts to `Relaunch` to install update

## Chromium upgrade tests

- [x] Verify `brave://gpu` on Brave and `chrome://gpu` on Chrome are similar for the same Chromium version on both browsers

#### Components
- [x]  Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components
- [x] Restart the browser, load brave://components, wait for 8 mins and verify that no component shows any errors
- [x] Verify Brave Local Data Updater, Brave Ad Block Updater, Brave Tor Client Updater (Mac), PDF Viewer (PDF.js), Brave HTTPS Everywhere Updater have non-zero version numbers

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS
