### ISSUE TITLE
Migrate Ledger state from JSON to a database to optimise memory and performance

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5815]
Migrate Ledger state from JSON to a database to optimise memory and performance which will become more important for mobile

- [x] Refactor and migrate Rewards category from category to type #6350
- [x] Refactor loadFromJson from RapidJSON to base::JSONReader #6351 
- [ ] Migrate user settings from JSON to Preferences #7024

**Comment by tmancey** [comment]
Supercedes https://github.com/brave/brave-browser/issues/3892 as all Ledger state is being migrated from JSON to a database

**Comment by tmancey** [comment]
https://github.com/brave/brave-browser/issues/6350

**Comment by NejcZdovc** [comment]
closing this one as we have the only issue left tracked and majority of stuff was already done
