### ISSUE TITLE
Grant virtualization - Phase 1

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6078]
In phase 1 we will not yet remove old contribution flow. We will still ping server for balance, but we will only get user funds in brave wallet back. So we will need to combine 3 things now: grants (blinded tokens), user funds (brave wallet) and external wallet (uphold). Sum of this 3 will give you total. 

For contribution user will have two options on how to do things. If we will detect that you have blinded tokens we will use that. If you have only portion that you can use we will first use blinded tokens and then take user funds in brave wallet and at the last step external wallet if you have it connected. If you don't have blinded tokens we will first check user funds and then external wallet. User funds and external wallet will go through the old process for now.

**Comment by LaurenWags** [comment]
Additional Test Plan for grant virtualization:

- Using a self-funded anon wallet, verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution 
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.
   - [ ] Confirm if you back up this wallet and restore on a clean profile your wallet balance is intact (minus any used BAT) as expected - no BAT is lost.


- Using an anon wallet funded only via a virtual grant (such as UGP), verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution 
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.
   - [ ] Confirm if you back up this wallet and restore on a clean profile, your wallet balance is 0 since the UGP grant was virtualized.


- Using an anon wallet funded with a mix of virtual and non-virtual BAT (such as self funded + UGP grant), verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution 
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.
   - [ ] Confirm if you back up this wallet and restore on a clean profile, only the self-funded BAT (minus any used) is restored. No UGP or Ad grant BAT is restored.


- Using an anon wallet funded with a mix of old and new grants (such as UGP grant + old ad grant), verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution *note, due to issue https://github.com/brave/brave-browser/issues/7709 the AC part will not be possible until that is fixed.
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.
   - [ ] Confirm if you back up this wallet and restore on a clean profile, only the self-funded BAT (minus any used) is restored. No UGP or Ad grant BAT is restored.


We should also verify that existing User Wallet functionality is still working as expected:
- Using a fully KYC'd user wallet, verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution *note, due to issue https://github.com/brave/brave-browser/issues/7595 the AC part will not be possible until that is fixed.
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.
   

- Using a connected but not KYC'd user wallet, verify you are able to
   - [ ] do a one time tip
   - [ ] a monthly tip (contribution)
   - [ ] auto contribution *note, due to issue https://github.com/brave/brave-browser/issues/7595 the AC part will not be possible until that is fixed.
   - [ ] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [ ] Confirm wallet balance decreases accurately.

- [ ] Confirm "Claim" process for self-funded BAT is still working:
   - enable rewards
   - restore wallet with some self-funded BAT (not from a grant)
   - connect kyc'd uphold account
   - make sure that self funded BAT is transferred to uphold card

**Comment by LaurenWags** [comment]
Verification in progress using

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/3918
* Verified test plan from https://github.com/brave/brave-browser/issues/6078#issuecomment-578799636 :

**PASS** - Scenario 1: Using a self-funded anon wallet, verify you are able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirm wallet balance decreases accurately. (Original wallet balance was 50 BAT, it is now 43 as expected)
   - [x] Confirm if you back up this wallet and restore on a clean profile your wallet balance is intact (minus any used BAT) as expected - no BAT is lost.

<img width="804" alt="scneario 1 anon-6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73582008-5cec7580-4459-11ea-89c5-8e41b2be5064.png">


**PASS** - Scenario 2: Using an anon wallet funded only via a virtual grant (such as UGP), verify you are able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirm wallet balance decreases accurately. (Original wallet balance was 17.5 BAT, it is now 0 BAT as expected)
   - [x] Confirm if you back up this wallet and restore on a clean profile, your wallet balance is 0 since the UGP grant was virtualized.

<img width="774" alt="scenario 2 ugp-6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73582019-637aed00-4459-11ea-9dd4-dcb431b192aa.png">


**PASS** - Scenario 3: Using an anon wallet funded with a mix of virtual and non-virtual BAT (such as self funded + UGP grant), verify you are able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirm wallet balance decreases accurately. (27+17.5=44.5 BAT to start with, wallet is now correctly at 19.5)
   - [x] Confirm if you back up this wallet and restore on a clean profile, only the self-funded BAT (minus any used) is restored. No UGP BAT is restored.

<img width="789" alt="scenario 3 anon-and-ugp-6078" src="https://user-images.githubusercontent.com/28145373/73582025-6aa1fb00-4459-11ea-903b-e83528ac6a22.png">


**PAS** - Scenario 4: Using an anon wallet funded with a mix of old and new grants (such as UGP grant + old ad grant), verify you are able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirm wallet balance decreases accurately. (Original balance was 21 BAT, it is now correctly 5 BAT)
   - [x] Confirm if you back up this wallet and restore on a clean profile, no UGP or Ad grant BAT is restored because they were virtualized.

<img width="787" alt="scenario 4 ugp-and-ads-6078" src="https://user-images.githubusercontent.com/28145373/73582029-72619f80-4459-11ea-9cd7-5caa73126527.png">


**PASS** - Scenario 5: Using a fully KYC'd user wallet, verify you are able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirm that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirm wallet balance decreases accurately. (Starting balance was 103 BAT, wallet balance is now showing 87 BAT.)

<img width="775" alt="scenario 5 KYCd-6078 and 7526" src="https://user-images.githubusercontent.com/28145373/73582036-7a214400-4459-11ea-94f1-f3f13ebe801e.png">

Logged issue for trouble with connected but not KYC'd accounts for tip, recurring tip, AC (Scenario 6): https://github.com/brave/brave-browser/issues/7999

Waiting for sandbox account to be verified - Scenario 7: Confirm "Claim" process for self-funded BAT is still working
   - enable rewards
   - restore wallet with some self-funded BAT (not from a grant)
   - connect kyc'd uphold account
   - [ ] make sure that self funded BAT is transferred to uphold card
