### ISSUE TITLE
Manual test run on Linux for Ethereum Remote Client 1.0.11

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6531]
## Per release specialty tests
 - [x] Metamask icons in connect hardware screen.([#6038](https://github.com/brave/brave-browser/issues/6038))
 - [ ] Missing translations for custom text on crypto wallet.([#6289](https://github.com/brave/brave-browser/issues/6289))
 - [x] Https://brave.com/cryptocurrency-risk links to a 404 page.([#6485](https://github.com/brave/brave-browser/issues/6485))

## Branding

- [x] Verify there are no appearances of the word MetaMask
- [x] Verify links to MetaMask resources such as websites and email should point to Brave resources
- [x] Verify all downloadable resources (Seed/Logs) contains Brave file names
- [x] Verify MetaFox logo is not present on any screen

## Component

- [x] Verify Ethereum client component is downloaded when you open brave://wallet for the first time
- [x] Verify Ethereum client component is successfully updated and doesn't corrupt the browser wallet
- [x] Delete component folder. Verify the component is downloaded successfully after browser relaunch

## Ðapps

- [x] Verify Ðapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Verify Ðapp transactions where assets are set/received show up in the account activity view within the extension

## Import & Recovery

- [x] Verify you can import Brave Crypto Wallet using 24 seed words 
- [x] Verify you can import MetaMask Wallet using only 12 seed words

## Transactions

- [x] Verify Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Verify Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] Verify a successful transaction can be done on a restored wallet

## Hardware

- [x] Verify you can link hardware wallet using Trezor and unlock the wallet 
- [x] Verify you can link hardware wallet using Ledger Nano and unlock the wallet

**Comment by srirambv** [comment]
Verification complete on component `0.1.17`
