### ISSUE TITLE
Add tests for downloading adblock / tracking protection data files

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#676]
Carried over from https://github.com/brave/browser-laptop/issues/125

The tests should:
- [ ] Check for proper handling for 404 if adblock data file isn't uploaded correctly
- [ ] Check for proper handling if adblock server is offline
- [ ] Check for proper handling if time elapsed since last check is > 1 day
- [ ] Check if there is proper handling when reading cached storage from disk
- [ ] Check if there is proper handling when a 2nd window is open
- [ ] Check for proper handling when etags match
- [ ] Check for proper handling when etags do not match

**Comment by bsclifton** [comment]
This issue hasn't had an update in a while - it's met the criteria for being stale. The issue is going to be closed for now. If this is still a problem, please leave a comment or re-open the issue. Thanks!
