### ISSUE TITLE
Grant virtualization - Phase 2

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6899]
Follow up of https://github.com/brave/brave-browser/issues/6078

**Completed**
- [x] add check for public key (public keys from initial promotion fetch should be checked against public key that is send with signed tokens) https://github.com/brave/brave-browser/issues/6939  -> https://github.com/brave/brave-core/pull/4008
- [x] if unblinded token expires we need to remove it https://github.com/brave/brave-browser/issues/7022 -> https://github.com/brave/brave-core/pull/4025
- [x] handle promotion expiration (and unblinded tokens with it) https://github.com/brave/brave-browser/issues/6947 -> https://github.com/brave/brave-core/pull/4035
- [x] add migration flow for old grants https://github.com/brave/brave-browser/issues/6937 -> https://github.com/brave/brave-core/pull/4101
- [x] add retry logic for contribution https://github.com/brave/brave-browser/issues/6940 -> https://github.com/brave/brave-core/pull/4372
- [x] implement new claim api for uphold where we send unblinded tokens to the server and then transfer it to uphold https://github.com/brave/brave-browser/issues/8354 -> https://github.com/brave/brave-core/pull/4708

**In progress**
- [ ] add unit tests https://github.com/brave/brave-browser/issues/6949 -> https://github.com/brave/brave-core/pull/4344

**Backlog**
- [x] do not delete tokens https://github.com/brave/brave-browser/issues/8181

**Blocked**
- [ ] backup and restore of unblinded tokens https://github.com/brave/brave-browser/issues/6938 **(waiting on server to implement new flow)**
- [ ] when doing AC with uphold we should have API that convert BAT to blinded tokens https://github.com/brave/brave-browser/issues/7595
- [ ] remove anonize and old contribution code https://github.com/brave/brave-browser/issues/7717
- [ ] implement new create persona api https://github.com/brave/brave-browser/issues/8428
- [ ] implement wallet create attestation platform agnostic https://github.com/brave/brave-browser/issues/6945 **(need to define flow)**

**Comment by NejcZdovc** [comment]
all was done
