### ISSUE TITLE
Manual test run on OS X for Ethereum Remote Client 1.0.13

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7033]
## Per release specialty tests
 - [x] Brave wallet scroll.([#6528](https://github.com/brave/brave-browser/issues/6528))
 - [x] Remove/Replace MetaFox icon from connect wallet popup.([#6534](https://github.com/brave/brave-browser/issues/6534))
 - [x]  Crypto Wallets add tokens to account button hidden in side-bar.([#6824](https://github.com/brave/brave-browser/issues/6824))
 - [x] Crypto Wallets does not have latest proxy caching.([#7032](https://github.com/brave/brave-browser/issues/7032))

## Branding

- [x] Verify there are no appearances of the word MetaMask
- [x] Verify links to MetaMask resources such as websites and email should point to Brave resources
- [x] Verify all downloadable resources (Seed/Logs) contains Brave file names
- [x] Verify MetaFox logo is not present on any screen

## Component

- [x] Verify Ethereum client component is downloaded when you open brave://wallet for the first time
- [x] Verify Ethereum client component is successfully updated and doesn't corrupt the browser wallet
- [x] Delete component folder. Verify the component is downloaded successfully after browser relaunch

## Ðapps

- [x] Verify Ðapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Verify Ðapp transactions where assets are set/received show up in the account activity view within the extension

## Import & Recovery

- [x] Verify you can import Brave Crypto Wallet using 24 seed words 
- [x] Verify you can import MetaMask Wallet using only 12 seed words

## Transactions

- [x] Verify Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Verify Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] Verify a successful transaction can be done on a restored wallet

## Hardware

- [x] Verify you can link hardware wallet using Trezor and unlock the wallet 
- [x] Verify you can link hardware wallet using Ledger Nano and unlock the wallet
