### ISSUE TITLE
Implement Brave Publisher Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7298]
**Tasks:**

- [x] Parse v3 Brave Ads catalog (https://github.com/brave/brave-browser/issues/7299)
- [x] Persist v3 Brave Ads catalog (https://github.com/brave/brave-browser/issues/7300)
- [x] Implement API to return a list of eligible Publisher Ads based upon specified sizes (https://github.com/brave/brave-browser/issues/7301)
- [x] Implement API to return a list of all eligible Publisher Ads (https://github.com/brave/brave-browser/issues/7426)
- [x] Implement API to show a Publisher Ad (https://github.com/brave/brave-browser/issues/7302)
- [x] Implement API to enable/disable publisher ads (https://github.com/brave/brave-browser/issues/7305)
- [x] Implement UI to enable/disable publisher ads (https://github.com/brave/brave-browser/issues/7430)
- [x] Implement API to notify when a Publisher Ad was viewed (https://github.com/brave/brave-browser/issues/7427)
- [x] Implement API to notify when a Publisher Ad was clicked (https://github.com/brave/brave-browser/issues/7428)
- [x] Add Publisher Channel Id to viewed, clicked and landed confirmations for Publisher Ads (https://github.com/brave/brave-browser/issues/7303)
- [x] Implement API to ask if Publisher Ads are available in the catalog bundle for a publisher to optimize performance (https://github.com/brave/brave-browser/issues/8122)
- [x] Implement API to provide a list of creative URL images to pre-cache (https://github.com/brave/brave-browser/issues/8516)
- [x] Implement API to purge creative URL images that have expired (https://github.com/brave/brave-browser/issues/8517)
- [ ] Copy/UI layout changes (https://github.com/brave/brave-browser/issues/7938)
    - [x] Copy changes
    - [ ] UI layout changes

***Landed confirmations are handled by the `bat-native-ads` library as part of https://github.com/brave/brave-browser/issues/7302**
***Dismissed confirmations are not required for Publisher Ads**
***Ad rewards are handled by the `bat-native-ads` library as part of https://github.com/brave/brave-browser/issues/7427 and https://github.com/brave/brave-browser/issues/7428**
***See specification for testing**

**Comment by tmancey** [comment]
Closing issue as codebase is stale
