### ISSUE TITLE
Things to be imported from browser-laptop during migration or manual import

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#730]
- [ ]  Import favicons from Brave #440 
- [ ] Cookies and passwords (Snap on Linux) #531 
- [x] Search Engines (should be fixed with  #731)
- [ ] Site Shields settings (requires #348 to be implemented first)
- [ ] Saved site settings 
- [ ] New tab setting (show image/dashboard)
- [x] Referral promo code #1294

cc: @bbondy

**Comment by LaurenWags** [comment]
++ on this esp site shield settings - would be a major pain to have to reset those.

**Comment by NejcZdovc** [comment]
+ payments into rewards

**Comment by LaurenWags** [comment]
@NejcZdovc covered by https://github.com/brave/brave-browser/issues/1215 possibly?

**Comment by NejcZdovc** [comment]
@LaurenWags correct

**Comment by garrettr** [comment]
Recent discussions have suggested we prioritize at least the following subset of "things to be imported" for the 1.0 milestone:
- Site Shield settings
- Saved sites settings

**Comment by bsclifton** [comment]
Closing as this code is now removed
