### ISSUE TITLE
Manual test run on OS X for Ethereum Remote Client 1.0.15

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7409]
## Per release specialty tests
 - [x] Get help link on connect hardware points to Metamask support page.([#6039](https://github.com/brave/brave-browser/issues/6039))
 - [x] "Learn more" under "Remove Account" pointing to MM Zenhub.([#6171](https://github.com/brave/brave-browser/issues/6171))
 - [x] Deposit transactions are not listed .([#6535](https://github.com/brave/brave-browser/issues/6535))
 - [x] Experimental 3box feature should be disabled.([#7381](https://github.com/brave/brave-browser/issues/7381))
 - [x] Rebase Crypto Wallets to MetaMask upstream .([#7408](https://github.com/brave/brave-browser/issues/7408))

## Branding

- [x] Verify there are no appearances of the word MetaMask
- [x] Verify links to MetaMask resources such as websites and email should point to Brave resources
- [x] Verify all downloadable resources (Seed/Logs) contains Brave file names
- [x] Verify MetaFox logo is not present on any screen

## Component

- [x] Verify Ethereum client component is downloaded when you open brave://wallet for the first time
- [x] Verify Ethereum client component is successfully updated and doesn't corrupt the browser wallet
- [x] Delete component folder. Verify the component is downloaded successfully after browser relaunch

## Ðapps

- [x] Verify Ðapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Verify Ðapp transactions where assets are set/received show up in the account activity view within the extension

## Import & Recovery

- [x] Verify you can import Brave Crypto Wallet using 24 seed words 
- [x] Verify you can import MetaMask Wallet using only 12 seed words

## Transactions

- [x] Verify Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Verify Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] Verify a successful transaction can be done on a restored wallet

## Hardware

- [x] Verify you can link hardware wallet using Trezor and unlock the wallet 
- [x] Verify you can link hardware wallet using Ledger Nano and unlock the wallet

**Comment by kjozwiak** [comment]
#### `Dapp` transaction under https://memefactory.io:

https://etherscan.io/tx/0x92270b55ec8ee74ab36df5b3aefdf5eb482e3a1bd608d3bf1c3512dde72e73ef

<img width="360" alt="Screen Shot 2020-01-10 at 2 24 03 PM" src="https://user-images.githubusercontent.com/2602313/72180345-fa9dd900-33b4-11ea-9c88-ff8f0cc7c9f1.png">

#### `Dapp` transaction under https://www.cryptokitties.co/

https://etherscan.io/tx/0x0c2aee5ffd9afd5022e1adc0b207a212ee5abd8c642fc7f6169fb5762db0efc1

<img width="624" alt="Screen Shot 2020-01-10 at 2 26 14 PM" src="https://user-images.githubusercontent.com/2602313/72180445-3042c200-33b5-11ea-8584-5f4f137874c1.png">
