### ISSUE TITLE
Tracking issue for browser crash on Android-Beta

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7918]
## Description 
Browser crashes for the following sites 

- [x] RST.ua (#7925)
- [x] http://android.mobile-review.com/articles/63573/ (#7926)
- [x] https://epaper.livemint.com (Nasty crashing not able to reuse browser again) (#7927)
- [x] Android play store crash in toolbar (#7931)
- [x] Android play console crash in rewards (#7929)
- [x] Android play store crash in sync (#7932)
