### ISSUE TITLE
[meta] Mozilla Location Service API key expiring on 2020-03-01

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7953]
According to
https://blog.mozilla.org/services/2019/09/03/a-new-policy-for-mozilla-location-service/, we will get cut off of the Mozilla Location service on 2020-03-01.

These things need to happen before then:
- [x] stand up a fallback service (brave/devops#2625, brave/devops#2633, brave/devops#2634)
- [x] add our location service to our privacy policy (https://github.com/brave/internal/issues/680)
- [x] proxy requests (https://github.com/brave/devops/issues/2457, https://github.com/brave/brave-browser/issues/8167, brave/browser-android-tabs#2564, brave/brave-ios#2343)
- <s>announce the change in a community/blog post (@tomlowenthal)</s>

The next steps after that will be to:
- switch to [OS location services](https://github.com/brave/brave-browser/issues/8451)
- enable [MaxMind DB updates](https://github.com/brave/devops/issues/2635) on the server
