### ISSUE TITLE
Manual test run on Linux for Ethereum Remote Client 1.0.16

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8015]
## Per release specialty tests
 - [x] Import wallet learn more links to MM help page.([#6103](https://github.com/brave/brave-browser/issues/6103))
 - [x] JSON file import help links to MM help page.([#6104](https://github.com/brave/brave-browser/issues/6104))
 - [x] Crypto Wallet dark theme issues.([#6381](https://github.com/brave/brave-browser/issues/6381))
 - [x] Wallet backup screen should be responsive to browser size .([#7045](https://github.com/brave/brave-browser/issues/7045))
 - [x] Clicking on `Restore account? Import using account seed phrase` does nothing.([#7537](https://github.com/brave/brave-browser/issues/7537))
 - [x] Learn more on connect wallet popup links to MM support page.([#7695](https://github.com/brave/brave-browser/issues/7695))
 - [x] Removing "Choose a type to set up" from brave://wallet.([#7791](https://github.com/brave/brave-browser/issues/7791))
 - [x] Connect to wallet popup needs to be responsive.([#7882](https://github.com/brave/brave-browser/issues/7882))

## Branding

- [x] Verify there are no appearances of the word MetaMask
- [x] Verify links to MetaMask resources such as websites and email should point to Brave resources
- [x] Verify all downloadable resources (Seed/Logs) contains Brave file names
- [x] Verify MetaFox logo is not present on any screen

## Component

- [x] Verify Ethereum client component is downloaded when you open brave://wallet for the first time
- [x] Verify Ethereum client component is successfully updated and doesn't corrupt the browser wallet
- [x] Delete component folder. Verify the component is downloaded successfully after browser relaunch

## Ðapps

- [x] Verify Ðapp can successfully connect to your crypto wallets account, signed via a pop-up notification
- [x] Verify Ðapp transactions where assets are set/received show up in the account activity view within the extension

## Import & Recovery

- [x] Verify you can import Brave Crypto Wallet using 24 seed words 
- [x] Verify you can import MetaMask Wallet using only 12 seed words
- [x] Verify you can restore Brave CW/MM account from the login screen

## Transactions

- [x] Verify Eth/ERC-20 tokens can be received at the addresses generated for your account
- [x] Verify Eth/ERC-20 tokens can be sent to other addresses from your account
- [x] Verify a successful transaction can be done on a restored wallet

## Hardware

- [x] Verify you can link hardware wallet using Trezor and unlock the wallet 
- [x] Verify you can link hardware wallet using Ledger Nano and unlock the wallet

**Comment by srirambv** [comment]
Looks good component update looks good and works fine
