### ISSUE TITLE
IPFS Integration - Roadmap and discussion

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#819]
Carried over from https://github.com/brave/browser-laptop/issues/9556

@diasdavid wrote:
> Hi there brave team! I'm David, from the IPFS project.
> 
> I'm looking into the IPFS integration into the Brave browser and I'm hoping you could clarify some design details, just so that I'm sure I understand how everything is pieced together.
> 
> Right now, the most straightforward way is to mimic what WebTorrent did and create an extension. I've noticed that it gets its own WebPage, located at https://github.com/brave/browser-laptop/tree/master/js/webtorrent and that this page gets bundled in with WebPack -- https://github.com/brave/browser-laptop/blob/master/webpack.config.js#L153-L169 --. I can create something similar, no problem.
> 
> - Where do I capture `ipfs://`, `dweb://` and even `http(s)://ipfs.io/ipfs/` urls so that they get resolved through the IPFS Extension?
> - How do I create a control panel like the one I see Dashlane/1Password
> ![image](https://user-images.githubusercontent.com/1211152/27265339-a8a1338c-548b-11e7-9da0-bf27f2e23cda.png)
> - Currently, we have full web applications that are hosted and served through IPFS. We can start by just adding IPFS support for download of files but ideally, we would like to see pages be rendered. Any advice on how to hint Brave the content type? Drop it into the dom like it's 🔥?
> 
> Thanks in advance! Super excited to do this :)

**Comment by drbh** [comment]
What are the next steps to shipping Brave with IPFS?

My understanding is that Brave is going to use a custom build of Chromium because it does not support custom protocols without the `web+` prefix. 

Quoted from [arewedistributedyet/issues/23](https://github.com/arewedistributedyet/arewedistributedyet/issues/23)
> Brave will use custom build of Chromium: they could override whitelisting rules as a part of the build, but it makes more sense to try to solve it upstream in Chromium first.

However he road block is upstream; getting Chromium to support DWeb protocols - which seemingly has been officially started on Aug 17 2018

Quoted by asanka@chromium.org from [/chromium/issues/detail?id=651311](https://bugs.chromium.org/p/chromium/issues/detail?id=651311)
> I'll start an intent-to-implement.

Assuming the protocols get supported and are included in a near future build of Chromium. What will the general integration process look like?

Will the `navigator.registerProtocolHandle` still be used or will this not be needed anymore?

If it is used, is the sample code below seem close to the general concept? Redirecting ipfs:// traffic to a ipfs gateway?
```
navigator.registerProtocolHandler("ipfs",
                                  "https://gateway.ipfs.io/ipfs/%s",
                                  "IPFS");
```

**Comment by drbh** [comment]
> The go-ipfs is shipped and orchestrated by Brave: would be something similar to Tor Tabs (very good UX, IPFS works out of the box)

I really like shipping go-ipfs with Brave! 👍 

Not only is it great UX, but it add a competitive advantage to Brave from a product growth perspective.  Similar to how Tor Tabs incentives users to move from the commercial browsers to Brave (because of its added feature set)

How do we go about adding a program the way Tor Tabs did.

Looking through the project in brave-laptop I find

[browser-laptop/blob/master/app/tor.js](https://github.com/brave/browser-laptop/blob/master/app/tor.js)

```
/**
 * Tor daemon management.
 *
 * This doesn't actually manage the tor daemon: the parts that did are
 * commented out.  Rather it just watches the tor daemon's control
 * port file for activity and connects to its control socket.
 *
 * @module tor
 */
```

and 
[browser-laptop/blob/master/tools/package_tor.js](https://github.com/brave/browser-laptop/blob/master/tools/package_tor.js)

which seems to pull the binaries from S3 (interesting)

```
const torS3Prefix = 'https://s3.us-east-2.amazonaws.com/demo-tor-binaries/'
var torPath = process.argv.slice(2)[0] // npm run package-tor torPath
if (torPath === undefined) {
  torPath = path.join('app', 'extensions', 'bin')
}
```

Does this suggest we need to host the IPFS go binaries somewhere and these are pulled in and installed with Brave?

Is there someone who worked on TorTabs and has insight to the process of shipping a binary with Brave?

**Comment by bsclifton** [comment]
cc: @riastradh-brave @darkdh

**Comment by drbh** [comment]
@bsclifton thanks for suggesting help from @riastradh-brave and @darkdh. 

Looking at their commits pertaining to Tor build packaging and the build_tor_scripts I've pieced together these basic next steps:

- [ ] Build go-ipfs from source for all supported platforms `linux`, `darwin` and `win32` like [brave/tor_build_scripts](https://github.com/brave/tor_build_scripts) builds Tor
- [ ] update the `tools/buildPackage.js` file to include ipfs binaries
- [ ] add new file called `tools/package_ipfs.js` that fetches and verifies the signature a precompiled ipfs binary

i've added a repo at [/drbh/ipfs_build_scripts](https://github.com/drbh/ipfs_build_scripts) as a starting point for the build scripts.

also i've created a fork of brave/browser-laptop and added a branch called ipfsPackageBuild at [/drbh/browser-laptop](https://github.com/drbh/browser-laptop/tree/ipfsPackageBuild) with what seems like the necessary files for brave to fetch the binaries.

The signature need to be updated in package_ipfs after the binaries are correctly built, and some adjustments to ipfs version are needed. 

I'm most confused about the build process for the ipfs_build_scripts, because the tor_build_scripts seem to add dependencies in a specific way like `openssl`. Since go-ipfs's only dependency seems to be Golang, can we build the binaries straight from a `golang:1.10-stretch` base image?

If anyone has insight on the build process this would be greatly appreciated. I hope my boilerplate code is helpful.

**Comment by lidel** [comment]
Thank you, this insight is really appreciated! 

On IPFS end we have https://github.com/ipfs/distributions which is responsible for building and publishing artifacts at https://dist.ipfs.io/#go-ipfs website, I can reach out to people and see how much of already existing process can be reused. 

Before we dive into details, I have a question about `ipfs_build_scripts`: **is build from source mandatory?**  Are you building Tor for Linux with a specific goal, eg. to solve dynamic linking issues present in the original build or something like that?

I ask because we already have [pre-built go-ipfs binaries for platforms you target with Brave](https://dist.ipfs.io/#go-ipfs) and we could download them from there just like it is done with Tor [here](https://github.com/brave/tor_build_scripts/blob/ca0f04d9ccbaff351f7103b29cfe83d0a3f1eef8/build_win32.sh#L7). It would simplify entire setup by removing a lot of moving pieces.

**Comment by drbh** [comment]
@lidel your a genuis! Pointing out [how Tor win32 is built](https://github.com/brave/tor_build_scripts/blob/ca0f04d9ccbaff351f7103b29cfe83d0a3f1eef8/build_win32.sh#L7) was super helpful. 

> Before we dive into details, I have a question about ipfs_build_scripts: is build from source mandatory? 

Retrospectively it seems like overkill to build from source. I was doing so only because I was following the path that the Tor binaries needed.

I understand now that they only built them from source for dynamic linking purposes - it seems that the Windows binary doesn't need the same dyn linking that the `darwin` and `linux` bins do

> I ask because we already have pre-built go-ipfs binaries for platforms you target with Brave 

Based on this we have two paths forward - including some sample code to get close to the intended goals


1. Directly downloading the ipfs precompiled binary - unzipping and storing. 
`Edits would take place in /tools/package_ipfs.js`
```
const request = require('request');
const os = require('os');
const fs = require('fs')

const tmpPath = `${os.tmpdir()}/ipfs-binary`;
var binary;
var opts = {
	"uri":"https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz", 
	gzip: true
}

console.log(tmpPath)
request(opts, function (err, res, body) { 
	fs.writeFile(tmpPath, body, 'binary', console.log);
})

```

2. Creating a bash shell build env - similar to how TorTabs did, to build rename and push binaries to S3
`Edits would take place in https://github.com/drbh/ipfs_build_scripts`
```
#!/bin/sh
set -eu
rm -rf go-ipfs/

export IPFS_WIN32_VERSION="0.4.17"
export BRAVE_TOR_VERSION="5"

curl -fsSl "https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v${IPFS_WIN32_VERSION}_windows-amd64.zip" -o ipfs-win32-$IPFS_WIN32_VERSION.zip

unzip ipfs-win32-$IPFS_WIN32_VERSION.zip

cp go-ipfs/ipfs.exe .
mv ipfs.exe ipfs-$IPFS_WIN32_VERSION-darwin-brave-$BRAVE_TOR_VERSION.exe
```


It seems like the first way of fetching the binaries within Brave is the easiest path forward. However it is noted that Tor binaries have been compiled and pushed to a S3 location. Maybe there is value in this data flow, however it seems unneeded for IPFS because it doesn't depend on dynamic linking.

I can take on the `/tools/package_ipfs.js` file and downloading IPFS directly if this seems like the best way forward

**Comment by lidel** [comment]
@drbh To keep momentum going let's go with direct download for now (1) and see if that works well enough. If it turns out we  need custom build for some platforms or Brave decides they want to host files at S3 to control user experience end-to-end, we can always add step (2) at a later stage.

FYI dist.ipfs.io has a valid [DNSLink](https://docs.ipfs.io/guides/concepts/dnslink/), which means fetching from  https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.17/ (or any other public gateway) will also work.

**Comment by darkdh** [comment]
for packaging binary, I suggested taking a look at https://github.com/brave/brave-core/pull/316, we use different method in brave-browser.

**Comment by drbh** [comment]
@darkdh thanks for the suggestion. I am looking at [/brave-core/pull/316](https://github.com/brave/brave-core/pull/316) now and I don't fully understand where the binary is pulled and packaged. 

Looking in [/brave-core/tree/master/browser/extensions](https://github.com/brave/brave-core/tree/master/browser/extensions) I see a few files that reference Tor but they seem to only reference a Tor client update.

**Questions**

1. Where is TorTab's Tor packaged?
2. What is the difference of packaging in Brave Browser vs Brave Core?
3. Are parts of Brave Browser's Tor client related to the Brave Core Tor client? 
4. Is packaging IPFS in Brave Browser less reliable in some way then Brave Core?

Any clarification is greatly appreciated! Thanks

**Comment by drbh** [comment]
### Updates!

- [X] Build go-ipfs from source for all supported platforms linux, darwin and win32 like brave/tor_build_scripts builds Tor
- [ ] ~~update the tools/buildPackage.js file to include ipfs binaries~~ 
- [X] add new file called tools/package_ipfs.js that fetches and verifies the signature of a precompiled ipfs binary

In addition - the biniary is pulled via dist.ipfs.io

> FYI dist.ipfs.io has a valid DNSLink, which means fetching from https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.17/ (or any other public gateway) will also work.

### Issues
- [ ] ipfsd-ctl not configured for storage
- [ ] ports are not working when attempting to specific on ipfsd-ctl server and daemon start
- [ ] ipfs daemon fails to start with `npm start` likely due to `app/filter.js` not correctly setup

ipfs daemon starts when the `ipfs.js` script is loaded into a node command line.

### Error

![iipfs-brave-fail](https://user-images.githubusercontent.com/9896130/44863289-b63fec00-ac4a-11e8-819e-66d9b7461803.png)

Above code that fails:
```
mystart () {
    console.log('My Start')

    server.start((err) => {
      if (err) { throw err }
      console.log('Server Start')
      console.log(f)

// FAILS HERE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
      f.spawn(options, (err, ipfsd) => {
        if (err) { throw err }
        console.log('Deamon Start')
        // this._process = ipfsd

        console.log('http://' + ipfsd.api.apiHost + ':' + ipfsd.api.apiPort + '/webui')

        ipfsd.api.id(function (err, id) {
          if (err) { throw err }

          // console.log(id.api.apiPort)
          // ipfsd.stop(server.stop)
        })
      })
    })

    console.log('Server Has Been Started')
  }
```

I don't exactly understand why the build fails when using `npm start` the install and packaging process succeeds with `npm install`

IPFS packaging and barebones daemon management - [ipfsPackageBuild branch](https://github.com/brave/browser-laptop/compare/master...drbh:ipfsPackageBuild)

**Comment by lidel** [comment]
@drbh apologies for not getting to it earlier, slipped thru my notifications. 

The main use for `ipfsd-ctl`  is  test suite of IPFS itself, 
so  it may be rough around edges specific to our use case.

Are you still blocked by the above error?
Isn't `browser-laptop` the old Muon-based codebase, and we should aim for [`brave-browser`](https://github.com/brave/brave-browser)/`brave-core` instead?

**Comment by drbh** [comment]
Just submitted a PR [https://github.com/brave/brave-core-crx-packager/pull/21](https://github.com/brave/brave-core-crx-packager/pull/21) following the Tor CRX bundling

**Comment by da2x** [comment]
Will creators be able to earn Brave Rewards for content distributed over IPFS?

Creators could claim their IPNS by publishing the `brave-payments-verification.txt` under their IPNS. Brave could verify this using a public HTTP gateway such as `https://cloudflare-ipfs.com/ipns/<id>/.well-known/brave-payments-verification.txt`. The Brave client would have to recognize and attribute time spent on `http://127.0.0.1:8080/ipns/<id>/*`, `https://*/ipns/<id>/*` (public gateways), `ipns://<id>/*`, and `dweb://ipns/*<id>` to `ipns://<id>`.

**Comment by mathiasrw** [comment]
@da2x This is such a good idea. Lets implement IPFS first and then integrate it into the attention economy!

**Comment by lidel** [comment]
# Notes on bringing IPFS to Brave in 2019

I had a chat with @bbondy about ways we can deliver better IPFS experience  in Brave, given where both projects are right now. 

Below is a short (well, I tried..) summary of takeaways and low hanging fruits we were able to identify to speed up IPFS integration.

## Today: IPFS works in Brave, but UX could be much better

IPFS Companion extension can be installed in Brave from [Chrome Store](https://github.com/ipfs-shipyard/ipfs-companion#ipfs-companion), with some caveats:

- to use real IPFS transport it requires external daemon to be installed on localhost as well (current options: [go-ipfs](https://github.com/ipfs/go-ipfs) or [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop)).
- (Problem 1) even if user has a local daemon installed and running, IPFS URLs in location bar will start with `http://127.0.0.1:8080/ipfs/` instead of `ipfs://` and origin-based security perimeter will be shared by all IPFS websites.


## Future: how it could work

We want to ship native IPFS support with Brave in 2019. 
What we mean by that in UX terms is:

MVP:

- Brave ships with IPFS detection and gives user an option to enable support for it
  - Detects the first time user tries to access IPFS resource and asks if support for IPFS should be installed (in form of IPFS Companion)
  - Explicit opt-in via an informative screen – flow similar to Widevine ([screenshot](https://ipfs.io/ipfs/QmNuP5hFymRBuVrwL8JwDKd2T7QeX5GbSsWQg64Utxur1o)), but more friendly and educational
  - After IPFS install embedded IPFS node is started and the initially requested URL is loaded over IPFS 
  - User can turn IPFS node on/off at any time via UI of IPFS Companion extension ([screenshot](https://user-images.githubusercontent.com/157609/42685002-18c7cee4-8692-11e8-9171-970866d91ae0.gif))

Ideal:
- keep `ipfs://` in location bar (native protocol handler)
- local discovery and p2p transport (to see and talk to other IPFS nodes in LAN without centralized signaling server)

## How to get there?

In 2019 there are two ways to do enable it, each comes with own set of challenges:

### **(A)** Bundling **go-ipfs** binary with Brave and talking to it via ipfs-companion

  - requires additional orchestration to start/stop/upgrade [go-ipfs](https://github.com/ipfs/go-ipfs) daemon binary
  - ipfs-companion talks to  daemon over [HTTP API](https://docs.ipfs.io/reference/api/http/) exposed on localhost TCP port
  - go-ipfs node talks to IPFS swarm over TCP/QUIC transports
  - separate process, huge surface, harder to audit  
  - (Problem 1) keeping `ipfs://` scheme in  location bar would solve Origin-based security, but requires (currently missing) protocol handler API in WebExtension context
  
### **(B)** Embedded **js-ipfs** running in ipfs-companion (WebExtension context)

  - _(JS implementation matured a lot, our browser extension is able to use it as a drop-in replacement for go-ipfs)_
  - no binary, [pure JS implementation](https://github.com/ipfs/js-ipfs)
  - managing in-memory node via [programmatic JS API](https://github.com/ipfs/js-ipfs#api)
  - easier to audit, reusing most of WebExtension sandbox
  - regular JS cant open raw TCP sockets, so js-ipfs node talks to the swarm over websockets (or webrtc)
    - Brave enables huge improvement here: ipfs-companion can be marked as `blessed_extension` and gain access to [raw socket APIs](https://github.com/brave/brave-core/blob/bc836d540a9aef6c5371fad89f5da2f77f7a212e/common/extensions/api/_api_features.json#L61-L75), which would enable local discovery and p2p transports (see relevant PoC for Firefox: [libdweb discovery and transport](https://github.com/ipfs-shipyard/ipfs-companion/pull/553#issuecomment-420325539))
  - (Problem 1) keeping `ipfs://` scheme in  location bar would solve Origin-based security, but requires (currently missing) protocol handler API in WebExtension context
  - (Problem 2) Important caveat: js-ipfs running in browser context is unable to open TCP port to provide HTTP Gateway, nor can ipfs-companion inject responses via [webRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest) API. How do we return payload (regular websites) then?
    - (Fix 1 - the best): If we have `ipfs://` and proper protocol handler API, then this is not an issue, as payload can be injected inside of the handler. We already confirmed this approach works in [libdweb experiment: protocol handler API](https://github.com/ipfs-shipyard/ipfs-companion/pull/533).
    - (Fix 2 - second best): if ipfs-companion is `blessed_extension` in Brave, then   access to [`sockets.tcpServer`](https://github.com/brave/brave-core/blob/bc836d540a9aef6c5371fad89f5da2f77f7a212e/common/extensions/api/_api_features.json#L66), enables us to expose js-ipfs HTTP Gateway over a regular TCP port. Not as good as (Fix 1), but as good as Gateway exposed by (go-ipfs) and does not require changes to Brave.
    - (Fix 3 - backup option): it might be possible to pass payload into Service Worker-based Access Point exposed at our public gateway (relevant approach currently researched by @Gozala in [lunet](https://github.com/Gozala/lunet/) experiment).
 

### Which one is more feasible?

While (A) was the way we planned to integrate in 2018, (B) is self-contained (execution context is limited to ipfs-companion extension), which may be easier to manage, audit and ship today, as IPFS project has a lot of relevant plumbing in place in js-ipfs and ipfs-companion thanks to [mozilla/libdweb](https://github.com/mozilla/libdweb) and other work that happened in recent months.

Shipping Brave-powered js-ipfs node in ipfs-companion being `blessed_extension` (B) may simply take less work.

Sidenote: both (A) and (B) can benefit from native Protocol Handler API:
- the use case for IPFS handler is demonstrated in [libdweb experiment: protocol handler API](https://github.com/ipfs-shipyard/ipfs-companion/pull/533) (tl;dr: watch [this](https://youtu.be/fS8pLOQdOoM?t=90) 4 minute live demo)
- worth noting, this type of generic handler API could enable other DWeb projects ([DAT](https://datproject.org/), [SSB](https://www.scuttlebutt.nz/)) to create native client extensions for Brave, so this may be delivered as a community effort, similar to [mozilla/libdweb](https://github.com/mozilla/libdweb)

## What are the next steps?

IPFS roadmap for bringing IPFS to Brave in 2019 will include (P0 - priority): 

- Marking ipfs-companion as `blessed_extension` and making use of [raw socket APIs](https://github.com/brave/brave-core/blob/bc836d540a9aef6c5371fad89f5da2f77f7a212e/common/extensions/api/_api_features.json#L61-L75) for:
  - (P0) (MVP) Exposing localhost HTTP Gateway (making js-ipfs node running in WebExtension is as useful as go-ipfs)
  - (P3) Local Discovery and better p2p transports
- (P1) Onboarding experience in Brave ("Detects the first time user tries to access IPFS resource and asks if support for IPFS should be installed") 
- (P2) Creating protocol handler API for Chromium (porting [libdweb experiment](https://github.com/ipfs-shipyard/ipfs-companion/pull/533) from Firefox)

Note: "Bundling go-ipfs with Brave" is still a possibility, and work done on extension responsible for binary updates may be resumed and used in the future, but we want to see if we can expose HTTP Gateway over `chrome.sockets.tcpServer`. If that is possible, we may be able to ship sooner than later.

If js-ipfs approach takes too much time, or (P0/MVP) does not work as expected, we can always focus back on bundling go-ipfs.

**Comment by lidel** [comment]
@da2x js-ipfs is actually making good progress on those fronts:

IPNS over pubsub and DHT will be enabled by default in js-ipfs 0.35, but we can experiment with it today as it is opt-in since [v0.34.0](https://github.com/ipfs/js-ipfs/releases/tag/v0.34.0). 

DNSLink lookup already works. In web browser context js-ipfs is delegating lookups to our public gateway ([runtime/dns-browser.js](https://github.com/ipfs/js-ipfs/blob/v0.34.1/src/core/runtime/dns-browser.js)), and in the future this can be improved by using a dedicated WebExtension API ([like this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1449171)), falling back to one of public [DNS-over-HTTPS](https://developers.google.com/speed/public-dns/docs/dns-over-https) providers or implementing Node.js `dns` API using `chrome.sockets.*`. 

> Does trying to access a transparently HTTP gatewayed resource over an DNSLink mapped domain count as “the first time user tries to access IPFS resource”? 

I think good candidates for "detecting IPFS without ipfs-companion" (very light on resources):
- Presence of requests to paths starting with `/ipfs/<cid>`   
  _(website assets or URL in location bar)_
- HTTP response headers including [`x-ipfs-path`](https://github.com/ipfs-shipyard/ipfs-companion/blob/v2.7.0/docs/x-ipfs-path-header.md#hinting-dnslink-lookups) 
  _(best-effort way to detect DNSLinked sites without expensive lookups)_
- JS on a website making a getter call for `window.ipfs` 
  _(reliable signal website could opportunistically use native ipfs support, similar to `window.ethereum` and MetaMask)_

**Comment by MidnightLightning** [comment]
Thank you for making strides in this direction! One aspect of a deeper integration between Brave and IPFS is more intuitive viewing/loading of IPFS-hosted files, based on MIME type. In https://github.com/ipfs-shipyard/ipfs-webui/issues/920 I brought up the fact that the way that the embedded video player in Chrome doesn't work ideally with how IPFS loads data at a low-level; even if  a Brave user doesn't have an IPFS node running of their own, I think there's an opportunity there for how the Brave browser itself loads and views videos and pictures if it detects it's being loaded via IPFS could be optimized.

**Comment by MicahZoltu** [comment]
While full IPFS integration would certainly be nice, we can gain a significant portion of the benefits of IPFS by implementing the much simpler process of validating IPFS hashes.  The browser can be pre-configured with known IPFS gateways (including localhost) and have a configuration page for adding more.  When a user browses a page that matches a configured IPFS regex (e.g., `https?://cloudflare-ipfs.com/ipfs/([^/])+`) it would validate the hash for the fetched file matches the hash in the URL.  When it doesn't match, a security pop-up can be presented to the user just like if the SSL key didn't validate.

While this doesn't give us the guaranteed availability that IPFS does, it _does_ give us the security of knowing that the data we are receiving is the expected data, thus allowing people to trustlessly utilize IPFS gateways (at the moment, IPFS gateways serve almost no purpose since you still have to trust them, and they can censor content).

For me, and I think many others, this is a big win from IPFS and I believe the amount of work required to achieve this is _much_ smaller than the amount of work required to do full P2P IPFS fetching of content.

**Comment by nileshtrivedi** [comment]
What's the current state of native IPFS integration in Brave?

**Comment by lidel** [comment]
We are exploring Option (B) from https://github.com/brave/brave-browser/issues/819#issuecomment-456039555:
- Ongoing work on Embedded JS-IPFS in Brave is tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/716
  > - `chrome.sockets` and an opt-in prototype of Embedded Gateway (https://github.com/ipfs-shipyard/ipfs-companion/issues/664#issuecomment-481697875) work only when built via `yarn dev-build bundle:brave:beta` and loaded manually to [Brave Nightly](https://brave.com/download-nightly/)
  >   - Seamless install from Chrome Web Store is not possible yet, it requires [Manifest patch in Brave](https://github.com/brave/brave-browser/issues/3899)
  >   - Experimental prebuilt `_brave.zip` package for Brave Nightly is attached to [this](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.8.2) release, but YMMV

**Comment by kirkins** [comment]
Any updates on IPFS?

**Comment by lidel** [comment]
Yes! 

### One-click-install

Stable release of IPFS Companion can be enabled directly via Brave Settings (`chrome://settings/extensions`):

> ![2019-09-20--14-43-17](https://user-images.githubusercontent.com/157609/65327738-0458c200-dbb5-11e9-95d5-5393591388f6.png)

By default, it works like regular ipfs-companion and  `External` node is used by default, assuming user has [go-ipfs](https://github.com/ipfs/go-ipfs#go-ipfs) or [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop#ipfs-desktop) installed and running.


### Experimental embedded JS IPFS node

Brave users (oh the pun..) can opt-in and try experimental `Embedded + chrome.sockets`
(see [/docs/node-types](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/node-types.md) for more details). 

**Note:** embedded js-ipfs will remain experimental opt-in until performance/ux gets closer to one with External node (js-ipfs is missing native DHT, uses delegated routing for now).

> ![2019-09-20--14-44-37](https://user-images.githubusercontent.com/157609/65327907-66192c00-dbb5-11e9-962f-9b5cd122572f.png)

> ![2019-09-20--14-45-06](https://user-images.githubusercontent.com/157609/65327962-7fba7380-dbb5-11e9-954b-6a18136eef60.png)

### Where to track work on Companion?

Meta issue on embedded js-ipfs is at https://github.com/ipfs-shipyard/ipfs-companion/issues/716, we also track v1 and v2 stages of IPFS integration in [ipfs-companion/projects/4](https://github.com/ipfs-shipyard/ipfs-companion/projects/4) :lion: 

There also a broader [IPFS Browser Update published on blog.ipfs.io](https://blog.ipfs.io/2019-10-08-ipfs-browsers-update/). Expect Brave-specific one in following weeks.

**Comment by bbondy** [comment]
Duping to this one, we can create other follow-ups from that too which are more specific and smaller than this issue. Thanks everyone for the discussions above.
https://github.com/brave/brave-browser/issues/10220
