### ISSUE TITLE
[Desktop] [Meta] Use OS location services where they exist

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8451]
In order to reduce the load on `location.brave.com` and improve accuracy for the [GeoLocation API](https://www.w3.org/TR/geolocation-API/), we should take advantage of platform location services where they exist, just like we do on [Android](https://github.com/brave/browser-android-tabs/issues/2564#issuecomment-587967714) and [iOS](https://github.com/brave/brave-ios/issues/2343#issuecomment-591612826).

Such services exist on all of our supported platforms:

- Windows: https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Geolocation
- macOS: https://developer.apple.com/documentation/corelocation
- Linux: https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home

though maybe not all versions of Windows and all Linux distros will have such facilities available. When it's not available, the geoip fallback service at `location.brave.com` should be used.

User-facing documentation for these location services is also available:
- Google: https://support.google.com/chrome/answer/142065
- Apple: https://support.apple.com/en-us/HT204690
- Microsoft: https://support.microsoft.com/en-us/help/4468240/windows-10-location-service-and-privacy

- [x] Support OS location services on Windows - https://github.com/brave/brave-browser/issues/10722
- [x] Support OS location services on macOS - https://github.com/brave/brave-browser/issues/10724
- [ ] Support OS location services on linux - https://github.com/brave/brave-browser/issues/29715

**Comment by simonhong** [comment]
Upstream already implemented this behind the flag.
There are `WinRT Geolocation Implementation` flags for Windows and `Core Location Implementation` flags for macOS.
Linux is not yet supported yet.
By default `NetworkLocationProvider` is used if above flags are off.
It asks device's location to googles api service and it's proxied to our service.
If flags are on, `NetworkLocagtionProvider` is off and only device's LocationProvider are used.(`CoreLocationProvider` for macOS and `LocationProviderWinrt` for Windows) Also, user should enable OS's location service for allowing application access os location service. If it's disabled and flag is on, browser can't get location data anymore.

**Comment by ajacobs21e** [comment]
@simonhong Brave does not show up as an option for me under macOS location settings. How do I add Brave to the list to enable location service?

**Comment by fmarier** [comment]
It's great to hear that there is already code for this upstream.

From your description, it sounds like we could:

1. Enable the `WinRT Geolocation Implementation` on Windows, `Core Location Implementation` on Mac, and `NetworkLocationProvider` on Linux.
2. Add a runtime fallback for Windows and Mac in the case where the OS location service isn't available due to permission or otherwise.

**Comment by simonhong** [comment]
@fmarier On Windows, we only need to to enable `WinRT Geolocation Implementation`.
If that flag is on and OS location service is not enabled by user, `NetworkLocationProvider` is used instead.
I think we should add similar checkup for macOS if possible.

**Comment by simonhong** [comment]
@ajacobs21e I think it's automatically added by OS when application tries to use location service.
If you enable `Core Location Implementation` flag and tries `navigator.geolocation.getCurrentPosition()` in console(or any webservices that uses this api), I think macOS will add it. and you can see it in brave in the list. Then, you can enable brave.

**Comment by fmarier** [comment]
There is an open bug for Linux support (via geoclue): https://bugs.chromium.org/p/chromium/issues/detail?id=1093873

**Comment by Apro123** [comment]
Its been around a month since this this issue was tagged "General". Has there been any update on this? This is a pretty serious issue for websites that require (ACCURATE) location services to work.

**Comment by simonhong** [comment]
@Apro123 On windows, brave could utilize os location service from 1.13(currently beta) - https://github.com/brave/brave-browser/issues/10722
For macOS/linux, we are waiting to support this in upstream.

**Comment by thommesborg** [comment]
As started in issue #5795 I enabled OS location access on macOS in between. Using macOS 11.1

The given location is still, or again, incorrect. Checked with osm.org and GMaps I get the same location but false location in both. If I have a look in the OS' settings for location-service there is no indication that Brave even tried to find me. A recently try will be market with an arrow-symbol on the specific app,  but there is nothing to see at Brave.

I had Core Location Implementation enabled within Brave-Flags and also tested that by reverting to default to no avail. Still the same false location.

No issues with the location in Safari, Chrome, Firefox btw.

**Comment by thommesborg** [comment]
I walked through the flags again and had to also _change default for Core Location Backend to_ **enabled** and now it works as expected.

**Comment by thommesborg** [comment]
This is still an issue. People at the Brave community complaining about this and in detail, that my before mentioned flags aren't available in Brave for Linux and Windoze. Enable core-location services everywhere and set the flags to enabled by default = issue fixed.

**Comment by vassyz** [comment]
Changing `Core Location Implementation` doesn't fix anything, Google Maps still shows the wrong location. I'm getting the error `Your location could not be determined.` with `Core Location Backend` enabled.

**Comment by thommesborg** [comment]
@vassyz now there is a need to know what OS you use and if both flags, mentioned earlier, are available and enabled.

**Comment by vassyz** [comment]
@thommesborg I'm on MacOS 10.15.7, but just tried on my work laptop with MacOS 11.2.1 with both flags on and the location is correct 🤔

**Comment by thommesborg** [comment]
@vassyz I'm also on macOS 11.2.1 (20D74). I've read on a chromium-bug that you have to have Wi-Fi enabled to get a location. Just a thought!

**Comment by vassyz** [comment]
After I'd updated my personal laptop to Big Sur (currently on version 11.4) and enabling the flags the current location corrected itself. I noticed a few weeks ago that it changed back to the incorrect one (7 miles away). I'm on the latest Brave version (Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64)) and I can't seem to find the flags.

**Comment by TadWohlrapp** [comment]
Can confirm: the flags are gone on macOS Big Sur 11.4 and current Brave v1.26.74 and location services are broken again.

**Comment by bsclifton** [comment]
Closing as the Linux one is the only one remaining. We have other specific issues (ex: using Windows location services).
