### ISSUE TITLE
Video playback fails until adblock is toggled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#902]
Issue ported over from https://github.com/brave/browser-laptop/issues/8521

Sites on which video playback fails with adblock
- [x] imdb
- [x] espn
- [x] fox news via #1478  (also fails on Chrome + uBlock)
- [x] fox business (also fails on Chrome + uBlock)
- [x] pornhub.com via #1518
- [x] nytimes via https://github.com/brave/brave-browser/issues/1984#issuecomment-437939151
- [x]  https://abcnews.go.com via https://github.com/brave/brave-browser/issues/902#issuecomment-433093164
cc: @darkdh

**Comment by snyderp** [comment]
I cannot recreate the following sites in the beta
* imdb (Ex: https://www.imdb.com/list/ls025720609/videoplayer/vi4122655257?ref_=hm_hp_i_2)
* espn (ex: any videos on http://www.espn.com)

**Comment by srirambv** [comment]
This is surprising. IMDB and ESPN is allowing playback without having to disable shields/toggle adblock. Was there anything changed on the adblock library?

**Comment by Techguyprivate** [comment]
Weird behaviour. I am sending you a gif ,please look at it.

  1. I have disabled script blocking in Brave default shield in chrome://setting.

  2.  In chrome://setting , go to content setting ,then javascript toggle option showing disabled.

  3 .Also, there is no toggle button in all site content setting.

  4.  I have to enable javascript on every site manually through the brave shield right of url bar.

  5.  Then it showed of in javascript setting in chrome:// setting , content setting as allowed.

Same thing also in both brave dev and beta built on brave core ( not brave browser laptop built on muon,modifeid electron)

**Comment by srirambv** [comment]
- [ ] https://abcnews.go.com. Adblock blocks frame script which contains valid origins to load video. Toggle adblock loads the video correctly 
![image](https://user-images.githubusercontent.com/17010094/47505889-026b6f00-d83d-11e8-8e97-01cfafeba83e.png)
![image](https://user-images.githubusercontent.com/17010094/47505903-08615000-d83d-11e8-8d95-ae9ed79e39d7.png)

**Comment by isiahmeadows** [comment]
BTW, I'll note I *do* get PornHub playback (including PornHub Live) in Chrome + uMatrix with these rules, but with a few caveats:

- I do get their fake popup ads (they open a new tab to destination, focus on that tab, then set existing tab to an ad without focusing) when I click "Porn Videos".
- I get the TrafficJunky ad placeholders, even though no ads are actually loaded.
- I so far *haven't* been able to get it to load without dropping the `naiadsystems.com` rules - those may need stubbed.

```
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
pornhub.com naiadsystems.com script allow
pornhub.com naiadsystems.com xhr allow
pornhub.com phncdn.com frame allow
pornhub.com phncdn.com media allow
pornhub.com phncdn.com script allow
pornhub.com pornhublive.com frame allow
pornhub.com pornhublive.com script allow
pornhub.com rncdn3.com media allow
```

**Comment by GeetaSarvadnya** [comment]
1+https://community.brave.com/t/fox-news-videos-will-not-play/45910

**Comment by ryanbr** [comment]
Foxnews adblock annoyance:

`@@||fncstatic.com/static/v/all/js/ads.js`

**Comment by ryanbr** [comment]
Regarding the abcnews.go.com, seems to be related to possibly blocking of akamai html script

```
   https://79423.analytics.edgekey.net/html5/akamaihtml5-min.js
```
Blocking scripts like this will cause intermittent video

**Comment by Brave-Matt** [comment]
User reporting fox news video play back issue:
https://community.brave.com/t/on-the-fox-news-website-videos-arent-playing/69496

**Comment by ryanbr** [comment]
I thought foxnews this was fixed, okay this will need a bit to debug.

**Comment by Brave-Matt** [comment]
Another report of fox news videos not playing until sheilds are down/ads are allowed:
https://community.brave.com/t/videos-dont-play-from-fox-news/81622/3

**Comment by ryanbr** [comment]
I've fixed abcnews, if someone can confirm?

Tested with `https://abcnews.go.com/Entertainment/kim-kardashian-west-backlash-working-trump-choose-alice/story?id=65571704`

And from the main page; `https://abcnews.go.com/`

Working on getting foxnews atm.

**Comment by ryanbr** [comment]
Foxnews and Foxbusiness should work now

**Comment by bkarlan** [comment]
Not working.  I'm using Brave Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by antonok-edm** [comment]
@ryanbr it looks to me like videos on foxbusiness articles are still broken

**Comment by ryanbr** [comment]
Checking Foxnews/Fox Business is now working.

Regarding the Imdb issue @thefallofbecause : https://github.com/brave/brave-browser/issues/13101

**Comment by ryanbr** [comment]
Before closing ticket. reviewed the following sites and sample links. 

With default shield settings, the following sites were checked for video playback and confirmed:

`https://www.imdb.com/video/vi3657416729?ref_=hm_hp_i_1&listId=ls053181649`  **Worked**. 
`https://www.espn.com/soccer/borussia-dortmund/story/4358642/bellingham-ready-to-succeed-haalandsancho-as-dortmunds-brightest-prospect`  **Worked**
`https://video.foxnews.com/v/6249541545001#sp=show-clips`    **Worked**
`https://www.foxbusiness.com/lifestyle/united-airlines-boeing-777-engine-pratt-whitney-resume-flying `  **Worked**
`https://www.pornhub.com/view_video.php?viewkey=xxxxxx`  **Worked**
`https://www.nytimes.com/video/us/politics/100000007721570/biden-george-floyd-verdict.html`  **Worked**
`https://abcnews.go.com/Health/video/volunteers-launch-websites-people-access-covid-19-vaccines-76342641`  **Worked**.

Any other issues with various sites, we should just log a issue report per site.  cc: @srirambv
