### ISSUE TITLE
[Android] Manual test run on Android Tab for 1.5.x HF 2 Android release

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9082]
## Per-Release checklist

- [x] [Android] Brave block cookies and can't be be deleted ([#9055](https://github.com/brave/brave-browser/issues/9055))
- [x] [Android] Replace Chromium incognito icon ([#9046](https://github.com/brave/brave-browser/issues/9046))
- [x] [Android] Closing all tabs doesn't close Brave when setting is enabled ([#9044](https://github.com/brave/brave-browser/issues/9044))

## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Visual look

- [x] Make sure thereafter every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Bookmarks

- [x] Verify that creating a bookmark works
- [x] Verify that clicking a bookmark loads the bookmark
- [x] Verify that deleting a bookmark works
- [x] Verify that creating a bookmark folder works

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)

## Find in page

- [x] Ensure search box is shown when selected via the hamburger menu
- [x] Verify that you can successfully find a word on the page
- [x] Verify that the forward and backward navigation icons under find are working
- [x] Verify failed to find shows 0 results

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [ ] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected 

## Background

- [x] Start loading a page, background the app, wait > 5 sec, then bring to front, ensure splash screen is not shown

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by srirambv** [comment]
Looks good
