### ISSUE TITLE
Rewards Everywhere phase 1

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9130]
- [x] Banner UI https://github.com/brave/brave-browser/issues/11393
- [x] Panel UI https://github.com/brave/brave-browser/issues/11929
- [ ] Greaselion
  - [x] Youtube https://github.com/brave/brave-browser/issues/9133
  - [x] Twitter https://github.com/brave/brave-browser/issues/11462
  - [x] Github https://github.com/brave/brave-browser/issues/11463
  - [x] Reddit https://github.com/brave/brave-browser/issues/11464
  - [x] Vimeo https://github.com/brave/brave-browser/issues/11465
  - [x] Twitch https://github.com/brave/brave-browser/issues/11466
- [x] Remove main switch https://github.com/brave/brave-browser/issues/11467
- [x] Non-persistent extension https://github.com/brave/brave-browser/issues/6462
- [x] Fix GL publishers https://github.com/brave/brave-browser/issues/12307
- [x] Uphold modal https://github.com/brave/brave-browser/issues/11431
- [x] [Desktop] Earn&Give onboarding https://github.com/brave/brave-browser/issues/12138
- [x] [Android] Earn&Give onboarding https://github.com/brave/brave-browser/issues/12141

**Comment by bughit** [comment]
If the user explicitly does not want to use your rewards system, saying "Rewards Everywhere" means nothing to them. You do realize that there's a sizable chunk of your user base that just want a stable, lean, non-spying chromium? Ramming rewards down their throats will only create hostility to it that would not exist were it completely optional (which has to mean none of it is running when disabled)

**Comment by NejcZdovc** [comment]
I understand where you are coming from and are designing Rewards everywhere with this thinking in mind. We will not enable stuff like auto contribute or ads by default, this is still opt in. Will provide more info like I said when we have final spec for it
