### ISSUE TITLE
Manual test run on Windows x64 for 1.8.x - Release Hotfix 3

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#9738]
## Per release specialty tests
 - [ ] `NTP Sponsored Images` component should refresh sooner.([#9590](https://github.com/brave/brave-browser/issues/9590))
 - [x] Implement pagination for publisher list.([#9607](https://github.com/brave/brave-browser/issues/9607))
 - [x] May ads payout recovery.([#9684](https://github.com/brave/brave-browser/issues/9684))

### Installer

- [x]  Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Data(Upgrade from previous release)

- [x]  Make sure that data from the last version appears in the new version OK
- [x]  With data from the last version, verify that
  - [x]  bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x]  cookies are preserved
  - [x]  installed extensions are retained and work correctly
  - [x]  opened tabs can be reloaded
  - [x]  stored passwords are preserved
  - [x]  unpinned tabs can be pinned

### Widevine

- [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
- [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

### Rewards

- [x]  Verify wallet is auto created after enabling rewards
- [x]  Verify account balance shows correct BAT and USD value
- [x]  Verify you are able to restore a wallet
- [x]  Verify wallet address matches the QR code that is generated under `Add funds`
- [x]  Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x]  Verify adding funds via any of the currencies flows into wallet after specified amount of time
- [x]  Verify adding funds to an existing wallet with amount, adjusts the BAT value appropriately
- [x]  Verify monthly budget shows correct BAT and USD value
- [x]  Verify you are able to exclude a publisher from the auto-contribute table by clicking on the `x` in auto-contribute table and popup list of sites
- [x]  Verify you are able to exclude a publisher by using the toggle on the Rewards Panel
- [x]  Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [x]  Verify when you click on `Send a tip`, the custom tip banner displays
- [x]  Verify you are able to make one-time tip and they display in tips panel
- [x]  Verify you are able to make recurring tip and they display in tips panel
- [x]  Verify you can tip a verified publisher
- [x]  Verify you can tip a verified YouTube creator
- [x]  Verify tip panel shows a verified checkmark for a verified publisher/verified YouTube creator
- [x]  Verify tip panel shows a message about unverified publisher
- [x]  Verify BR panel shows message about an unverified publisher
- [x]  Verify you are able to perform a contribution
- [x]  Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators
- [x]  Verify that disabling Rewards and enabling it again does not lose state
- [x]  Verify that disabling auto-contribute and enabling it again does not lose state
- [x]  Adjust min visit/time in settings. Visit some sites and YouTube channels to verify they are added to the table after the specified settings
- [x]  Upgrade from older version
  - [x]  Verify the wallet balance is retained and wallet backup code isn't corrupted
  - [x]  Verify auto-contribute list is not lost after upgrade
  - [x]  Verify tips list is not lost after upgrade
  - [x]  Verify wallet panel transactions list is not lost after upgrade

### Ads Upgrade Tests:

- [x]   Install 0.62.51 and enable Rewards (Ads are not available on this version). Update on `test` channel to the hotfix version. Verify Ads are off by default, should get a BAT logo notification to alert you that Ads are available.
- [x]   Install 0.64.77 and enable Rewards. Ads are on by default. View an Ad. Update on `test` channel to the hotfix version. Verify Ads are still on after update, Ads panel information was not lost after upgrade, no BAT logo notification.
- [x]   Install 0.64.77 and enable Rewards. Disable Ads. Update on `test` channel to the hotfix version. Verify Ads are still off after update, no BAT logo notification.
- [x]   Install `1.8.90 CR: 81.0.4044.129` and enable Rewards. Ads are on by default. View an ad. Update on `test` channel to the hotfix version. Verify Ads are still on after update, Ads panel information was not lost after upgrade, no BAT logo notification.
- [x]   install `1.8.90 CR: 81.0.4044.129` and enable Rewards. Disable Ads. Update on `test` channel to the hotfix version. Verify Ads are still off after update, no BAT logo notification.

### Session storage

- [x]  Temporarily move away your browser profile and test that a new profile is created when browser is launched 
  - macOS - `~/Library/Application\ Support/BraveSoftware/`
  - Windows - `%userprofile%\appdata\Local\BraveSoftware\` 
  - Linux(Ubuntu) - `~/.config/BraveSoftware/`
- [x]  Test that windows and tabs restore when closed, including active tab
  - [x] Ensure that the tabs in the above session are being lazy loaded when the session is restored

## Update tests

- [x]  Verify visiting `brave://settings/help` triggers update check
- [x]  Verify once update is downloaded, prompts to `Relaunch` to install update

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
